### PR TITLE
Update Docs Posthog apikey

### PR DESCRIPTION
**Pull request by slumbering**
The new apiKey target Posthog Docs-0.3 project (everything is ready on PostHog)

Capture d’écran 2022-10-21 à 16 06 48

This PR has to be merged for launch.

Signed-off-by: jffarge <jf@dagger.io>

### CODE REVIEW

**Comment by slumbering** [comment]
cc @mircubed

**Comment by mircubed** [comment]
@gerhard @samalba There is a PR draft from JF that is related to the docs analytics, but I am not sure if it is attached to the right site since the plan changed a few times. Could you review this and update it if needed?

**Comment by gerhard** [comment]
The key is correct: https://app.posthog.com/project/settings

image

That's the only change which this PR introduces - it looks good to me.

Not sure how we will know if this works as expected, but my suggestion is to merge it when we are ready to launch the new docs and see what happens.

WDYT @vikram-dagger @shykes?

**Comment by shykes** [comment]
Agreed. Preparing to merge.

**Review by shykes — APPROVED** [review]

**Pull request merged**
