### PR TITLE
Import .NET SDK as Experimental

### PR DESCRIPTION
**Pull request by gerhard**
Fixes DEV-1031 

This imports https://github.com/nabsul/DaggerSDK under `sdk/dotnet` as an **experimental** SDK.

## @gerhard action items (part of this PR)
- [x] Open PR with https://github.com/nabsul/DaggerSDK history import
	- [x] Capture commands used for history import
```console
git remote add dagger-sdk-dotnet https://github.com/nabsul/DaggerSDK
git fetch dagger-sdk-dotnet --no-tags
git checkout -b sdk/dotnet dagger-sdk-dotnet/main
mkdir -p sdk/dotnet
git ls-tree -z --name-only HEAD | xargs -0 -I {} git mv {} sdk/dotnet/
git commit --gpg-sign --signoff

git checkout main
git pull
git checkout -b import-sdk-dotnet

git merge --gpg-sign --signoff --allow-unrelated-histories sdk/dotnet

git push -u fork
```
- [x] Give @nabsul write permissions to `dagger` repository
- [x] Add @nabsul to [`CODEOWNERS`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) (`@dagger/sdk-dotnet` group)
- [x] Mention in SDK's README that it is currently experimental

## @nabsul action items (part of this PR)
- [x] Configure `Sign-off-by` https://docs.dagger.io/204441/contributing/#dco
  - @gerhard manually set this to **Pass** so that @nabsul does not need to rewrite commits

## Follow-ups (outside / after this PR)

- Migrate https://github.com/nabsul/DaggerSDK/pull/1 if still relevant
- Add commit to https://github.com/nabsul/DaggerSDK that removes all files except the README
	- Add repo migration notice to `README.md`
	- Archive repository in GitHub, e.g. https://github.com/thechangelog/infrastructure

Did I miss anything @nabsul?

### CODE REVIEW

**Review by jpadams — APPROVED** [review]
👍 Super excited for this work to continue! Thanks @nabsul !!

**Comment by gerhard** [comment]
Does this looks good to you @nabsul? I'm keen to get this merged early next week.

**Comment by nabsul** [comment]
This looks great, thanks @gerhard ! :shipit:

**Review by nabsul — APPROVED** [review]

**Comment by gerhard** [comment]
Any chance of actioning the following @nabsul?
* Add commit to https://github.com/nabsul/DaggerSDK that removes all files except the README
  * Add repo migration notice to README.md
  * Archive repository in GitHub, e.g. https://github.com/thechangelog/infrastructure

Here is what the Elixir SDK did: https://github.com/wingyplus/dagger_ex

**Pull request merged**
