### PR TITLE
Keep go.opentelemetry.io/otel versions in sync with BuildKit

### PR DESCRIPTION
**Pull request by gerhard**
https://github.com/moby/buildkit/blob/v0.10.3/go.mod#L62-L68

Otherwise we can introduce data races and other weird behaviour:
- (jaeger v1.6.0) data races https://github.com/dagger/dagger/runs/7359366602?check_suite_focus=true#step:8:1433
- (jaeger v1.8.0) conflicting Schema URLs https://github.com/dagger/dagger/runs/7358945187?check_suite_focus=true#step:8:2066

Also mentioned in https://github.com/dagger/dagger/pull/2446#issuecomment-1126377411

<a href="https://gitpod.io/#https://github.com/dagger/dagger/pull/2808"></a>

### CODE REVIEW

**Comment by gerhard** [comment]
Noticed that `react-scripts` keeps failing randomly, pretty sure that we have a flaky test on our hands.

**Comment by gerhard** [comment]
Leaving this with you @aluzzardi, after we shared context synchronously.

**Comment by aluzzardi** [comment]
In an ideal world this should never be a problem (otel is meant for tracing across micro services, version mismatch is OK) but I'd rather we don't spend too much time on this.

Let's go ahead with this as is, we can revisit someday

/cc @sipsma

**Comment by gerhard** [comment]
Needs a LGTM before it can be merged. Any 👍 will do: @helderco @sipsma @aluzzardi

**Review by sipsma — APPROVED** [review]

**Pull request merged**
