### PR TITLE
universe(x/kubectl): update kustomize with latest version

### PR DESCRIPTION
**Pull request by TomChv**
Since https://github.com/bitnami/bitnami-docker-kubectl/pull/43 has been merge, this PR updates the experimental package default version to latest version and adds a test.

Signed-off-by: Vasek - Tom C <tom.chauveau@epitech.eu>

### CODE REVIEW

**Comment by mircubed** [comment]
@jpadams reminder to review :)

**Review by samalba — CHANGES_REQUESTED** [review]
@TomChv Could you move this change to pkg/universe.dagger.io/alpha/?

**Comment by TomChv** [comment]
> @TomChv Could you move this change to pkg/universe.dagger.io/alpha/?

I cannot because the current [Kustomization package in alpha](https://github.com/dagger/dagger/tree/main/pkg/universe.dagger.io/alpha/kubernetes/kustomize) is completely different of mine :/

**Comment by jpadams** [comment]
before we can move this to `alpha` we need to see if we can unify this with 
https://github.com/dagger/dagger/blob/main/pkg/universe.dagger.io/alpha/kubernetes/kustomize/kustomize.cue

**Comment by TomChv** [comment]
I'm not sure we can since we are not even using the same base image :/
My package has its own logic that is totally different from alpha's

**Review by jpadams — APPROVED** [review]
Going to merge this in `x` and continue to look for way to get this into `alpha`.

**Review by gerhard — APPROVED** [review]
This change looks straightforward, I am on board with @jpadams: OK to merge as soon as all checks are green.

**Pull request merged**
