### PR TITLE
Container: add `build`

### PR DESCRIPTION
**Pull request by vito**
needed for #3210 

Implements the following API, based on #3151:

```graphql
extend type Container {
  build(context: DirectoryID!, dockerfile: String): Container!
}
```

* I decided to go with `context` and `dockerfile` for the param args since they felt a bit more descriptive. They are both terms described in the [Docker docs](https://docs.docker.com/engine/reference/commandline/build/#description).
* I decided to have this live on `Container` instead of `Directory`. It's true that it always takes a `Directory`, but I like the symmetry with `container.from` and `container.withFS` as the final goal is to build a `Container`, just like them.

Also, moved `container.from` implementation to `(*core.Container).From` for consistency.

### CODE REVIEW

**Comment by jlongtine** [comment]
I like `container { build }`, but I'm noticing it feels weird to be able to do:

```graphql
container {
  from(address: "alpine") {
    build(context:..., dockerfile:...) {}
  }
}
```

It's not obvious to me what should happen in that case. What does the `build() Container!` have in it? Does anything from `alpine` come along for the ride? Or does it get completely blown away?

**Comment by jlongtine** [comment]
> ```graphql
> container {
>   from(address: "alpine") {
>     from(address: "ubuntu") {
>     }
>   }
> }
> ```

In this example, what happens? Are the filesystem and the image config totally blown away?

**Comment by vito** [comment]
Yep, but if you configure any mounts in between the `from` calls they'll stick around.

**Comment by jlongtine** [comment]
> Yep, but if you configure any mounts in between the `from` calls they'll stick around.

Cool. That makes sense. Thanks!

@vikram-dagger @mircubed We should make sure this is clearly documented!

**Comment by jpadams** [comment]
Needs DX and arch review from @shykes and @aluzzardi

**Review by shykes — APPROVED** [review]
API LGTM. It's a tradeoff, but the best one available I think.

Implementation: I defer to others on that one :)

**Review by jlongtine — APPROVED** [review]
LGTM!

**Comment by jpadams** [comment]
@vikram-dagger @kpenfound for docs and examples you're working on:
```
query GrabRepo {
  git(url: "https://github.com/dagger/dagger") {
    branch(name: "v0.2.x") {
      tree {
        id
      }
    }
  }
}
```
...`.id`: ```
"eyJsbGIiOnsiZGVmIjpbIkdxZ0JDaVZuYVhRNkx5OW5hWFJvZFdJdVkyOXRMMlJoWjJkbGNpOWtZV2RuWlhJamRqQXVNaTU0RWljS0ZHZHBkQzVoZFhSb2FHVmhaR1Z5YzJWamNtVjBFZzlIU1ZSZlFWVlVTRjlJUlVGRVJW..."
```

```
query DockerBuildDockerfile {
  container {
    build(
      context: "eyJsbGIiOnsiZGVmIjpbIkdxZ0JDaVZuYVhRNkx5OW5hWFJvZFdJdVkyOXRMMlJoWjJkbGNpOWtZV2RuWlhJamRqQXVNaTU0RWljS0ZHZHBkQzVoZFhSb2FHVmhaR1Z5YzJWamNtVjBFZzlIU1ZSZlFWVlVTRjlJUlVGRVJW..."
      dockerfile: "Dockerfile"
    ) {
      exec(args: ["version"]) {
        stdout {
          contents
        }
      }
    }
  }
}
```

output:
```
{
  "data": {
    "container": {
      "build": {
        "exec": {
          "stdout": {
            "contents": "dagger devel () linux/arm64\n"
          }
        }
      }
    }
  }
}
```

**Pull request merged**
