### PR TITLE
docs: add Elixir to Cookbook Filesystem section

### PR DESCRIPTION
**Pull request by wingyplus**
These changes add Elixir tab and Elixir script file to Cookbook Filesystem
section. All Elixir script files can execute by running `elixir
main.exs` the compiler will install Dagger SDK and execute it
automatically.

### CODE REVIEW

**Comment by wingyplus** [comment]
Here is the demo https://deploy-preview-5672--devel-docs-dagger-io.netlify.app/cookbook#filesystem

**Comment by vikram-dagger** [comment]
Two items for this:
- The Elixir SDK is still marked experimental. We don't have any experimental SDK code in the cookbook yet so this would be the first instance. 
- These recipes are for the filesystem section only (other sections will not have an Elixir SDK code tab). This will create an inconsistent experience.

Should we proceed with this PR? WDYT @mircubed @gerhard @shykes ?

**Comment by TomChv** [comment]
@vikram-dagger I think we should wait until it become an official SDK, we have a lot to do with Zenith so I'm not sure it's the right time for now

**Comment by wingyplus** [comment]
May I ask what is the direction we should go? :)

**Comment by vikram-dagger** [comment]
> May I ask what is the direction we should go? :)

Thanks for your work on this! However afaik, there are no plans to add cookbook recipes for SDKs tagged "experimental".

**Comment by wingyplus** [comment]
Thank you for your information. I’ll close this now. :)

**Pull request closed without merging**
