### PR TITLE
validator: check for undefined fields

### LINKED ISSUE #493: Some cue errors are not caught before running
One big selling point of Cue is that you can catch many errors in your configuration *before* applying it. However, certain errors which *should* be caught before running (or at least feel like they should be caught), are not.

So far I have identified one category of errors which is *not* caught by Cue before execution:
* References to a non-existing definition in an imported package

For example, I expect this snippet to fail before execution, but it does not:

```
import (
   “strings” // Package name does not matter. Builtin or external package doesn’t matter.
)

// #Nope field does not exist in the package
foo: strings.#Nope
```

In summary, references to non-existing fields in another package are *not* considered an error at build time, but will in fact resolve to an error when queried at run time.

## Related
- [ ] https://github.com/dagger/dagger/issues/2331

### PR DESCRIPTION
**Pull request by aluzzardi**
Fixes #493

### CODE REVIEW

**Comment by shykes** [comment]
omg

**Comment by aluzzardi** [comment]
Had a couple of test failures but they were actually legitimate (tests were broken in the first place). Fixed and everything seem to work.

**Comment by aluzzardi** [comment]
Pushed an update:

> Trying something ... for #2334, I think I can achieve the same just by checking BottomKind rather than inspecting the error string of Value.Err()
> Need to do more tests. Entirely new method, just passively checking for v.Kind() == cue.BottomKind and returning v.Error()

/cc @helderco @jlongtine

**Comment by aluzzardi** [comment]
@jlongtine @helderco In the end because of false positives, I'm limiting `BottomKind` errors to "undefined field"

**Comment by aluzzardi** [comment]
This is ready to go!

**Comment by aluzzardi** [comment]
@helderco I'm not going to close #493 yet because I'm not 100% all the problems are fixed

**Review by helderco — APPROVED** [review]
LGTM

**Pull request merged**
