### PR TITLE
feat(lsp): add `dagger lsp` command.

### PR DESCRIPTION
**Pull request by TomChv**
Directly integrate server's start in dagger to simplify the usage since users
will not have to install another binary to use the lsp.

Signed-off-by: Vasek - Tom C <tom.chauveau@epitech.eu>

### CODE REVIEW

**Comment by TomChv** [comment]
@aluzzardi We have a platform issue when I try to build the binary.
It's because `go-tree-sitter` use C GO...

I found a workaround on `Dagger LSP` with goreleaser : https://github.com/dagger/daggerlsp/blob/main/.goreleaser.yaml, 
I think we will have to do the same here to use/release it.
Since we are currently using Dagger to build our project, I think that will not be a piece of cake.

**Comment by samalba** [comment]
I think it's overkill to enable cgo everywhere for this. We may end up with other cross-compiling issues.

From the vscode extension, would it be possible to implement the following in the start function:
- check if `daggerlsp` in the $PATH - if it is, use this
- check if `docker` is in the $PATH - if it is, use `docker run -it --rm <some-prebuilt-daggerlsp-image>:<version>`
- if none of it is available, gently redirect the user the install instructions

Not as good as using the lsp via a sub-command, but good enough to not bother with install instructions.

I'll defer to @aluzzardi to decide whether it's still better option to enable CGO (I checked the go-tree-sitter lib, looks like there is no workaround outside of CGO).

**Comment by grouville** [comment]
> everywhere



> I think it's overkill to enable cgo everywhere for this. We may end up with other cross-compiling issues.
> 
> From the vscode extension, would it be possible to implement the following in the start function:
> 
> * check if `daggerlsp` in the $PATH - if it is, use this
> * check if `docker` is in the $PATH - if it is, use `docker run -it --rm <some-prebuilt-daggerlsp-image>:<version>`
> * if none of it is available, gently redirect the user the install instructions
> 
> Not as good as using the lsp via a sub-command, but good enough to not bother with install instructions.
> 
> I'll defer to @aluzzardi to decide whether it's still better option to enable CGO (I checked the go-tree-sitter lib, looks like there is no workaround outside of CGO).

May be a dumb question, but why not doing as `gopls` ?
- Running a `go install github.com/dagger/daggerlsp@latest` command (https://pkg.go.dev/golang.org/x/tools/gopls#readme-installation), from either dagger / the vscode extension ?

**Comment by samalba** [comment]
@aluzzardi noticed that go-tree-sitter was added recently. Is it actually needed? If it's just for a feature that can be temporarily removed (not sure), we can simply remove the dep and process with this PR without the dep on CGO.

**Comment by grouville** [comment]
> * check

It is being used for the semantic tokenization, whose role here is to be used by the VSCode extension for syntax highlighting purposes

**Comment by grouville** [comment]
@samalba. Done: https://github.com/dagger/vscode-dagger/pull/10. Semantic highlighting is replaced with syntax highlighting in this PR (same way as other extensions do), until we find an alternative

**Review by gerhard — COMMENTED** [review]
Looks good!

Pushed a small change:
image

Should [`SIGINT`](https://en.wikipedia.org/wiki/Signal_(IPC)#SIGINT) (a.k.a. `CTRL C` or `^C`) work? It currently doesn't:
image

Three (3) is the magic number and an acceptable workaround if this is intentional (a.k.a. "feature", a.k.a. "not a bug"):
image

FTR: [Respond to Ctrl+C interrupt signals gracefully.](https://pace.dev/blog/2020/02/17/repond-to-ctrl-c-interrupt-signals-gracefully-with-context-in-golang-by-mat-ryer.html)

**Comment by gerhard** [comment]
I have heard @dolanor that you have the most experience integrating this with `vim`. Do you have 15 mins to spare?

**Comment by TomChv** [comment]
> Three (3) is the magic number and an acceptable workaround if this is intentional (a.k.a. "feature", a.k.a. "not a bug"):

Yeah right now it's 3 ^C to stop the server. We can update this later

**Comment by gerhard** [comment]
I have an important PR coming up shortly against https://github.com/dagger/daggerlsp. Would like to get that in before we merge this. Expect to have it wrapped up in the next few hours.

**Comment by TomChv** [comment]
> I have an important PR coming up shortly against https://github.com/dagger/daggerlsp. Would like to get that in before we merge this. Expect to have it wrapped up in the next few hours.

It depends if you want to include it in the next Dagger LSP release or not.
If you want we can wait tomorrow to merge this PR.

**Comment by gerhard** [comment]
> It depends if you want to include it in the next Dagger LSP release or not. If you want we can wait tomorrow to merge this PR.

That's a good point, it's not dependent on these changes. 🙌🏻

**Review by gerhard — APPROVED** [review]
👍 🚀

**Pull request merged**
