### PR TITLE
docs: Migrates content from dagger/examples repository with history

### PR DESCRIPTION
**Pull request by vikram-dagger**
This commit migrates the code examples from the https://github.com/dagger/examples repository to the current repository, preserving the Git history of the original repository.

- Examples are now in a new `examples/` directory in the repository root.
- SDK examples are now in `examples/sdk/[go|nodejs|python]/*`.
- CLI examples are now in `examples/cli/*`.

This commit updates the README file in the `examples/` directory with new file paths to the available examples.

This commit deletes the LICENSE file from the migrated https://github.com/dagger/examples repository to avoid having two LICENSE files in the current repository. Note that both the current and migrated repositories use the same license terms ie. Apache License 2.0.

The intent is for new examples to be added to the current repository instead of the https://github.com/dagger/examples, which will shortly be deprecated. Also see https://github.com/dagger/examples/pull/36

### CODE REVIEW

**Comment by vikram-dagger** [comment]
@kpenfound @jpadams there are some commits in the original examples repo with missing DCO, which is causing the DCO test to fail. I'm not sure if it's possible to re-sign those or if doing this will rewrite the history of the merged repo. Please let me know how you would like to handle this.

As a separate note, I guess we should NOT "squash and merge" this PR like we normally do, as we want to retain the complete commit history of the merged repo? @gerhard for his thoughts.

**Comment by samalba** [comment]
> @kpenfound @jpadams there are some commits in the original examples repo with missing DCO, which is causing the DCO test to fail. I'm not sure if it's possible to re-sign those or if doing this will rewrite the history of the merged repo. Please let me know how you would like to handle this. Also @samalba for thoughts.
> 
> As a separate note, I guess we should NOT "squash and merge" this PR like we normally do, as we want to retain the complete commit history of the merged repo? @gerhard @samalba for thoughts.

For the DCO, we need to either have them sign/amend the commits (I see @jkodroff and @kpenfound with missing signatures) - or remove the commits from the rebase (the changes can be added later I guess).

No problem to squash the history, looks like it would simplify a few things.

**Comment by vikram-dagger** [comment]
> > @kpenfound @jpadams there are some commits in the original examples repo with missing DCO, which is causing the DCO test to fail. I'm not sure if it's possible to re-sign those or if doing this will rewrite the history of the merged repo. Please let me know how you would like to handle this. Also @samalba for thoughts.
> > As a separate note, I guess we should NOT "squash and merge" this PR like we normally do, as we want to retain the complete commit history of the merged repo? @gerhard @samalba for thoughts.
> 
> For the DCO, we need to either have them sign/amend the commits (I see @jkodroff and @kpenfound with missing signatures) - or remove the commits from the rebase (the changes can be added later I guess).

@jpadams which would you prefer?

> No problem to squash the history, looks like it would simplify a few things.

I agree. However my understanding from @jpadams was that we should retain the history for licensing/legal reasons as it includes at least one external contribution.

**Comment by vikram-dagger** [comment]
@kpenfound to move this forward, could you try signing your commits with missing DCO and if that works, then we can let @jkodroff know and he can do the same?

**Comment by kpenfound** [comment]
@vikram-dagger I think there's somehow an issue with how the git history was pulled over with DCO, because all but one of those failing commits were properly signed in dagger/examples

**Comment by vikram-dagger** [comment]
> @vikram-dagger I think there's somehow an issue with how the git history was pulled over with DCO, because all but one of those failing commits were properly signed in dagger/examples

Hmm, that's odd. This is the process I followed: https://stackoverflow.com/questions/40640733/git-move-repository-to-another-repository-as-a-directory. Could you please have a look and let me know if you can suggest anything to do differently? Also asking @marcosnils @gerhard to add their eyes to it.

**Comment by vikram-dagger** [comment]
> @vikram-dagger I think there's somehow an issue with how the git history was pulled over with DCO, because all but one of those failing commits were properly signed in dagger/examples

@kpenfound it looks like there are two unsigned ones: `3c7641f` and `33de315`. They are unsigned in the dagger/examples repository as well. The other failing commits have a DCO but there seems to be a name mismatch, `Kyle Penfound` vs `kpenfound`. 

Leaving aside the commits with name mismatch, is there a way for you to sign the unsigned ones and we can then check if that is sufficient for the DCO to pass?

**Review by gerhard — APPROVED** [review]
We talked about the failing DCO with @vikram-dagger.

I manually checked all commits, they look good to me.

**Comment by gerhard** [comment]
Disabled **Require linear history** for the purpose of merging this PR via a merge commit so that history is preserved, as @vikram-dagger intended. cc @aluzzardi @samalba

**Pull request merged**
