### PR TITLE
feat: new tty logger

### PR DESCRIPTION
**Pull request by dolanor**
As this logger takes more time to fix, I've split it from the original, used a new logger format name `tty2` so we can start merging it and improve it from here.

### CODE REVIEW

**Comment by gerhard** [comment]
Another tiny iteration on this sometimes this week would be great. [Smooth is fast](https://shipit.show/16).

**Comment by gerhard** [comment]
This is great to see! Will check it out either today or tomorrow the latest. 👀

**Comment by gerhard** [comment]
Bumping this one to my tomorrow in case @aluzzardi or @samalba don't beat me to it their today.

**Review by samalba — APPROVED** [review]
I did a couple of tests with some plans I have. It works fine. I would even make this one the new default logger otherwise the risk is that nobody tries it. Given the current default is buggy, I think we won't have any UX regression.

**Review by gerhard — APPROVED** [review]
> @samalba: I did a couple of tests with some plans I have. It works fine. I would even make this one the new default logger otherwise the risk is that nobody tries it. Given the current default is buggy, I think we won't have any UX regression.

The idea behind `tty2` was to limit the blast radius of something that we don't know how well it works in practice. A new implementation is likely to have "features" (a.k.a. bugs) that we are not aware of until more people try it out. If things look good in 1-2 weeks, we can promote it to the new default. If they don't, we can try to address them and defer that decision until we are more comfortable with the new implementation.

I am tempted to ship this in the next version as is, ask for feedback from everyone on the team as well as users, and promote to the default TTY logger a week later at the soonest if we don't discover any show-stoppers. 

Good to **squash & merge** from me (after the last tiny commit)! Leaving the final call on the above to you @dolanor.

<a href="https://share.descript.com/view/l0Bp4kpA0lM" target="_blank">Screenshot 2022-07-22 at 12 09 32</a>

Is there another command that I should run @dolanor which shows the `tty2` improvement over `tty`? Based on the above, I am not seeing any difference.

---

@dolanor maybe we can learn something from https://github.com/stern/stern

**Comment by dolanor** [comment]
> The idea behind `tty2` was to limit the blast radius of something that we don't know how well it works in practice. A new implementation is likely to have "features" (a.k.a. bugs) that we are not aware of until more people try it out. If things look good in 1-2 weeks, we can promote it to the new default. If they don't, we can try to address them and defer that decision until we are more comfortable with the new implementation.

It's mostly a refactor of the original tty + bug fixes along the way. I tried to keep compatibility to the max between both.
The next part of it will be to break compatibility until we get to an even better result than just few bug fixes. That's why @gerhard and I thought about keeping it separated for now.

> I am tempted to ship this in the next version as is, ask for feedback from everyone on the team as well as users, and promote to the default TTY logger a week later at the soonest if we don't discover any show-stoppers. Leaving the final call on the above to you @dolanor.


> Good to **squash & merge** from me **AFTER** the conflicts are resolved and all checks for green!

Ok, will do that

> Is there another command that I should run @dolanor which shows the `tty2` improvement over `tty`? Based on the above, I am not seeing any difference.

The simplest is to zoom your term to the max and `dagger do -p ci.cue --log-format=tty test` and wait for the panic. (if I remember right, it happens when the log group name is too big. So with a big enough plan with a lot of sub action, it can happen even with wide terminals)
There are few others that I don't remember how to trigger. There must be some test case that highlight them in the `tty.v2_test.go` file (that I should rename BTW)

> @dolanor maybe we can learn something from https://github.com/stern/stern
Have you played with it? I don't really have some k8s env to play with to try it out.
From what I read, it would be more like our `plain` logger that would aggregate logs and color them.
I guess a little bit like what docker-compose did for multiple containers running.
Here, the logic is way more complex than just writing to os.Stdout/Stderr. Which is why it is error prone and full of bugs.

**Comment by gerhard** [comment]
Leaving this with you @dolanor @grouville. Will check again on August 1st.

**Comment by grouville** [comment]
@gerhard, the odds are starting to show that the CI cache breaks when integration + universe are running in parallel

**Comment by grouville** [comment]
@gerhard, just rebased. It works. Let's try it for at least a week 😇

**Pull request merged**
