### PR TITLE
Docs: various improvements

### PR DESCRIPTION
**Pull request by shykes**

### CODE REVIEW

**Review by helderco — COMMENTED** [review]
Did this render? Those drafts are referencing cue files (for the code samples) that weren't moved as well.

**Comment by shykes** [comment]
> Did this render? Those drafts are referencing cue files (for the code samples) that weren't moved as well.

You're right, it broke. That's why the netlify preview failed. I just pushed a fix.

**Comment by helderco** [comment]
The plans dir should move to guides to keep the links, or to tests like the others. The point of tests is to add a bats file later and test those plans.

**Review by gerhard — APPROVED** [review]
💙🚀

**Comment by shykes** [comment]
Thank you @gerhard !

**Pull request merged**
