### PR TITLE
[Docs] Docs UI Feedback Implementation

### PR DESCRIPTION
**Pull request by crjm**
This will make changes in the UI based on internal feedback.

Signed-off-by: crjm <julian@dagger.io>

### CODE REVIEW

**Comment by grouville** [comment]
@crjm can I add myself as a reviewer ?

**Comment by crjm** [comment]
@grouville I'm trying to put Camille as a reviewer, as the feedback was from her, but she cannot be added as a reviewer. I'll remind her of the deploy preview to see what she thinks.

**Comment by crjm** [comment]
@grouville feedback received, you can go ahead and merge if you want :rocket:

**Comment by slumbering** [comment]
> @grouville I'm trying to put Camille as a reviewer, as the feedback was from her, but she cannot be added as a reviewer. I'll remind her of the deploy preview to see what she thinks.

Yes you're right. Because she's now an employee, Camille should be added to this repo ;). cc @gerhard @samalba @aluzzardi

**Review by grouville — APPROVED** [review]
Camille approved

**Pull request merged**
