### PR TITLE
docs: Mention macOS ARM vs Intel Homebrew dagger install path diff

### PR DESCRIPTION
**Pull request by gerhard**
This supersedes https://github.com/dagger/dagger/pull/1998. We appreciate the contribution @sauzy34 and want to get it merged. Thank you!

### CODE REVIEW

**Comment by gerhard** [comment]
Please merge if all checks pass & you are OK with the changes @slumbering @TomChv (#1998 reviewers)

**Comment by gerhard** [comment]
I think that the Netlify failure is due to a https://github.com/dagger/dagger/pull/2173 side-effect: https://app.netlify.com/sites/devel-docs-dagger-io/deploys/62570cbd8d3caa00085e5440#L78-L80

image

I am not sure what is the exact problem, investigating...

**Comment by shykes** [comment]
Doesn't this erase original author information for the commits?

**Comment by gerhard** [comment]
While the intent is the same as https://github.com/dagger/dagger/pull/1998, the change is different, as is the author:

image

Can you think of a better way of addressing the absence of a follow-up while moving this forward? https://github.com/dagger/dagger/pull/1998#issuecomment-1096492588

**Comment by gerhard** [comment]
WDYT @dolanor @grouville @helderco @TomChv?

**Review by helderco — APPROVED** [review]

**Pull request merged**
