### PR TITLE
docs/faq: Add FAQ on tests/secrets_sops.yaml

### PR DESCRIPTION
**Pull request by waveywaves**
Add directions on how to retrieve the sops_age_key file and use
`sops` to add a new secret to tests/secrets_sops.yaml.

### CODE REVIEW

**Review by grouville — CHANGES_REQUESTED** [review]
Could you please lint the README ?

**Review by gerhard — APPROVED** [review]
👍 🚀

**Comment by gerhard** [comment]
When you get a minute, can you please re-review this PR @grouville so that we can get it merged? Thanks!

**Review by grouville — APPROVED** [review]
LGTM

**Pull request merged**
