### PR TITLE
chore(deps): Update sdk/python

### PR DESCRIPTION
**Pull request by helderco**
Should fix https://github.com/dagger/dagger/pull/3774#issuecomment-1332062083

Signed-off-by: Helder Correia

### CODE REVIEW

**Comment by helderco** [comment]
I think that there's an issue with dependabot, I'll be mindful of it in the future.

**Comment by grouville** [comment]
Just triggered the test of the engine provisioning (CI) on my fork: https://github.com/grouville/dagger/actions/runs/3583730956

**Comment by grouville** [comment]
Passes 💥

**Review by grouville — APPROVED** [review]
LGTM. Fixes and passes manual trigger on fork: https://github.com/grouville/dagger/actions/runs/3583730956

**Pull request merged**
