### PR TITLE
docs: Add more installation options for Windows

### PR DESCRIPTION
**Pull request by piraces**
For the page: https://docs.dagger.io/1200/local-dev

Related to #2259

### CODE REVIEW

**Review by TomChv — APPROVED** [review]
Thanks for your contribution, LGTM

**Comment by samalba** [comment]
I am all for supporting Chocolatey and Scoop, they greatly improve the life of Windows users. My only concern is how those packages get updates? I see the Scoop manifest file gets updated by a Github action, it seems that the package will always be up to date to the latest release. Is it the same thing with Chocolatey? How are they maintained? Ideally we want those packages to be fully integrated with the release process to make sure all new versions get published. Once we ensure this is the case, we should merge this PR.

**Comment by piraces** [comment]
@samalba Those packages get updates in an automated way via GitHub Actions (similar to Scoop ones). In this case it is this action: https://github.com/piraces/chocolatey-packages/actions/workflows/main.yml ([repo](https://github.com/piraces/chocolatey-packages)).

The action runs every day at 11AM UTC (scheduled) to check for updates and submit them to Chocolatey and make a commit with the updated info in the same repo (but I'm planning to run it more frequently).

In this case I can't think about how we can achieve fully integrated release process including Chocolatey... This process is usually managed by the community in a separate repository, but maybe we can plan and investigate to create an automation in this repo.

In the case for [Azure/bicep](https://github.com/Azure/bicep), the package is managed in the same way vía my repository. I always check the workflow runs ok and latest versions are available (sometimes it gets time until they moderate the new version), and if the workflow fails (only happened once to me) I push the packages manually.

**Comment by samalba** [comment]
I think it's totally fine to run the update once a day at this point. And I fully agree using chocolatey or scoop is much nicer than the the usual PS script.

**Review by samalba — APPROVED** [review]

**Pull request merged**
