### PR TITLE
fix plan validation for generated fields

### PR DESCRIPTION
**Pull request by aluzzardi**

### CODE REVIEW

**Comment by aluzzardi** [comment]
This should go after #2321 so we can mark the backward incompatible change.

**Review by helderco — APPROVED** [review]
LGTM!

**Review by jlongtine — APPROVED** [review]
:shipit: 

Interesting that the `@dagger` attributed was being attached to the latter part of the disjunction, rather than the field. I wasn't expecting that.

**Comment by aluzzardi** [comment]
@jlongtine @helderco 

**UPDATE**: I changed the version requirement in `pkg/pkg.go` to **0.2.9** so that users are forced to upgrade once they get the new binary

**Comment by helderco** [comment]
What happens if I build from main and use dagger in a config outside this repo? Will it complain that I need 0.2.9?

**Comment by aluzzardi** [comment]
@helderco Version checking is disabled for development (non release) dagger binaries

**Pull request merged**
