### PR TITLE
apostrophe around the dir flag argument

### PR DESCRIPTION
**Pull request by lind**
Add ' for --dir command to work using branch and subdir

At least using iterm on mac I had to add '' arround the dir flag argument.

### CODE REVIEW

**Review by gerhard — APPROVED** [review]
👍 🚀

**Comment by jedevc** [comment]
:thinking: wait, why are quotes required here? I don't think that `#` should have a specific meaning on mac vs on linux, are you using a different shell?

What error were you getting?

**Comment by lind** [comment]
Your right @jedevc I was using zsh and got this: `zsh: no matches found: --dir=https://github.com/dagger/dagger#main:cmd/dagger`

But with bash it works. Maybe revert this then?

**Comment by jedevc** [comment]
What's weird is that I also use zsh - what do you get if you run the following:

```
$ echo foo#bar
foo#bar
```

I get the expected result on both zsh and bash :confused:

**Comment by lind** [comment]
I got `zsh: no matches found: foo#bar`. Probably something with my zsh config then.

**Pull request merged**
