### PR TITLE
feat: shell autocomplete

### PR DESCRIPTION
**Pull request by jedevc**
This PR introduces support for shell autocompletion. We allow auto-completing module commands, chained commands, builtins, arg flags, etc.

<a href="https://asciinema.org/a/WYvfoe6VCH66c8Nlb3YHzuuZ6" target="_blank"></a>

There's still some important functionality missing, but this is a good first pass. Some things we should maybe come back and do:
- We should allow autocompletion of args, such as `File`s and `Directory`s to paths on the host, and autocompletion of enums to their list of allowed values
- We should allow partial parse tree - so that we can handle cases like `.container | \t` to auto-complete functions on the container type. Currently, we need to have at least one character inserted.

---

TODO:
- [x] Determine "code completion context" at cursor
- [x] Autocomplete flags from context
- [ ] Autocomplete args of certain types from context (e.g. `dagger.File`/`dagger.Directory`)
  - This probably requires some way of parsing flags during auto-completion :cry: 
- [x] Autocomplete command names from context
- [x] Autocomplete builtins
- [ ] Support partial parse trees
  - Sort of working, but relies on a temporary fork: https://github.com/mvdan/sh/compare/master...jedevc:mvdan-sh:allow-partial-parse-tree
  - Moving this to a follow-up! https://github.com/jedevc/dagger/compare/jedevc:dagger:shell-autocomplete...shell-autocomplete-partial-parse-tree
- [x] Add tests!
  - Very important, this logic is very fragile!
- [x] Cleanup

### CODE REVIEW

**Comment by shykes** [comment]
I cause a crash :(

## What I did

1. Opened interactive terminal from this version:

```
dagger call -m github.com/jedevc/dagger@shell-autocomplete dev terminal --cmd=dagger,shell
```

2. Start typing an incomplete command

```
.container | f
```

3. Press tab

## What I expected

My command auto-completes to `.container | from`

## What happened

CLI crashed:

```
⋈ .container | fpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc33100]

goroutine 162 [running]:
main.(*CompletionContext).lookupField(0x0, {0x40008b0010, 0xa}, {0x4000c12030, 0x0, 0x0})
        /app/cmd/dagger/shell_completion.go:201 +0x30
main.(*shellAutoComplete).dispatchCall(0x4000735a98?, 0x0, 0x40008c4000, 0xd)
        /app/cmd/dagger/shell_completion.go:118 +0x18c
main.(*shellAutoComplete).dispatch(0x0?, 0x0?, 0x4000735ad8?, 0xc3207c?)
        /app/cmd/dagger/shell_completion.go:101 +0x50
main.(*shellAutoComplete).dispatchPipe(0x400013c408, 0xe351e0?, 0x4000bb8060, 0xd)
        /app/cmd/dagger/shell_completion.go:126 +0x3c
main.(*shellAutoComplete).dispatch(0x400013c408?, 0x4000854000?, 0x4000aa1020?, 0x0?)
        /app/cmd/dagger/shell_completion.go:103 +0x80
main.(*shellAutoComplete).Do(0x400013c408, {0x4000542000?, 0x40005f8c18?, 0xb6e73c?}, 0xe)
        /app/cmd/dagger/shell_completion.go:80 +0x208
github.com/chzyer/readline.(*opCompleter).OnComplete(0x40002ee000)
        /go/pkg/mod/github.com/chzyer/readline@v1.5.1/complete.go:87 +0x12c
github.com/chzyer/readline.(*Operation).ioloop(0x400025fea0)
        /go/pkg/mod/github.com/chzyer/readline@v1.5.1/operation.go:180 +0xa0c
created by github.com/chzyer/readline.NewOperation in goroutine 1
        /go/pkg/mod/github.com/chzyer/readline@v1.5.1/operation.go:88 +0x2c4
exit 2
```

**Comment by jedevc** [comment]
Woops. Looks like completion wasn't working when there was no module loaded - fixed.

**Comment by helderco** [comment]
This is pretty nice, thanks @jedevc!

I rebased yesterday, just want to finish updating a few completions based on the latest changes to module loading and execution.

**Comment by helderco** [comment]
Just running tests before pushing.

**Review by helderco — APPROVED** [review]
Nice work!

**Pull request merged**
