### PR TITLE
docs: cookbook: mount directories as secrets after v.0.8.0

### PR DESCRIPTION
**Pull request by grouville**
Closes https://github.com/dagger/dagger/issues/4896

Re-opening following the [revert](https://github.com/dagger/dagger/pull/5519). Most of the context is on the [initial PR](https://github.com/dagger/dagger/pull/5502)

Small cookbook example / wrapper with the `.with()` method showing how to mount directories securely.

cc @helderco

### CODE REVIEW

**Review by helderco — COMMENTED** [review]
I think we can simplify this a lot.

My `~/.gnupg` directory is less than 1MiB. To keep the cookbook simple for mounting a secret directory I'd just mount the whole `~/.gnupg` directory. You just resolve all the paths from the host first in a map of names to full paths, and  then loop over these for a simpler `with` util.

Then it'll be easy enough for the user to add include/exclude globs or provide an explicit map of file names instead to limit which files are added.

EDIT: My suggestion here:
- https://github.com/grouville/dagger/pull/216

**Comment by gerhard** [comment]
@grouville @helderco what needs to happen to get this ready for review? I am keen to get this merged today.

cc @vikram-dagger

**Comment by grouville** [comment]
> @grouville @helderco what needs to happen to get this ready for review? I am keen to get this merged today.
> 
> cc @vikram-dagger

I'll update the docs accordingly in a few hours 🙏

**Comment by gerhard** [comment]
Thank you @grouville! I am super keen on getting this one merged within the next 2h. We are really close to having everything in place for tomorrow's release.

**Comment by grouville** [comment]
@gerhard: As seen with @helderco, this will have to be merged after the `v.0.8.0` release: https://github.com/dagger/dagger/pull/5519#pullrequestreview-1552165562.

> This PR was re-opened prior the revert: https://github.com/dagger/dagger/pull/5519.

It goes in-pair with https://github.com/dagger/dagger/pull/5518 and https://github.com/dagger/dagger/pull/5515, which will be merged right after the release.

However, I'm currently updating it to make it reviewable and ready to be shipped tomorrow

**Comment by helderco** [comment]
The go and node.js snippets haven't been updated. I suggested improvements using Python, but it needs to be replicated to the others.

**Comment by gerhard** [comment]
Since we are a few hours from release, can we get this one ready to merge & then go for merge?

**Comment by helderco** [comment]
I'm finishing another cookbook issue and I'll help here if needed.

**Comment by grouville** [comment]
> I'm finishing another cookbook issue and I'll help here if needed.

@helderco, your help on the `Node SDK Client` issue unblocked me. It shall be ready for a review.

**Pull request merged**
