### PR TITLE
fix hostname calculation when using services

### LINKED ISSUE #5450: 🐞 Some operations stopped caching since 0.6.3
### What is the issue?

Since v0.6.3, some operations stopped caching. See the steps below on how to reproduce.

I did not have time to dig into which of these changes introduced this change in behaviour, but I'm fairly certain that it's one of these: https://github.com/dagger/dagger/releases/tag/v0.6.3

For now, I am sharing for visibility (discovered it earlier today). When I get a moment, if someone else doesn't pick it up by then, my intention is to continue digging into this.

cc @vito @sipsma @helderco

### Log output

_No response_

### Steps to reproduce

```console
git clone https://github.com/thechangelog/changelog.com some-operations-stopped-caching
cd some-operations-stopped-caching/magefiles

# upgrade to Go SDK which uses Engine v0.6.2:
go get -u dagger.io/dagger@v0.7.2

# run the pipeline:
go run main.go -w ../ ci
# this will take less than 4m on the first run
# it will take consistently 15s on all subsequent runs, when nothing changes

# upgrade to latest Go SDK which uses Engine v0.6.3:
go get -u dagger.io/dagger@v0.7.3

# run the pipeline again:
go run main.go -w ../ ci
# this will take less than 4m on the first run
# it will take consistently 50s on all subsequent runs, when nothing changes
# the expectation is that all ops should be cached, but not all are
```

### SDK version

Go SDK v0.7.2

### OS version

macOS 12.6 connecting to remote Docker 24.0.2 via TCP (runs on NixOS 22.11)

### PR DESCRIPTION
**Pull request by marcosnils**
fixes #5450

Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>

### CODE REVIEW

**Comment by marcosnils** [comment]
I'll wait for @vito's comments before addressing tests failures.

**Comment by vito** [comment]
@sipsma Unfortunately I don't think that's an easy change, because the `llb.Hostname` has to be added alongside all the other `llb.RunOptions` that go into creating the `Container.FS` that is evaluated by `Container.Start`. It's the same reason I had to jump through hoops in #5322.

I'm not sure if anyone is even making use of this aspect of the API, and there's an easy workaround (just call `WithExposedPort` with a bogus value), and the long-term fix is #5322, so I think this is probably OK to just merge for now.

However it also seems worth considering rolling back the `core/host.go` changes in #5346; it seems like that could have smaller fallout since it's for a heavily experimental feature anyway (`dagger do`).

**Comment by sipsma** [comment]
> Unfortunately I don't think that's an easy change, because the llb.Hostname has to be added alongside all the other llb.RunOptions that go into creating the Container.FS that is evaluated by Container.Start. It's the same reason I had to jump through hoops in https://github.com/dagger/dagger/pull/5322.

@vito Ah right, I remember that whole saga of hoop jumping now, thanks, makes sense.

> However it also seems worth considering rolling back the core/host.go changes in https://github.com/dagger/dagger/pull/5346; it seems like that could have smaller fallout since it's for a heavily experimental feature anyway (dagger do).

Yeah I agree that's an option worth considering too, kind of a hard call. But one thing I'm just realized is that the hostname setting *might* actually break other stuff besides this particular issue involving local LLB.

For example, if you had `c.Container().From("image:tag1")` and `c.Container().From("image:tag2")`, but it turns out that `tag1` and `tag2` actually point to the same digest, then even though the LLB digests differ, buildkit will internally resolve them and cache based on the resolved sha rather than tag. But if we always set hostname on an exec from the LLB digests, then that caching wouldn't be possible anymore (right? double check my thinking here).

So if that's correct then that's probably an argument for this patch.

One other small benefit of not setting hostnames every time is that it allows buildkit to re-use network namespaces for the execs. No clue if that's really much of a benefit outside extremely high load scenarios though, just worth mentioning.

**Comment by vito** [comment]
Yeah that's all accurate. Those are also more scenarios where it'd be great if we could get the actual cache key out of Buildkit somehow.

Either way we won't be setting hostnames all the time in the long run since #5322 changes it so that only the service gateway execs set a hostname, so I'm fully onboard with that already. Only trying to identify which "quick fix" would result in fewest complaining users. :P In all likelihood both will be 0, so let's :shipit:

**Comment by sipsma** [comment]
> Those are also more scenarios where it'd be great if we could get the actual cache key out of Buildkit somehow.

Agreed, or with the thing you figured out yesterday at least we could the individual resolved op digests and construct our own "DAG digest" out of them even if Buildkit won't give you that. It still wouldn't be perfect since it wouldn't account for buildkit's ability to selectively run cache based hashes for some ops, but it would be much closer

**Comment by marcosnils** [comment]
closing in favor of https://github.com/dagger/dagger/pull/5468. Thx @vito

**Pull request closed without merging**
