### PR TITLE
universe: Add kubernetes package

### PR DESCRIPTION
**Pull request by TomChv**
### Changes

Related to #1951

- Add `#Kubectl`
- Add `#Apply`
- Add tests for both

#### URL

```shell
dagger do -p ./apply.cue test apply url           
[✔] [✔] actions.test.apply.url                                                                                                                                        
[✔] actions.test.apply.url                                                                                                                                        0.7s
[✔] client.filesystem."./kubeconfig".read                                                                                                                         0.0s

kubectl get pods                       
NAME          READY   STATUS             RESTARTS     AGE
hello-world   0/1     CrashLoopBackOff   1 (8s ago)   9s

```

#### Directory

See issue below

### Issue

I'm currently hitting an issue with `directory` test, I do not understand why, it's related to client API, may @helderco can help me

```shell
dagger do -p ./apply.cue test apply directory
[✔] actions.test.apply.directory                                                                                                                                  1.2s
[✔] client.filesystem."./kubeconfig".read                                                                                                                         0.0s
2:00AM FTL failed to execute plan: task failed: actions.test.apply.directory._exec: invalid FS at path "actions.test.apply.directory._exec.mounts.manifest.contents": FS is not set

ls
ls -R ./data 
hello-pod

./data/hello-pod:
hello.yaml
```

As you see, file exist but it doesn't works :/

[See the plan here](https://github.com/dagger/dagger/blob/7f46ae46789b1560bdea73ce652b741bbba4b8b2/pkg/universe.dagger.io/x/tom.chauveau.pro%40icloud.com/kubernetes/test/apply.cue#L13)

Signed-off-by: Vasek - Tom C <tom.chauveau@epitech.eu>

### CODE REVIEW

**Review by gerhard — CHANGES_REQUESTED** [review]
This does not resolve https://github.com/dagger/dagger/issues/1951 because it's not an official package. It's a step in that direction, but I think that we should merge this with https://github.com/dagger/dagger/pull/2055 into a single official kubernetes package. Both great steps in the same direction.

The one thing that could be improved is not committing the `kubeconfig` file. This file only works for your current KiND setup and will fail as soon as you re-install. The tests also wouldn't work anywhere else. I think that @rawkode has a better approach here: https://github.com/dagger/dagger/pull/2055/files#diff-85930119ab3ecf91b3a6adf9dc5648f894dbfd74b5293aca6d1be74314f8eda0R11-R14

If we don't merge `test/apply.cue` & `test/kubectl.cue` files, we get an error:

```console
✦ ❯ dagger do test
[✗] actions.test.apply.directory                                                                                                                                                                                                           1.3s
[✔] actions.test.kubectl.custom                                                                                                                                                                                                            0.7s
[✔] actions.test.kubectl.simple                                                                                                                                                                                                            0.7s
[✗] actions.test.apply.url                                                                                                                                                                                                                 2.0s
[✔] actions.test.kubectl.custom.verify                                                                                                                                                                                                     0.0s
[✔] actions.test.kubectl.simple.verify                                                                                                                                                                                                     0.0s
[+] actions.test.kubectl.custom.verify.export                                                                                                                                                                                              0.0s
9:12PM FTL failed to execute plan: task failed: actions.test.apply.directory._exec: invalid secret at path "actions.test.apply.directory._exec.mounts.kubeconfig.contents": secret is not set
```

This is related to how multiple `dagger.#Plan` get merged.

This diff works:

```diff
diff --git a/pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/test/apply.cue b/pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/test/apply.cue
deleted file mode 100644
index 49b830ab..00000000
--- a/pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/test/apply.cue
+++ /dev/null
@@ -1,32 +0,0 @@
-package kubernetes
-
-import (
-       "dagger.io/dagger"
-
-       "universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes"
-)
-
-dagger.#Plan & {
-       // Kubeconfig must be in current directory
-       client: filesystem: {
-               "./kubeconfig": read: contents: dagger.#Secret
-               "./data": read: contents:       dagger.#FS
-       }
-
-       actions: test: apply: {
-               // Alias on kubeconfig
-               _kubeconfig: client.filesystem."./kubeconfig".read.contents
-
-               url: kubernetes.#Apply & {
-                       kubeconfig: _kubeconfig
-                       location:   "url"
-                       url:        "https://gist.githubusercontent.com/grouville/04402633618f3289a633f652e9e4412c/raw/293fa6197b78ba3fad7200fa74b52c62ec8e6703/hello-world-pod.yaml"
-               }
-
-               directory: kubernetes.#Apply & {
-                       kubeconfig: _kubeconfig
-                       location:   "directory"
-                       source:     client.filesystem."./data".read.contents
-               }
-       }
-}
diff --git a/pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/test/kubectl.cue b/pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/test/kubectl.cue
deleted file mode 100644
index 7b2a3a7f..00000000
--- a/pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/test/kubectl.cue
+++ /dev/null
@@ -1,48 +0,0 @@
-package kubernetes
-
-import (
-       "dagger.io/dagger"
-
-       "universe.dagger.io/docker"
-       "universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes"
-)
-
-dagger.#Plan & {
-       actions: test: kubectl: {
-               simple: {
-                       _image: kubernetes.#Kubectl
-                       verify: docker.#Run & {
-                               input: _image.output
-                               user:  "root"
-                               command: {
-                                       name: "-c"
-                                       args: ["""
-                                                       kubectl version >> /version.txt || true
-                                               """]
-                               }
-                               entrypoint: ["/bin/sh"]
-                               export: files: "/version.txt": _ & =~"v1.23.5"
-                       }
-               }
-
-               custom: {
-                       _image: kubernetes.#Kubectl & {
-                               version: "1.21.12"
-                       }
-
-                       verify: docker.#Run & {
-                               input: _image.output
-                               user:  "root"
-                               command: {
-                                       name: "-c"
-                                       args: ["""
-                                                       kubectl version >> /version.txt || true
-                                               """]
-                               }
-                               entrypoint: ["/bin/sh"]
-                               export: files: "/version.txt": _ & =~"v1.21.12"
-                       }
-               }
-       }
-}
diff --git a/pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/test/test.cue b/pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/test/test.cue
new file mode 100644
index 00000000..d59bfcf9
--- /dev/null
+++ b/pkg/universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes/test/test.cue
@@ -0,0 +1,73 @@
+package kubernetes
+
+import (
+       "dagger.io/dagger"
+
+       "universe.dagger.io/docker"
+       "universe.dagger.io/x/tom.chauveau.pro@icloud.com/kubernetes"
+)
+
+dagger.#Plan & {
+       // Kubeconfig must be in current directory
+       client: filesystem: {
+               "./kubeconfig": read: contents: dagger.#Secret
+               "./data": read: contents:       dagger.#FS
+       }
+
+       actions: test: {
+               kubectl: {
+
+       actions: test: {
+               kubectl: {
+                       simple: {
+                               _image: kubernetes.#Kubectl
+
+                               verify: docker.#Run & {
+                                       input: _image.output
+                                       user:  "root"
+                                       command: {
+                                               name: "-c"
+                                               args: ["""
+                                                       kubectl version >> /version.txt || true
+                                               """]
+                                       }
+                                       entrypoint: ["/bin/sh"]
+                                       export: files: "/version.txt": _ & =~"v1.23.5"
+                               }
+                       }
+
+                       custom: {
+                               _image: kubernetes.#Kubectl & {
+                                       version: "1.21.12"
+                               }
+
+                               verify: docker.#Run & {
+                                       input: _image.output
+                                       user:  "root"
+                                       command: {
+                                               name: "-c"
+                                               args: ["""
+                                                       kubectl version >> /version.txt || true
+                                               """]
+                                       }
+                                       entrypoint: ["/bin/sh"]
+                                       export: files: "/version.txt": _ & =~"v1.21.12"
+                               }
+                       }
+               }
+               apply: {
+                       // Alias on kubeconfig
+                       _kubeconfig: client.filesystem."./kubeconfig".read.contents
+
+                       url: kubernetes.#Apply & {
+                               kubeconfig: _kubeconfig
+                               location:   "url"
+                               url:        "https://gist.githubusercontent.com/grouville/04402633618f3289a633f652e9e4412c/raw/293fa6197b78ba3fad7200fa74b52c62ec8e6703/hello-world-pod.yaml"
+                       }
+
+                       directory: kubernetes.#Apply & {
+                               kubeconfig: _kubeconfig
+                               location:   "directory"
+                               source:     client.filesystem."./data".read.contents
+                       }
+
+               }
+       }
+}
```

**Comment by TomChv** [comment]
> The one thing that could be improved is not committing the kubeconfig file. This file only works for your current KiND setup and will fail as soon as you re-install.

It was a mistake, you are right!

> I think that @rawkode has a better approach here

I totally agree with you! I'll fix that one

> This is related to how multiple dagger.#Plan get merged.

I know that issue but I think could just also run both `dagger do test kubectl` and `dagger do test apply` in `bats` so it will be easier to maintain when we will add more definition.

I didn't write `test.bats` because we do not deploy a cluster in our current CI so it will always fail

**Comment by gerhard** [comment]
👀

**Comment by gerhard** [comment]
This is still failing for me:

```console
tom.chauveau.pro@icloud.com/kubernetes/test on  universe/kubernetes [$]
❯ dagger do test
failed to load plan: package "universe.dagger.io" is incompatible with this version of dagger (requires 0.2.9 or newer). Run `dagger project update` to resolve this

tom.chauveau.pro@icloud.com/kubernetes/test on  universe/kubernetes [$]
❯ dagger project update
2:49PM WRN system | skip vendoring: module is symlinked    module=dagger.io
Project updated

tom.chauveau.pro@icloud.com/kubernetes/test on  universe/kubernetes [$✘?]
❯ dagger do test
failed to load plan: "client.filesystem.\"./data\".read" is not set
"client.platform.arch" is not set
"client.platform.os" is not set
"actions.test.apply.directory._exec.output" is not set: :
    ../../../../cue.mod/pkg/dagger.io/dagger/core/exec.cue:38:2
    ../../../../docker/run.cue:163:2
"actions.test.kubectl.custom.verify.export._files.\"/version.txt\"._read.contents" is not set: :
    ../../../../cue.mod/pkg/dagger.io/dagger/core/fs.cue:49:2
    ../../../../docker/run.cue:127:7
"actions.test.apply.directory._baseImage._op.output" is not set: :
    ../../../../cue.mod/pkg/dagger.io/dagger/core/image.cue:80:2
    ../../../../docker/pull.cue:20:2
"actions.test.apply.directory._baseImage._op.digest" is not set: :
    ../../../../cue.mod/pkg/dagger.io/dagger/core/image.cue:83:2
    ../../../../docker/pull.cue:20:2
"actions.test.apply.directory.workdir" is not set: :
    ../../../../docker/run.cue:65:2
    ./apply.cue:30:3
"_#Location" is not set:
    ../apply.cue:8:1
```

Instead of continuing with the comments, I will push the fix(es) so that we can get it merged.

**Comment by gerhard** [comment]
There are two more issues with this as it currently stands:

1. While `dagger do test` works with `dagger devel (4181b77f) darwin/arm64`, we don't know if it works with the current Dagger version (> 0.2.9). Going to rebase on top of `main` and double-check that this still works with the latest changes. Unfortunately, this is one of the side-effects of a really long PR review cycle. I take responsibility for the slow feedback.

2. The pod that gets deployed part of the test keeps exiting. There is no cleanup either. While this is no big deal (definitely not a blocker), it's worth mentioning it:

image

**Comment by TomChv** [comment]
> This is still failing for me:

You forget to read my comment : https://github.com/dagger/dagger/pull/2252#issuecomment-1105820433

Your solution works for little package but kubernetes will growth and `test.cue` will become really big, that why I wanted to split test into multiple files even if we cannot do `dagger do test`.

> The pod that gets deployed part of the test keeps exiting

It normal, the pod is just doing a `hello world`, no process is running

> There is no cleanup either

It will come with `kubernetes.#Delete` in a future PR

**Comment by gerhard** [comment]
> You forget to read my comment : [#2252 (comment)](https://github.com/dagger/dagger/pull/2252#issuecomment-1105820433)
> 
> Your solution works for little package but kubernetes will growth and `test.cue` will become really big, that why I wanted to split test into multiple files even if we cannot do `dagger do test`.

OK! Please remove my commit and rebase on top of main so that we know we have the latest version before this gets merged.

**Comment by TomChv** [comment]
PR is successfully rebased are your change has been revert (sorry for that btw)

**Comment by gerhard** [comment]
Not a problem, I am keen on getting this one through by the end of this week.

**Comment by gerhard** [comment]
Unfortunately, the same integration test is still failing: https://github.com/dagger/dagger/runs/6325026413?check_suite_focus=true

Do you want to dig into that? @sipsma might be able to help.

**Comment by TomChv** [comment]
I'll but it's really not related to my current PR :/ That's strange

**Comment by sipsma** [comment]
@TomChv It just passed on a re-run, but it did take a few tries. It's very odd because I have not seen that error before even though I have been running tests in CI literally >100 times the last few days, so if that test was flaky I would have expected it to pop up. It is a timing-based test (async exec kind of has to be unfortunately) so it's possible we were just getting slow runners (noisy neighbor? not sure what what GHA's backend looks like). Still, it's weird it showed so much in this unrelated PR in particular.

Either way, it passing should unblock you for now. I will send out a PR to add some extra logging to the test case so if it flakes again we can have a better idea why. Also, the stuff I've been doing with collecting jaeger traces from CI test runs will help with this too.

**Comment by TomChv** [comment]
> Either way, it passing should unblock you for now. I will send out a PR to add some extra logging to the test case so if it flakes again we can have a better idea why. Also, the stuff I've been doing with collecting jaeger traces from CI test runs will help with this too.

You are awesome! Thank you :rocket:

**Review by gerhard — APPROVED** [review]
👍

**Pull request merged**
