### PR TITLE
fix(cli): fix secret plaintext being printed on screen

### PR DESCRIPTION
**Pull request by helderco**
Fixes https://github.com/dagger/dagger/issues/8464

### CODE REVIEW

**Review by sipsma — APPROVED** [review]
LGTM, agree test is worth adding though too

**Comment by jedevc** [comment]
Approach SGTM, but I think there's still an underlying issue - if the user explicitly calls `plaintext` on the secret, the secret still ends up in the otel trace.

I think we might also want to have the OTEL trace logs scanned and filtered.

**Comment by helderco** [comment]
> Approach SGTM, but I think there's still an underlying issue - if the user explicitly calls `plaintext` on the secret, the secret still ends up in the otel trace.
> 
> I think we might also want to have the OTEL trace logs scanned and filtered.

True, but that's a separate PR.

**Review by jedevc — APPROVED** [review]

**Comment by helderco** [comment]
Added tests.

**Pull request merged**
