### PR TITLE
style: improve NodeJS SDK codebase

### PR DESCRIPTION
**Pull request by TomChv**
Enforce prettier rules and install sort import plugins. Cleanup codebase.
Update Eslint's' no-unused-vars' rule to allow '_'.
Fix code duplication between image.ts and bin.ts.

Signed-off-by: Tom Chauveau <tom.chauveau@epitech.eu>

### CODE REVIEW

**Comment by slumbering** [comment]
Hey @TomChv 👋 
Thanks for the PR. You have some conflicts

**Comment by gerhard** [comment]
@TomChv want to check this again?

We should aim to get this reviewed & merged same day if possible @slumbering @dolanor. With all the changes happening in the Node.js SDK right now, if this does not move through quickly, we are likely to end up in the same merge conflict situation.

**Comment by TomChv** [comment]
> We should aim to get this reviewed & merged same day if possible @slumbering @dolanor. With all the changes happening in the Node.js SDK right now, if this does not move through quickly, we are likely to end up in the same merge conflict situation.

I'm taking care of the rebase today! We shall be able to merge it after that :)

**Comment by slumbering** [comment]
@TomChv Should we close this PR ? Most of the files you've refactored are deleted now. We can definitely use the .prettierrc though. Super useful.

**Comment by TomChv** [comment]
Yeah! I'll just split those changes into multiple PR easier to merge

**Comment by slumbering** [comment]
@TomChv Let me know when this PR can be close. Thanks

**Comment by TomChv** [comment]
PR closed, I have already transfer changes to new PRs

**Pull request closed without merging**
