### PR TITLE
Add Exclude Sub-Directory tests

### PR DESCRIPTION
**Pull request by benjaminstrasser**

### CODE REVIEW

**Comment by vito** [comment]
Thanks for whittling this down to the exact scenario where it fails! This seems to be an issue in Buildkit related specifically to in-memory files, which explains why it works properly for host directories. I'll see if I can track down the bug and submit a PR upstream.

**Comment by vito** [comment]
I can confirm this bug is present in Buildkit v0.10.5 but appears to be fixed on `master`. We should be able to get the fix once Buildkit v0.11.0 has finalized (there's an [RC](https://github.com/moby/buildkit/releases/tag/v0.11.0-rc1) out so far).

Here's the test I used to confirm:

```patch
diff --git a/client/client_test.go b/client/client_test.go
index e3edce37..2e5b762a 100644
--- a/client/client_test.go
+++ b/client/client_test.go
@@ -187,6 +187,7 @@ func TestIntegration(t *testing.T) {
 		testMultipleCacheExports,
 		testMountStubsDirectory,
 		testMountStubsTimestamp,
+		testFileOpCopyExcludeDir,
 	)
 }
 
@@ -1630,6 +1631,64 @@ func testFileOpInputSwap(t *testing.T, sb integration.Sandbox) {
 	require.Contains(t, err.Error(), "bar: no such file")
 }
 
+func testFileOpCopyExcludeDir(t *testing.T, sb integration.Sandbox) {
+	requiresLinux(t)
+	c, err := New(sb.Context(), sb.Address())
+	require.NoError(t, err)
+	defer c.Close()
+
+	base := llb.Scratch().
+		File(llb.Mkfile("a.txt", 0644, []byte("a"))).
+		File(llb.Mkfile("b.txt", 0644, []byte("a"))).
+		File(llb.Mkdir("subdir", 0755, llb.WithParents(true))).
+		File(llb.Mkfile("subdir/c.txt", 0644, []byte("c"))).
+		File(llb.Mkfile("subdir/d.txt", 0644, []byte("d")))
+
+	st := llb.Scratch().File(llb.Copy(
+		base,
+		".",
+		".",
+		&llb.CopyInfo{
+			CreateDestPath:      true,
+			CopyDirContentsOnly: true,
+			ExcludePatterns:     []string{"subdir"},
+		},
+	))
+
+	def, err := st.Marshal(sb.Context())
+	require.NoError(t, err)
+
+	var entries []string
+	_, err = c.Build(sb.Context(), SolveOpt{}, "", func(ctx context.Context, c gateway.Client) (*gateway.Result, error) {
+		res, err := c.Solve(ctx, gateway.SolveRequest{
+			Definition: def.ToPB(),
+		})
+		if err != nil {
+			return nil, err
+		}
+
+		ref, err := res.SingleRef()
+		if err != nil {
+			return nil, err
+		}
+
+		ents, err := ref.ReadDir(ctx, gateway.ReadDirRequest{
+			Path: ".",
+		})
+		if err != nil {
+			return nil, err
+		}
+
+		for _, ent := range ents {
+			entries = append(entries, ent.GetPath())
+		}
+
+		return nil, nil
+	}, nil)
+	require.NoError(t, err)
+	require.Equal(t, []string{"a.txt", "b.txt"}, entries)
+}
+
 func testLocalSourceDiffer(t *testing.T, sb integration.Sandbox) {
 	for _, d := range []llb.DiffType{llb.DiffNone, llb.DiffMetadata} {
 		t.Run(fmt.Sprintf("differ=%s", d), func(t *testing.T) {
```

`master`:

```
+ docker start -a c40831162525428f0e9cd41cee8d862ce17cbc82f156d4f0b2554b5e39418e07
=== RUN   TestIntegration
=== RUN   TestIntegration/TestFileOpCopyExcludeDir/worker=oci
=== PAUSE TestIntegration/TestFileOpCopyExcludeDir/worker=oci
=== RUN   TestIntegration/TestFileOpCopyExcludeDir/worker=oci-rootless
=== PAUSE TestIntegration/TestFileOpCopyExcludeDir/worker=oci-rootless
=== RUN   TestIntegration/TestFileOpCopyExcludeDir/worker=oci-snapshotter-stargz
=== PAUSE TestIntegration/TestFileOpCopyExcludeDir/worker=oci-snapshotter-stargz
=== RUN   TestIntegration/TestFileOpCopyExcludeDir/worker=containerd
=== PAUSE TestIntegration/TestFileOpCopyExcludeDir/worker=containerd
=== RUN   TestIntegration/TestFileOpCopyExcludeDir/worker=containerd-1.5
=== PAUSE TestIntegration/TestFileOpCopyExcludeDir/worker=containerd-1.5
=== RUN   TestIntegration/TestFileOpCopyExcludeDir/worker=containerd-rootless
=== PAUSE TestIntegration/TestFileOpCopyExcludeDir/worker=containerd-rootless
=== RUN   TestIntegration/TestFileOpCopyExcludeDir/worker=containerd-snapshotter-stargz
=== PAUSE TestIntegration/TestFileOpCopyExcludeDir/worker=containerd-snapshotter-stargz
=== CONT  TestIntegration/TestFileOpCopyExcludeDir/worker=oci
=== CONT  TestIntegration/TestFileOpCopyExcludeDir/worker=containerd-1.5
=== CONT  TestIntegration/TestFileOpCopyExcludeDir/worker=containerd-snapshotter-stargz
=== CONT  TestIntegration/TestFileOpCopyExcludeDir/worker=containerd-rootless
=== CONT  TestIntegration/TestFileOpCopyExcludeDir/worker=containerd
=== CONT  TestIntegration/TestFileOpCopyExcludeDir/worker=oci-snapshotter-stargz
=== CONT  TestIntegration/TestFileOpCopyExcludeDir/worker=oci-rootless
--- PASS: TestIntegration (2.39s)
    --- PASS: TestIntegration/TestFileOpCopyExcludeDir/worker=oci-rootless (0.30s)
    --- PASS: TestIntegration/TestFileOpCopyExcludeDir/worker=oci (0.36s)
    --- PASS: TestIntegration/TestFileOpCopyExcludeDir/worker=oci-snapshotter-stargz (0.39s)
    --- PASS: TestIntegration/TestFileOpCopyExcludeDir/worker=containerd-rootless (0.40s)
    --- PASS: TestIntegration/TestFileOpCopyExcludeDir/worker=containerd (0.45s)
    --- PASS: TestIntegration/TestFileOpCopyExcludeDir/worker=containerd-1.5 (0.46s)
    --- PASS: TestIntegration/TestFileOpCopyExcludeDir/worker=containerd-snapshotter-stargz (0.49s)
PASS
ok      github.com/moby/buildkit/client 2.896s
```

v0.10.5 (abridged output):

```
=== CONT  TestIntegration/TestFileOpCopyExcludeDir/worker=containerd-snapshotter-stargz
    client_test.go:1573: 
                Error Trace:    client_test.go:1573
                                                        run.go:88
                                                        run.go:202
                Error:          Received unexpected error:
                                failed to copy file info: failed to chown /tmp/bktest_containerd_stargz_grpc3443666468/root/snapshotter/snapshots/6/fs/subdir: lchown /tmp/bktest_containerd_
stargz_grpc3443666468/root/snapshotter/snapshots/6/fs/subdir: no such file or directory
                                github.com/moby/buildkit/util/stack.Enable
                                        /src/util/stack/stack.go:77
                                github.com/moby/buildkit/util/grpcerrors.FromGRPC
                                        /src/util/grpcerrors/grpcerrors.go:188
                                github.com/moby/buildkit/util/grpcerrors.UnaryClientInterceptor
                                        /src/util/grpcerrors/intercept.go:41
                                google.golang.org/grpc.(*ClientConn).Invoke
                                        /src/vendor/google.golang.org/grpc/call.go:35
                                github.com/moby/buildkit/api/services/control.(*controlClient).Solve
                                        /src/api/services/control/control.pb.go:1443
                                github.com/moby/buildkit/client.(*Client).solve.func2
                                        /src/client/solve.go:208
                                golang.org/x/sync/errgroup.(*Group).Go.func1
                                        /src/vendor/golang.org/x/sync/errgroup/errgroup.go:57
                                runtime.goexit
                                        /usr/local/go/src/runtime/asm_amd64.s:1581
                                failed to solve
                                github.com/moby/buildkit/client.(*Client).solve.func2
                                        /src/client/solve.go:221
                                golang.org/x/sync/errgroup.(*Group).Go.func1
                                        /src/vendor/golang.org/x/sync/errgroup/errgroup.go:57
                                runtime.goexit
                                        /usr/local/go/src/runtime/asm_amd64.s:1581
                Test:           TestIntegration/TestFileOpCopyExcludeDir/worker=containerd-snapshotter-stargz
```

Not sure what to do with this PR. I think we could merge it once we bump our dependency; additional test coverage is always nice.

**Comment by benjaminstrasser** [comment]
> I can confirm this bug is present in Buildkit v0.10.5 but appears to be fixed on `master`. We should be able to get the fix once Buildkit v0.11.0 has finalized (there's an [RC](https://github.com/moby/buildkit/releases/tag/v0.11.0-rc1) out so far).

Thanks for figuring this out!

> Not sure what to do with this PR. I think we could merge it once we bump our dependency; additional test coverage is always nice.

Sounds good to me. Tests are indeed almost always nice.

@vito 
Do we want to bump the version in this PR?

**Comment by vito** [comment]
> Do we want to bump the version in this PR?

Makes sense. v0.11.0-rc.1 was 12 days ago so hopefully a final version will be out sometime soon.

**Comment by benjaminstrasser** [comment]
> > Do we want to bump the version in this PR?
> 
> Makes sense. v0.11.0-rc.1 was 12 days ago so hopefully, a final version will be out sometime soon.

I will bump it once buildkit v0.11.0 is released and mark this PR as ready for review.

**Comment by gerhard** [comment]
@sipsma any idea as when we can expect BuildKit v0.11.0?

**Comment by sipsma** [comment]
@gerhard the rc came out a few days ago but from what I can tell there's still a ton of churn and last minutes fixes being merged, so I wouldn't recommend upgrading until the official release. The last I heard they were aiming for an rc2 on dec 2nd, but it hasn't come out yet. So I'd expect v0.11 "soon" but probably include a few weeks of buffer given the upcoming holidays.

**Comment by benjaminstrasser** [comment]
@gerhard 
Still waiting for buildkit to release v0.11.0. They released rc3 3 weeks ago so I think It won't be that long [v0.11.0-rc3](https://github.com/moby/buildkit/releases/tag/v0.11.0-rc3).
This PR should probably be opened again.

**Comment by sipsma** [comment]
FYI Issue for updating our dependency on buildkit is here: https://github.com/dagger/dagger/issues/4293

**Comment by vito** [comment]
@benjaminstrasser We've bumped to v0.11.0-rc.3 (https://github.com/dagger/dagger/pull/4296) so this might pass with a rebase!

**Comment by grouville** [comment]
@benjaminstrasser. To keep you in touch. Following @vito's comment, I rebased your PR. Keeping these tests is a great idea, so once it passes, I'm going to merge them.

For Github management, I assigned you #3791, as it's fixed, and these tests prove it 😇 🙏

**Review by grouville — APPROVED** [review]
Following @vito's comments above: We've bumped to v0.11.0-rc.3 (https://github.com/dagger/dagger/pull/4296), so this passes.

**Pull request merged**
