### PR TITLE
docs: Fix image source on Docker build

### PR DESCRIPTION
**Pull request by VazeeKevin**

### CODE REVIEW

**Review by helderco — APPROVED** [review]
Awesome, thanks! 🙂

**Comment by VazeeKevin** [comment]
hmmm, nothing changed on preview: https://deploy-preview-2724--devel-docs-dagger-io.netlify.app/1241/docker#dockerbuild

**Comment by helderco** [comment]
Uh... indeed!

**Comment by helderco** [comment]
Ping @slumbering

**Comment by VazeeKevin** [comment]
> JF Farge — Today at 14:48
> I've just triggered a cache clean + new deploy. In local everything works fine ... 🤔
> JF Farge — Today at 14:49
> Ok it's fixed now (maybe a cache issue...)

it's now up to date (https://docs.dagger.io/1241/docker/#dockerbuild), thanks guys 👍

**Pull request merged**
