### PR TITLE
nodejs: update examples and docs to reflect primitive return in node sdk

### PR DESCRIPTION
**Pull request by benjaminstrasser**
- [x]  examples/nodejs
- [ ] #3771 
- [ ] SDK docs

### CODE REVIEW

**Comment by slumbering** [comment]
Good catch @benjaminstrasser, thanks. This PR will be merged once SDK updates will be published to npmjs.

**Comment by slumbering** [comment]
@benjaminstrasser the `examples/nodejs` has been fully updated into the repo. Nice catch 👍 !
Thanks

**Comment by benjaminstrasser** [comment]
@slumbering 
So this PR can be closed or should I update the docs?

**Comment by slumbering** [comment]
You can actually close it. I wasn't sure because you have some remaining checkboxes.

**Pull request closed without merging**
