### PR TITLE
Add kapa to docs

### PR DESCRIPTION
**Pull request by d3rp3tt3**
This adds Kapa AI to the Dagger docs, which we're testing to see if it provides a great UX for people to quickly get answers to their Dagger-related questions.

### CODE REVIEW

**Comment by vikram-dagger** [comment]
Quick note that I see the following warning in the kapa search box

image

**Comment by d3rp3tt3** [comment]
Rehydrating

**Comment by d3rp3tt3** [comment]
> Quick note that I see the following warning in the kapa search box
> 
> (image)

@vikram-dagger - that error should have been fixed shortly after that. Let me know if you see it again. I'm waiting on decision from the team about whether we merge this.

**Comment by d3rp3tt3** [comment]
Closing since this is stale - brought in unnecessary commits. Will reopen.

**Pull request closed without merging**
