### PR TITLE
Fix provision test in native OS workflow

### PR DESCRIPTION
**Pull request by helderco**
Fixes failure in main. It was failing when _INTERNAL_DAGGER_TEST_CLI_URL is set. Changed from `tmp_path` to `tmp_path_factory` to get a clean dir on every run.

### CODE REVIEW

**Review by gerhard — APPROVED** [review]
👍 🚀

**Comment by gerhard** [comment]
This failed after the merge: https://github.com/dagger/dagger/actions/runs/6929609331/job/18847815344#step:5:154

image

**Comment by helderco** [comment]
I'll send a fix right away.

**Comment by helderco** [comment]
Seems like it was a fluke. Not sure how the temporary file that's created during _arrange_ disappeared by the _act_ part of the test.

**Pull request merged**
