### PR TITLE
Node.js: Fix linting doc snippets

### LINKED ISSUE #4857: Docs: new guides section isn't being linted
We lint the code snippets in the SDK guides, but the new Guides section uses a different path for the snippets that isn't being included in that linting. This is creating some inconsistency in code formatting.

With the playground embeds though, it's no longer a direct reference between the snippet file and what you see on the page. I assume the playground embeds are created from the snippets, @vikram-dagger please correct me if I'm wrong.

### PR DESCRIPTION
**Pull request by helderco**
Fixes #4857

I removed the duplication in eslint and prettier configs by extending them, same as I did in Python.

So you can lint docs from `sdk/nodejs` directory:
```console
yarn docs:lint
```
And format:
```console
yarn docs:fmt
```

### CODE REVIEW

**Comment by helderco** [comment]
The failing rust actions should be fixed in:
- https://github.com/dagger/dagger/pull/5380

**Review by gerhard — APPROVED** [review]
Nice improvements!

Is it OK to leave this as is? cc @slumbering 

```console
> yarn docs:lint
yarn run v1.22.19
$ yarn eslint --max-warnings=0 --resolve-plugins-relative-to=./ ../../docs/current
$ /Users/gerhard/github.com/dagger/dagger/sdk/nodejs/node_modules/.bin/eslint --max-warnings=0 --resolve-plugins-relative-to=./ ../../docs/current
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.1.0

YOUR TYPESCRIPT VERSION: 5.1.3

Please only submit bug reports when using the officially supported version.

=============
✨  Done in 3.18s.
```

Same issue is happening even after rebasing on top of `main`.

**Comment by helderco** [comment]
@gerhard Yeah, we should upgrade that but I'd say it's a different PR. Not introduced by this one.

**Comment by helderco** [comment]
This would be a downgrade actually. Probably `@typescript-eslint/typescript-estree` is too strict on `typescript <5.1.0` here. It's working fine, on a next update they'll probably bump that upper limit and the warning will go away.

**Comment by helderco** [comment]
For reference this was only closed 3 days ago:
- https://github.com/typescript-eslint/typescript-eslint/issues/6934

**Comment by gerhard** [comment]
Sounds good to me!

**Pull request merged**
