### PR TITLE
docs: Adds openshift gitlab guide

### PR DESCRIPTION
**Pull request by schlapzz**

### CODE REVIEW

**Comment by gerhard** [comment]
We talked with @vikram-dagger about this one today.

I've added it to my list, will circle back towards the end of this week.

Thank you @schlapzz 💪

**Comment by schlapzz** [comment]
@gerhard Any new on this?

**Comment by vikram-dagger** [comment]
@schlapzz  please rebase this before merging, as the docs filesystem structure has changed. See https://github.com/dagger/dagger/pull/6164/ for details. Feel free to ping me if you need any help.

**Comment by gerhard** [comment]
I ran out of time before the holidays @schlapzz, will come back to this second week of January.

**Comment by chrira** [comment]
@gerhard I took @schlapzz changes, put them on the actual main and adapted them to the new doc structure.
This you'll find here: https://github.com/dagger/dagger/pull/6487
You can close this PR and check the new one, thanks!

**Comment by gerhard** [comment]
My apologies @schlapzz for not getting round this one.

Thanks to @chrira's PR timing, I was finally able to get this out: https://docs.dagger.io/488564/openshift-gitlab

Thank you both for sticking with this 💪💪

**Pull request closed without merging**
