### PR TITLE
sdk: python: Revert to black’s default max line length

### LINKED ISSUE #3698: Reduce line length in lint?
I've increased from 88 (default) to 119 because:
- Looks better in a lot of cases
- 119 is the max to for good code reviews in GitHub
- Screen sizes theses days are bigger than the default cap

Cons:
- Split pane editor in the IDE
- **With a chainable API it's better to force multiline sooner** 👈

Note: it'll create a PR with lots of cosmetic changes.

### PR DESCRIPTION
**Pull request by helderco**
Fixes #3698

Signed-off-by: Helder Correia

### CODE REVIEW

**Comment by gerhard** [comment]
What am I doing wrong?

image

**Review by sipsma — APPROVED** [review]

**Review by gerhard — COMMENTED** [review]
Tests are failing locally. I don't feel confident merging this. WDYT @helderco?

image

**Comment by helderco** [comment]
@gerhard That's because of the provisioner, be patient, it's coming... :)

**Comment by helderco** [comment]
Trying to speed up to that PR.

**Comment by helderco** [comment]
In the meantime you just have to run `cloak dev` manually.

**Pull request merged**
