### PR TITLE
Fix export cache issue

### LINKED ISSUE #1551: Export cache to local host do not work
### Context

Currently working on #1020, I first tried to understand how buildkit manage his cache in local.
But I found that dagger do not actually use local cache

### Code snippet

```cue
package test

import (
	"dagger.io/dagger/engine"
)

engine.#Plan & {
	actions: {
		image: engine.#Pull & {
			source: "alpine"
		}

		test: engine.#Exec & {
			input: image.output
			args: ["/bin/sh", "-c", """
					sleep 15 && echo test
				"""]
		}
	}
}
```

### Repro case

```shell
# Down buildkit daemon to remove daemon cache
docker container stop dagger-buildkitd && docker container rm dagger-buildkitd && docker volume rm dagger-buildkitd

# Create store directory
mkdir -p store

# List file
ls
store          test-cache.cue

# Run dagger for the first time
dagger --europa up test-cache.cue --cache-from type=local,src=store --cache-to type=local,mode=max,dest=store      

WARN[0002] local cache import at store not found due to err: could not read store/index.json: open store/index.json: no such file or directory 
[✔] actions.image                                                                                                                                                                         2.3s
[✔] actions.test                                                                                                                                                                         18.8s

# Check cache (OK)
dagger --europa up test-cache.cue --cache-from type=local,src=store --cache-to type=local,mode=max,dest=store
[✔] actions.image                                                                                                                                                                         0.7s
[✔] actions.test    
                                                                                                                                                                      0.0s
# Remove daemon & volume
docker container stop dagger-buildkitd && docker container rm dagger-buildkitd && docker volume rm dagger-buildkitd
dagger-buildkitd
dagger-buildkitd
dagger-buildkitd


# Rerun dagger (KO, it do not use cache)
dagger --europa up test-cache.cue --cache-from type=local,src=store --cache-to type=local,mode=max,dest=store      
[✔] actions.image                                                                                                                                                                         2.1s
[✔] actions.test                                                                                                                                                                         18.8s

# As you see, cache is correctly set
ls store/
blobs      index.json ingest
```

### PR DESCRIPTION
**Pull request by TomChv**
Resolve #1551 and #1020.
We are never returning the result of solved operations so Buildkit could not cache the layer.
This commit implements a simple system to forward operations' result to the main build to cache it.

Signed-off-by: Vasek - Tom C <tom.chauveau@epitech.eu>

### CODE REVIEW

**Review by aluzzardi — APPROVED** [review]

**Comment by aluzzardi** [comment]
LGTM, needs a rebase

**Comment by TomChv** [comment]
@aluzzardi No conflict remains, merge it when you want, I've check CI and except sops error (du to GitHub secrets), tests succeed and more than that, they are cached ;)

**Comment by TomChv** [comment]
CI looks fixed, thank you @marcosnils for the rerun!

**Comment by TomChv** [comment]
I'm closing this branch, she's not synchronised with `dagger/dagger` and it looks like the commit history is broken, let's move to #1962 to avoid branch issues

**Pull request closed without merging**
