### PR TITLE
universe(x): Add Scaleway CLI experimental package

### PR DESCRIPTION
**Pull request by TomChv**
Implement basic Scaleway CLI to manage Scaleway infrastructure directly from
Dagger.

Signed-off-by: Vasek - Tom C <tom.chauveau@epitech.eu>

### CODE REVIEW

**Comment by mircubed** [comment]
@jpadams reminder to review :)

**Review by samalba — CHANGES_REQUESTED** [review]
Since pkg/universe.dagger.io/x/* is deprecated, could you move this one to pkg/universe.dagger.io/alpha?

The pkg makes sense to me IMO. Do you (or another user) have a use case for it?

**Comment by TomChv** [comment]
> Do you @TomChv (or another user) have a use case for it?

I'll certainly use it for a personal project to deploy infrastructure so yes :)

**Comment by TomChv** [comment]
> Since pkg/universe.dagger.io/x/* is deprecated, could you move this one to pkg/universe.dagger.io/alpha?

Fixed in https://github.com/dagger/dagger/pull/2578/commits/14e4b869414020dce6a6d1b49b01ecf793cefdd4

**Review by samalba — APPROVED** [review]

**Pull request merged**
