### PR TITLE
fix(universe/docker): support exporting relative to working directory

### PR DESCRIPTION
**Pull request by GeorgeMac**
Unsure if this is a desired or not, but thought I would propose it.
I got stuck using `docker` package, after assuming `export` would resolve relative to `workdir`.

I started a little thread in the [help](https://discord.com/channels/707636530424053791/709803368318632038/1007931064876019753) channel in discord for my issue.
Eventually, I figured out what I was doing wrong and solved it with an absolute path.

This change updates `files`, `directories` and `secrets` within `export` to resolve any relative paths against the `workdir` base.

### CODE REVIEW

**Review by marcosnils — COMMENTED** [review]
LGTM after fixing linting issues.

**Comment by GeorgeMac** [comment]
Thanks @marcosnils 

qq. it says `failed to execute plan: maximum timeout reached` as the error, and I can't see any other kinds of failure (I did hit two previously, but I think I cleaned all those up).

**Review by marcosnils — APPROVED** [review]

**Comment by GeorgeMac** [comment]
Ah, seems there is an issue in there. I will investigate!

**Review by marcosnils — CHANGES_REQUESTED** [review]
tests don't pass.

**Comment by GeorgeMac** [comment]
@marcosnils that one in `Universe Tests - Europa` timed out pulling from dockerhub.
Mind if I get a restart?

**Comment by gerhard** [comment]
FWIW re flaky tests https://github.com/dagger/dagger/pull/2941#issuecomment-1215705175

**Review by marcosnils — APPROVED** [review]

**Comment by GeorgeMac** [comment]
Thanks, everyone 🙏

**Comment by marcosnils** [comment]
> Thanks, everyone pray

thanks you for the contribution :raised_hands:

**Pull request merged**
