### PR TITLE
cli: automatically make dir+file flags absolute paths

### PR DESCRIPTION
**Pull request by sipsma**
The engine complains if the Host API is used with non-absolute paths. For the CLI's use case, this is not really meaningful since the user is explicitly passing paths anyways so we can safely make the paths absolute on the user's behalf automatically.

Adding to v0.10 since it's an annoying enough papercut and the fix is extremely trivial (vast majority of additions here are test code)

### CODE REVIEW

**Review by jedevc — APPROVED** [review]
Oh nice!

I was expecting this would be done by changing the API to remove the warning entirely, but this works nicely :tada:

**Comment by sipsma** [comment]
Failures are due to docs issues being fixed in https://github.com/dagger/dagger/pull/6745, will just rebase this one on that once merged

**Comment by sipsma** [comment]
> I was expecting this would be done by changing the API to remove the warning entirely, but this works nicely 🎉

Yeah I suspect we *could* just lift the limitation there at this point, but in the interest of minimizing boat rocking at the last minute decided to just go with this 😄

**Review by helderco — APPROVED** [review]
Orthogonal to this but we could also support loading from git://, right?

**Comment by sipsma** [comment]
> Orthogonal to this but we could also support loading from git://, right?

Yep! Just wanted this PR to be as minimal as possible, but that should be pretty trivial as a follow-up too if desired

**Comment by jedevc** [comment]
> Orthogonal to this but we could also support loading from git://, right?

:thinking: I might be missing something, but don't we do this already? https://github.com/sipsma/dagger/blob/ea8997b2e6eec28d0b46969479f963c3846641d5/cmd/dagger/flags.go#L193

Added in https://github.com/dagger/dagger/pull/6058

**Comment by sipsma** [comment]
> > Orthogonal to this but we could also support loading from git://, right?
> 
> 🤔 I might be missing something, but don't we do this already? https://github.com/sipsma/dagger/blob/ea8997b2e6eec28d0b46969479f963c3846641d5/cmd/dagger/flags.go#L193
> 
> Added in #6058

@jedevc that was for `Directory` args, we don't have the same for `File` yet though

**Pull request merged**
