### PR TITLE
Fail auto-release if no changes since previous release

### PR DESCRIPTION
**Pull request by gerhard**
We want to fail auto-releases on purpose if there have been no changes since the previous release. While this can happen, it is rare and we should take notice of it, hence the failure.

For more context, see this Discord thread:
https://discord.com/channels/707636530424053791/796905486145683506/1022141805468328027

My intention has been to update this to Dagger for a long time now. It kept getting trumped by other priorities, and while now is the wrong time to do it, every time I have to touch this YAML, I sigh and tell myself: "one day...". Not today though.

I checked that this works as expected via https://github.com/gerhard/dagger/actions/runs/3103289111/jobs/5026460988

FWIW, these are the temporary changes which I used for that check:

```diff
diff --git a/.github/workflows/auto-release.yml b/.github/workflows/auto-release.yml
index ea78cfee..6db172af 100644
--- a/.github/workflows/auto-release.yml
+++ b/.github/workflows/auto-release.yml
@@ -48,7 +48,7 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SEMVER_BUMP: ${{ github.event.inputs.release_type }}
         run: |
-          previous_release_version="$(gh api /repos/gerhard/:repo/tags --jq '.[0].name')"
+          previous_release_version="$(gh api /repos/:owner/:repo/releases --jq '.[0].tag_name')"
           echo "PREVIOUS RELEASE VERSION: $previous_release_version"
           printf "::set-output name=%s::%s\n" previous "$previous_release_version"
           if [[ -n "${{ github.event.inputs.release_version }}" ]]
@@ -65,10 +65,9 @@ jobs:
 
       - name: "Fail if no changes since previous release"
         run: |
-          git fetch origin main
           echo "Changes since previous release:"
-          git diff --color --stat ${{ steps.release_version.outputs.previous }}...origin/main
-          if [ -z "$(git diff --color --stat ${{ steps.release_version.outputs.previous }}...origin/main)" ]
+          git diff --color --stat ${{ steps.release_version.outputs.previous }}...$GITHUB_SHA
+          if [ -z "$(git diff --color --stat ${{ steps.release_version.outputs.previous }}...$GITHUB_SHA)" ]
           then
             echo "This auto-release was failed on purpose: there have been no changes since ${{ steps.release_version.outputs.previous }}."
             echo "While this can happen, it is rare and we should take notice of it, hence the failure."

```

---

BTW, my intention has been to update this to Dagger for a long time now. It kept getting trumped by other priorities, and while now is the wrong time to do it, every time I have to touch this YAML, I sigh and tell myself: one day... Not today though.

### CODE REVIEW

**Comment by gerhard** [comment]
After this gets merged, we should make an actual change that warrants a new release and trigger manually as `v0.2.35`.

To confirm that it works as expected, after `auto-release` workflow succeeds and publishes `v0.2.35` we should trigger another manual one and watch it fail, since there should be no changes between that `v0.2.35` and the next release.

**Comment by gerhard** [comment]
@jpadams https://github.com/dagger/dagger/pull/3139 is the PR that I would like to merge before we try this change out from `main`. As soon as that PR is merged, this one will be ready to run through.

**Review by jpadams — APPROVED** [review]
LGTM. We'll see how it goes this time 🤞

**Comment by jpadams** [comment]
auto-release ran today.

I re-ran manually with no new commits. Failed as expected! 🎉 

image

**Pull request merged**
