### PR TITLE
feat(dev): improve testing in sdk elixir dev module

### PR DESCRIPTION
**Pull request by wingyplus**
* Drop Elixir v1.14 and add Elixir v1.17.
* Improve Elixir version management by using map instead of slice of string. With map, we can freely manage OTP version and OS separately.
* Visualization improvement, just using `errgroup.Go` is quite hard to read on the TUI visualization. In this changes, add the tracer to it by labeling it with `test - elixir/<version>` pattern.
* Add `dagger_codegen` test by running only elixir latest version. And add tracer to separate between `dagger` SDK and `dagger_codegen` under test version.

### CODE REVIEW

**Comment by helderco** [comment]
Hey Win! Is this rebased and updated?

**Comment by wingyplus** [comment]
@helderco Just rebased. Waiting for CI to pass. 🙏

**Review by TomChv — APPROVED** [review]
Rebase, make sure tests passes and good to go

**Review by helderco — APPROVED** [review]

**Comment by helderco** [comment]
Failure is a known flake.

**Pull request merged**
