### PR TITLE
docs: Document installation using macports

### PR DESCRIPTION
**Pull request by esafak**
Update _install-cli.mdx to mention macports

### CODE REVIEW

**Comment by vikram-dagger** [comment]
Ping @gerhard @kpenfound @jpadams for review

**Comment by vikram-dagger** [comment]
Ping @gerhard @kpenfound @jpadams @marcosnils for review

**Comment by marcosnils** [comment]
@vikram-dagger  let's hold to merge this since it's currently violating the Dagger trademark (https://dagger.io/trademark-guidelines) as the macports project is basically distributing a repackaging of the Dagger package. cc @jpadams

**Comment by mircubed** [comment]
@jpadams please advise on next steps here, thanks!

**Comment by jpadams** [comment]
@esafak Thanks for the PR!
MacPorts is not in violation of our policy since it's distributing our official darwin builds.

Our official installation method for MacOS, driven by current user demand, is via the Homebrew tap that Dagger maintains or via our download script.

Our plan is to look for a way to incorporate alternative installation methods that are not maintained by Dagger into the docs in a way that makes it clear to users what is official/maintained-by-Dagger and what is community-supported.

I'm going to close this PR, but link it to this new issue where we'll figure out the right way to list community-supported installation methods like this.
https://github.com/dagger/dagger/issues/7588

**Pull request closed without merging**
