### PR TITLE
dagger.json

### PR DESCRIPTION
**Pull request by sipsma**
Related: https://github.com/dagger/dagger/issues/3016

### Follow-ups

1. https://github.com/dagger/dagger/issues/3351
1. Announce breaking change to community once merged?
   * Actually now that extensions are being deferred for public launch, maybe not? We need to decide what to do about all the existing extensions+users trying them.

### TODO
- [x] Make dagger.json optional (https://github.com/dagger/dagger/issues/3275)
- [x] Rebase on new cloak->dagger commits and code-first schema PR (once that's merged soon)
- [x] Docs (just updated the existing extension guides for now, since that's the only time they are needed)
- [x] Fix gitdeps example in the repo 
- [x] More testing (add new tests here, validate against external repos like todoapp and other extensions)
- [x] The format of extensions like `{"local": "path/to/local"}` is weird, made sense in yaml but not json, worth a quick re-assessment
- [x] Going to try making a CLI wrapper for CRUD operations quick. If this devolves into many subproblems, discussions, other open design threads, etc. then I will save that for a follow up.
- [x] Remove the find-up behavior (for now, pending further discussion)

### Format

Example w/ an SDK
```json
{
  "name": "myproject",
  "extensions": {
    "alpine": {
      "local": {
        "path": "examples/alpine/dagger.json"
      }
    },
    "netlify": {
      "git": {
        "remote": "https://github.com/sipsma/foo",
        "ref": "bar",
        "path": "path/to/netlify/dagger.json"
      }
    }
  },
  "sdk": "go"
}
```

* One important part of the format is that `extensions` is keyed by the extension name (whereas previously in the yaml you just provided a list of locations). This is a good thing I think: it reflects the fact that extensions are currently identified uniquely in the router by their name alone and there thus can only be one with a given name at a time.

* Other than that, I am not a huge fan of the weird `"location"` and `"params"` keys; it exists mostly because it was a convenient format to achieve some semblance of polymorphism in the go code for parsing all this while still using static types to the extent possible. Happy to adjust it if needed.

#### sdk field

`"sdk"` is an optional field. The behavior of loading a project will change depending on whether it is present or not:
1. If it is present - you are defining a *new* API, so when clients load it, *only* that new API will be presented to them.
3. If it is not present - there is no new API defined, so instead clients loading `dagger.json`  will be presented the merged API of the extensions defined in `dagger.json`.

This is the only relatively clean way I found in the short term to achieve the behavior described [here](https://github.com/dagger/dagger/issues/3016#issue-1376410325) (and that was present previously due to distinction between dependencies and extensions) while staying logically consistent.

***Note that there's a huge caveat to all of the above: [until this issue has been fixed](https://github.com/dagger/dagger/issues/3072), none of the above matters because there is only a single global schema.*** The code has been written such that the above behavior should appear once we've addressed that issue though, so it's extremely important we are all on the same page about it rather than surprised later.

Let me know if this makes sense, it's very subtle, I can provide a full concrete example if helpful.

### Loading Behavior
* `dagger.json` can only be used for one extension now. No more scripts field either
* Removed the "find-up" behavior (for now, can discuss more, sometimes it's nice sometimes it's annoying)

### CLI interface

Threw together a *very* basic CLI interface. Happy to adjust and clean this up, but want to get initial feedback before too much work.

#### `dagger project`
Dumps the current json (can support more formats in future)

#### `dagger project init`
```console
dagger project init --name foobar --sdk go
```
* creates a new `dagger.json` in your cwd
* `sdk` is optional

#### `dagger project add`
local:
```console
dagger project add local --path path/to/dagger.json
```

git:
```console
dagger project add git --remote https://github.com/sipsma/foo --ref bar --path path/to/dagger.json
```

* The "name" key is found by actually loading the `dagger.json` specified (in the case of git this requires use of the engine and project API, which is pretty convenient)
* If there's another extension with the same name key, the current behavior is to just overwrite it. Can change that though

#### `dagger project rm`
```console
dagger project rm --name netlify
```
* remove the extension with the given name from the extensions field in dagger.json
* `--name` should probably just a positional arg, it's a flag for consistency atm but writing this now that seems silly. Will update

### CODE REVIEW

**Comment by aluzzardi** [comment]
/cc @jpadams @kpenfound 

This is the WIP cloak.yaml --> dagger.json PR.

1) This is where universe would fit in as a a dependency (e.g. `git`, `local`, ... `universe`?)
2) Perhaps some of the file format could be shared between the two

**Comment by shykes** [comment]
FYI @jpadams @kpenfound successor of cloak.yaml, part of extension design

**Comment by aluzzardi** [comment]
Overall looks good. Open questions on format, CLI, and other nitpickery:

Format:

```json
    "netlify": {
      "location": "git",
      "params": {
        "remote": "https://github.com/sipsma/foo",
        "ref": "bar",
        "path": "path/to/netlify/dagger.json"
      }
    }
```

Brainstorming here, but how would we feel like encoding this as a string and "restructuring" later rather than storing the structure?

Example from package.json https://docs.npmjs.com/cli/v8/configuring-npm/package-json#dependencies

```json
{
  "name": "baz",
  "dependencies": {
    "bar": "file:../foo/bar"
  }
}
```

They support git URLs (with `#<commit-ish>` ref information), GitHub, local, npm (e.g. our "universe").

Similar to what `go.mod` does (minus the npm/registry part).

Same feedback about the CLI: rather than `dagger project add git --remote https://github.com/sipsma/foo --ref bar --path path/to/dagger.json`, we could re-use this "string" syntax (just like `yarn add <git remote url>`)

**=== If remaining with the current structured approach, one nitpick ===**

Rather than a `location string` + `params any` (hard to manually read/write), I'd suggest something like this instead:

```go
type Extension struct {
    Git *GitParams `json:"git,omitempty"`
    Local *LocalParams `json:"local,omitempty"`
 }
```

That way this:

```json
{
    "netlify": {
      "location": "git",
      "params": {
        "remote": "https://github.com/sipsma/foo",
        "ref": "bar",
        "path": "path/to/netlify/dagger.json"
      }
    }
}
```

could be written as:

```json
{
    "netlify": {
      "git": {
        "remote": "https://github.com/sipsma/foo",
        "ref": "bar",
        "path": "path/to/netlify/dagger.json"
      }
    }
}
```

(yeah the Go code would less nice since we'd need to switch over all the pointers and check which is not `nil` to figure out `location`, but IMHO it's nicer to read/write/document/validate)

**Comment by shykes** [comment]
@aluzzardi I’d say if it’s good enough for package.json, it’s good enough for us :) (for the parts that are actually semantically equivalent in both files of course)

**Comment by sipsma** [comment]
@aluzzardi 

> Brainstorming here, but how would we feel like encoding this as a string and "restructuring" later rather than storing the structure?

I think we should definitely support that for the CLI interface (independently came up in [this comment](https://github.com/dagger/dagger/issues/3275#issuecomment-1271983052)) but what's the advantage of doing that in the json file? The json config is meant to be human readable but not optimized for human writing (CLI should be main interface), which is where our approach deviates from package.json. Having structured data in a string in json seems more complicated than just using the structure of json directly. It also makes it more complicated to extra information out (have deser json and then deser strings inside it).

But again, all for supporting that on the CLI interface level. I do think the `--flag` format should remain there too because it's often easier to programmatically setup flags than it is to programmatically construct a structured string, but the structured strings is nicer to write by hand manually.

**Review by aluzzardi — APPROVED** [review]

**Pull request merged**
