### PR TITLE
docs: Add Docusaurus medium-zoom plugin

### PR DESCRIPTION
**Pull request by jossemarGT**
As per discussed in #2981

The medium-zoom plugin could improve the user experience when reading diagrams that are wider than the page layout.

### CODE REVIEW

**Comment by TomChv** [comment]
I tried the preview, it works well :rocket:

**Comment by dolanor** [comment]
Tested as well.
LGTM.

**Comment by slumbering** [comment]
@jossemarGT Thanks for your PR.

After trying on Safari, firefox and Brave (macOS 12.5.1) i've got a recurrent issue. The plugin works randomly. 

How to reproduce:
 - open https://deploy-preview-2995--devel-docs-dagger-io.netlify.app/1247/dagger-fs/
 - click on an image to zoom. Sometimes it works, sometimes not.
 - If it works, refresh the page and try again. It should fail
 
I get a blank screen.

ezgif com-gif-maker


The other problem here is every image become zoomable, which is not the expected behaviour (we don't want those images for instance from https://deploy-preview-2995--devel-docs-dagger-io.netlify.app/ to be zoomable)

**Comment by jossemarGT** [comment]
> After trying on Safari, firefox and Brave (macOS 12.5.1) i've got a recurrent issue. The plugin works randomly.
> [...]
> I get a blank screen.

Apologies for that. I recall getting this result locally once, and then I dismissed it, thinking there was something related to my browser's cache. I'll drill down this issue to spot if this behavior comes from the `medium-zoom` library itself or is related to how the Docusaurus plugin `plugin-image-zoom` initializes it.

> The other problem here is every image become zoomable, which is not the expected behaviour

Yes, I intentionally left it this way to get your attention and feedback :sweat_smile: . Which constraints should we have in mind to let an image be zoomable?

- It is an image on the website :x:
- It is an image on A, B & C pages
- It is a diagram on the website
- It is a diagram on A, B & C pages
- It is a diagram wider than Y px
 
Since the criteria may vary from time to time, also I would like to ask, does the team mind adding a CSS class (i.e.: `zoomable`) to the elements we want to enable this feature? I _think_ this is the most straightforward approach, but it comes with a maintenance cost.

**Comment by slumbering** [comment]
> > After trying on Safari, firefox and Brave (macOS 12.5.1) i've got a recurrent issue. The plugin works randomly.
> > [...]
> > I get a blank screen.
> 
> Apologies for that. I recall getting this result locally once, and then I dismissed it, thinking there was something related to my browser's cache. I'll drill down this issue to spot if this behavior comes from the `medium-zoom` library itself or is related to how the Docusaurus plugin `plugin-image-zoom` initializes it.
> 
> > The other problem here is every image become zoomable, which is not the expected behaviour
> 
> Yes, I intentionally left it this way to get your attention and feedback 😅 . Which constraints should we have in mind to let an image be zoomable?
> 
> * It is an image on the website ❌
> * It is an image on A, B & C pages
> * It is a diagram on the website
> * It is a diagram on A, B & C pages
> * It is a diagram wider than Y px
> 
> Since the criteria may vary from time to time, also I would like to ask, does the team mind adding a CSS class (i.e.: `zoomable`) to the elements we want to enable this feature? I _think_ this is the most straightforward approach, but it comes with a maintenance cost.

There is a section on the plugin repo that explain how you can exclude images: https://github.com/flexanalytics/plugin-image-zoom#excluding-images-from-using-zoom.
Instead of adding a class to make the image zoomable, you can wrap your image in a <em> tag for instance to exclude it. It still comes with a maintenance cost but I would rather have every image zoomable and exclude some of them.

**Comment by gerhard** [comment]
What are your thoughts on this @slumbering?

**Comment by slumbering** [comment]
> > Instead of adding a class to make the image zoomable, you can wrap your image in a tag for instance to exclude it. It still comes with a maintenance cost but I would rather have every image zoomable and exclude some of them.
> 
> Noted, still I need to clarify the following. When I proposed a class, I thought it might be better to manually add this capability for images wider than `~710px` since there are a few, requiring less maintenance effort. But I was not sure about the expected outcome, so now you have suggested one approach I'll proceed that way.
> 
> When enabling it by default for all the images with exceptions, I need to double check, do we want to exclude the images wrapping them on an `em` element instead of a class? The `em` mentioned on that plugin's documentation is just a suggestion, since the `selector` is configurable.
> 
> Let me share how it would look like for either with the following snippet from `CardGrid` in [How It works](https://docs.dagger.io/f44rm/how-it-works) page:
> 
> ```js
> <div
>   className={`${styles.card} ${x.fullWidth ? styles.fullWidth : ""}`}
> >
>   <em></em> /* selector: '.markdown :not(em) > img' */
>   /* or 
>    // selector: '.markdown img:not(.not-zoom)'
>   */
>   <div className={styles.description}>
>     <h4>{x.label}</h4>
>     <p>{x.description}</p>
>   </div>
> </div>
> ```
> 
> Side question. When we wrap up this discussion, what is best for you? Should I close this PR to continue troubleshooting the blank page issue?

@jossemarGT: semantically speaking the second option is better indeed. 
` // selector: '.markdown img:not(.not-zoom)'`

For your side question it's ok to continue troubleshooting here. Thanks

**Comment by jossemarGT** [comment]
Updated :sparkles:  Please take a look.

Turns out the root cause of the "blank" page was the `medium-zoom` object being attached to images that were not fully loaded upon react initialization or route change. This behavior is not correctly handled by the plugin we used at the beginning, but this other one does ([docusaurus-plugin-image-zoom](https://github.com/gabrielcsapo/docusaurus-plugin-image-zoom)). The great thing about this other plugin is that it already supports "night mode"  out of the box.

Also, as discussed before, I have added the `not-zoom` className to all the non-illustrative images like the ones we see on the overview page.  I had to update a couple of components to accomplish this, so if we find it too intrusive, we can drop that commit and discuss other approaches.

**Comment by slumbering** [comment]
hey @jossemarGT ! Looks good to me \o/ ! Thanks for this contribution

**Review by slumbering — APPROVED** [review]

**Pull request merged**
