### PR TITLE
.dagger: fix gitDir glob pattern to ignore all but `.git`

### PR DESCRIPTION
**Pull request by vito**
right now this is uploading everything which takes quite a while

### CODE REVIEW

**Comment by jedevc** [comment]
Aha :saluting_face: noticed this, thanks!

**Comment by gerhard** [comment]
I **think** this fixes:
- https://github.com/dagger/dagger/issues/8395

Would you agree @vito?

**Comment by vito** [comment]
@gerhard Hmm hard to say - this particular fix should only affect invoking the Dagger module at the root of the repo. Sounds like those issues are more general.

**Comment by shykes** [comment]
This is because of the breaking change in 0.13. Previously you had to omit the `*'

**Pull request merged**
