### PR TITLE
Delete leftover module files in zenith docs

### PR DESCRIPTION
**Pull request by helderco**
Did a dagger mod sync on snippets with a dagger.json, removed all generated files from the others.

### CODE REVIEW

**Comment by helderco** [comment]
I realize now that the `dagger.gen.go` files may have been committed because of the linter, however it makes it more complicated to manage. I recently made changes to the core API and it made things more difficult.

There has to be a better way. We could ignore snippets that have dependencies for now and add a step later that does a mod sync on these before linting.

**Comment by vikram-dagger** [comment]
Based on last comment, I'm guessing this can't be merged as is @helderco ? Or how would you like to proceed?

**Comment by helderco** [comment]
As a quick workaround I'm going to just find `dagger.json` files in `docs/` and call mod sync on them before linting.

**Comment by gerhard** [comment]
Closing this since it doesn't seem to be in a good state - merge conflicts - and a lot of things have changed since.

It's OK to open this as a new PR and see it through more swiftly.

**Pull request closed without merging**
