### PR TITLE
wip: feat: add Pulumi support

### PR DESCRIPTION
**Pull request by rawkode**
Still to do:

- [ ] Support Local State
- [ ] Support Python runtime
- [ ] Support dotnet runtime
- [ ] Support go runtime
- [ ] Add test to ensure outputs loaded correctly

### CODE REVIEW

**Comment by rawkode** [comment]
@shykes Do should I move this to my own GitHub? How do I namespace it?

**Comment by shykes** [comment]
I propose that we try an experiment with @rawkode as our fearless volunteer :)

* Let’s create an experimental namespace under `universe.dagger.io/x`
* Individual contributors vetted by the Dagger maintainers get co-maintainer privileges to `universe.dagger.io/x/<email>`. For example I may get `universe.dagger.io/x/sh.dagger@hykes.org`. Only individual email addresses are allowed. This allows continuity of individual ownership across job changes. It also clarifies the fact that these are not officially endorsed packages. For example what I publish in my experimental space is not officially endorsed or guaranteed to work by Dagger; and @rawkode ’s pulumi package is not endorsed by Pulumi even though he works there. I believe this will prevent headaches down the road.

In this particular case @rawkode could you adapt this PR to target your experimental space? Please use an email address that meets the criteria above. If you have any question or concern please let us know.

@dagger/maintainers any thoughts or concerns?

**Comment by dolanor** [comment]
I agree with Helder here, for privacy and spamming reasons.

**Comment by shykes** [comment]
> Is there an advantage to using an email? To many, emails are private. I wouldn't want to use mine. I prefer a simple unique name like a github username: `universe.dagger.io/x/rawkode/pulumi`.

The advantage of using an email is that we can 1) avoid taking responsibility for trust and identity (a difficult and time-consuming problem), and also 2) avoid locking the community into a proprietary trust and identity platform (for example github usernames).

Email privacy is a concern, but it's one that we all deal with already: for example all our open-source git commits have an email address on them. I personally use a separate email address just for that purpose, specifically because I am concerned about privacy.

So in summary:

| | Email | Use another service's usernames (eg. Github) |  Manage our own usernames |
| -- | -- | -- | -- |
| Avoid the work of managing identity & trust | ✅ | ✅ | ❌ |
| Avoid lock-in to a random third-party platform | ✅ | ❌ | ✅ |
| Users don't have to create yet another username | ✅| ✅ |❌ |
| Users can control which email address is public | ✅ | ✅ | ✅ |
| Users never need to publish an email address | ❌ | ❌ | ❌ |

> As I understand this, we're talking only about packages that are candidates to be adopted officially in, e.g., `universe.dagger.io/pulumi`, correct?

In this case, yes, but not necessarily. You can publish a package without specifically planning for it to become official. You just publish packages, and if it's good material for an official package, we can pull it in.

> I like the _incubator_ idea above, but I agree, this allows us to move faster for now.

Yeah we can discuss that one in parallel. I am less immediately excited about a centralized _incubator_, because it doesn't solve my immediate problem of removing coordination bottlenecks. In a way it creates more work, because now we have to define clear rules for deciding when a package moves out of incubator, what are the different guarantees of each...

**Comment by helderco** [comment]
> In this case, yes, but not necessarily. You can publish a package without specifically planning for it to become official. You just publish packages, and if it's good material for an official package, we can pull it in.

My concern with this is that everyone will have every experiment in their projects with project update since it comes with `universe.dagger.io`. But it’s temporary.

**Comment by marcosnils** [comment]
> My concern with this is that everyone will have every experiment in their projects with project update since it comes with `universe.dagger.io`

that's a good and valid point. 

On the other hand, why was this PR closed? :thinking:

**Comment by rawkode** [comment]
It was closed because this PR targeted Dagger 0.1. I replaced with #1991

**Pull request closed without merging**
