### PR TITLE
universe: add `#Delete` definition to experimental kubernetes package

### PR DESCRIPTION
**Pull request by TomChv**
Implement `#Delete` definition to kubernetes.

To avoid duplication, this commit also implement a private base definition
and simplify current `#Apply` and `#Delete`

Signed-off-by: Vasek - Tom C <tom.chauveau@epitech.eu>

### CODE REVIEW

**Review by helderco — APPROVED** [review]
LGTM

**Comment by gerhard** [comment]
👀

**Comment by gerhard** [comment]
Other tasks kept bumping this until I ran out of time, will look into it tomorrow.

**Comment by gerhard** [comment]
Picking this one up again.

**Review by gerhard — APPROVED** [review]
✅ Kustomises nginx as expected
✅ Deletes nginx as expected

image

🙇‍♂️ I had to edit the `apply-delete.cue` file to check the apply, then the delete. For the next PR, is there something that we could do to improve this @TomChv?

🚀

**Comment by TomChv** [comment]
> I had to edit the apply-delete.cue file to check the apply, then the delete.
For the next PR, is there something that we could do to improve this @TomChv?

Which changes have you done?
On my side I was checking in log to see if pods were successfully created or not

**Pull request merged**
