### PR TITLE
Revert GitHub action dagger for test / sdk / nodejs

### PR DESCRIPTION
**Pull request by gerhard**
Follow-up to:
- https://github.com/dagger/dagger/pull/3783

### CODE REVIEW

**Comment by gerhard** [comment]
`yarn test` from `sdk/nodejs` runs fine.

`./hack/make sdk:nodejs:test` fails the same as it does in GitHub Actions: https://github.com/dagger/dagger/actions/runs/3470283360/jobs/5798294185#step:4:855

@slumbering suspects an issue with https://github.com/dagger/dagger/blob/15fb73a3431e9ad42ec522040a7a4f287c992630/sdk/nodejs/provisioning/docker-provision/image.ts#L211

**Comment by gerhard** [comment]
@aluzzardi @sipsma do you have a few spare cycles to look into this?

If not, that's OK, I can skip the dagger integration in this PR and continue using GitHub Actions directly until we have time to dig into this issue. My only worry is that this failure might be masking a problem in the Node.js SDK, but I'm not sure.

**Comment by sipsma** [comment]
> Could this be the DAGGER_HOST & dagger-in-dagger related

Yeah was just typing that, it will be resolved by this issue: https://github.com/dagger/dagger/issues/3834

I can take a look at it quickly after double checking no one else has started yet

**Comment by sipsma** [comment]
@gerhard fixed the http provisioning here: https://github.com/dagger/dagger/pull/3851

Was able to run `./hack/make sdk:nodejs:test` locally successfully after that change, so hopefully should be good here on a rebase

**Review by sipsma — APPROVED** [review]

**Comment by gerhard** [comment]
Thank you @sipsma 🙌

**Pull request merged**
