### PR TITLE
services support

### PR DESCRIPTION
**Pull request by aluzzardi**
This PR adds support for services, specifically:

- Creating services (asynchronous containers)
- Service control (listing, retrieving, stopping, ...)
- tty streaming over WebSocket with CLI support (`cloak attach`)
- Experimental `debugger` extension

TODO:

- Improve error handling in the WebSocket handler
- Remove hardcoded endpoint in `cloak attach` (e.g. ws://localhost:8080)
- Find out if there's a well known protocol for tty over ws we could use instead of the homemade one I came up with
- Add missing arguments in service start (e.g. cache mounts, etc)
- Change the API to support multiple processes per container
- Q: should we support regular (non streaming) `std{in,out,err}`?
  - I think it would make sense to programmatically start one-off containers
- Tests

Next (out of scope for this PR):

- Container to container networking
  - e.g. Allow the pipeline to somehow communicate with services
- Host to container (and container to host?) networking
  - e.g. Allow the end user to access a service through `localhost`

### CODE REVIEW

**Comment by aluzzardi** [comment]
Moved to https://github.com/dagger/dagger/pull/3124

**Comment by aluzzardi** [comment]
Merging as is to avoid maintaining this PR, however this needs a lot of rework before being released:

- Convert to New Core API
- Restructure to be multi-process (just like buildkit)
- Support non-interactive mode (e.g. for launching a db etc, we don't want tty streaming etc)
- cloak attach is hardcoded to localhost
- Tests

If we don't get it to before preview, we should disable this.

/cc @sipsma @vito

**Comment by vito** [comment]
@dolanor I'd wager the latest discussion in https://github.com/dagger/dagger/issues/4080 is more relevant at this point, but yeah this is the most recent actually-pushed code for it (besides #4025 which is tangentially related).

**Comment by helderco** [comment]
Lobbying to continue with the debugger in:
- https://github.com/dagger/dagger/issues/4463

**Pull request closed without merging**
