### PR TITLE
sdk: python: Refactor client factory

### PR DESCRIPTION
**Pull request by helderco**
## What

- Async only support[^1]
- Flattened directory structure a bit
- Refactored client factory to be modular
  - Allows more connectors to be added later (unix, stdio...), as well as provisioners (docker run, fork exec...)
- Use `with dagger.Connection()` as single entrypoint for getting the codegen’d client
  - Previously `dagger.Client()` could be used without `dagger.Engine()`
  - Previous `dagger.Client()` was the dynamic query builder, not the codegen one
- Return scalars wrapped in a `Result` object to make it a bit more explicit when queries execute
  - See #3555
  - Bonus of being easier to test
  - Not sure about result, interested in feedback[^2]
- Codegen improvements

## How

Look at the `examples/python/simple-client` example (notice type hint):

say-wat

## Next

I’ll amend with these or publish follow ups depending on review.

- Document getting started or similar
- Battery of tests to flush out bugs
- Provision the Engine[^3]

[^1]: For the sake of expediency. It’s a bit of a pain to support both sync and async. NodeJS comes with an event loop built-in but in Python it’s optional. It’s easy to just spin an event loop in a sync environment to run async dagger, but not the inverse. If we start with only sync support then you can’t run tasks concurrently and you can’t use dagger in an async environment otherwise it’ll block your event loop. I’m questioning more and more if we even need to support sync at all but in any case I think there’s other priorities.

[^2]: The coroutine itself could act as the "rule of thumb" but when we support sync it won't be there. Besides, I can put more stuff into the `Result` object like the query that was executed, the entire response from the server, and the query builder object that produced them.

[^3]: Notice that this PR disables provisioning. There’s still decisions to be made on how to do this in the next no-Go SDK releases.

Signed-off-by: Helder Correia

### CODE REVIEW

**Review by samalba — APPROVED** [review]

**Comment by aluzzardi** [comment]
Looks great -- haven't dug deep into the code but let's go ahead and merge as is.

One question: why `dagger.Connection()` instead of `dagger.Connect` (like in the Go SDK)?

**Comment by samalba** [comment]
I'll merge this for now, it's easier to have the `main` branch up to date on the client to run some tests. I agree with Andrea on the consistency with the Go SDK, we can open a follow-up PR to address it if Helder agrees with this as well.

**Comment by helderco** [comment]
> One question: why `dagger.Connection()` instead of `dagger.Connect` (like in the Go SDK)?

I was wandering when this would come up 🙂

It's because of the context manager syntax. "With connection" makes more grammatical sense than "with connect".

Let's break it apart to further understand:

```python
conn = dagger.Connection()  # instantiating an object, not really doing anything
with conn as client:        # things happen only on "with" (provision, connect, etc)
    ...
```

**Comment by gerhard** [comment]
Context was just right. Visuals helped a lot. I wish everyone's PRs read like this. Great job @helderco!

**Pull request merged**
