### PR TITLE
ci: invoke dagger directly through its GitHub Action

### PR DESCRIPTION
**Pull request by crazy-max**
follow-up https://github.com/dagger/dagger-for-github/pull/56#issuecomment-1111730526

cc @sipsma 

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Comment by crazy-max** [comment]
Also following steps doesn't seem necessary to me: https://github.com/dagger/dagger/blob/2c195bcac4e133e2ed7396b3b73a0003e6f51eb9/.github/workflows/dagger-ci.yml#L61-L71

```yaml
      - name: Sets env vars on push to main
        run: |
          echo "DAGGER_CACHE_TO=type=gha,mode=max,scope=${{env.DAGGER_CACHE_BASE}}-main" >> $GITHUB_ENV
          echo "DAGGER_CACHE_FROM=type=gha,scope=${{env.DAGGER_CACHE_BASE}}-main" >> $GITHUB_ENV
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Sets env vars on pull request
        run: |
          echo "DAGGER_CACHE_TO=type=gha,mode=max,scope=${{env.DAGGER_CACHE_BASE}}-${{github.event.number}}" >> $GITHUB_ENV
          echo "DAGGER_CACHE_FROM=type=gha,scope=${{env.DAGGER_CACHE_BASE}}-main type=gha,scope=${{env.DAGGER_CACHE_BASE}}-${{github.event.number}}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'pull_request' }}
```

Cache access restriction across PR/branches is automatically handled by GitHub so you could directly use:

```yaml
      - name: Build
        uses: dagger/dagger-for-github@v2
        with:
          cmds: |
            do build
        env:
          DAGGER_LOG_LEVEL: "debug"
          DAGGER_CACHE_FROM: "type=gha,scope=dagger-ci-build"
          DAGGER_CACHE_TO: "type=gha,scope=dagger-ci-build,mode=max"
```

More info: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

**Comment by sipsma** [comment]
@crazy-max Awesome, thanks, had no idea about the difference between `run` and `uses`. 

For the steps that setup the different `DAGGER_CACHE_TO` env vars, the problem we were trying to address there was that Buildkit cache manifests overwrite each other. The goal was to be able to import cache from both our main branch and the PR specific cache. Are you saying that would work already? From what I could tell that wouldn't work as is, but I was going off reading GHA docs + the buildkit code rather than trying it, so wouldn't be surprised if I was wrong.

**Comment by crazy-max** [comment]
> For the steps that setup the different `DAGGER_CACHE_TO` env vars, the problem we were trying to address there was that Buildkit cache manifests overwrite each other. The goal was to be able to import cache from both our main branch and the PR specific cache. Are you saying that would work already? From what I could tell that wouldn't work as is, but I was going off reading GHA docs + the buildkit code rather than trying it, so wouldn't be surprised if I was wrong.

Yes indeed. I think it will work only on first trigger of the PR and subsequent builds will overwrite it. Didn't try it myself though but worth to check that.

**Comment by aluzzardi** [comment]
Thank you @crazy-max!

I don't think it's a problem right now but just flagging this: this essentially means that `install-only` won't honor caching (or at least, subsequent `run` steps using it won't work).

`cmds` is a little bit limited in what one can do compared to `install-only` (e.g. `curl $(dagger do deploy --output-format json | jq -r .url)`)

If I understand what you're saying in https://github.com/dagger/dagger-for-github/pull/56#issuecomment-1111730526, exposing `ACTION_` from an action to subsequent runs is not necessarily a best practice (huge hack), right?

Maybe long term what we'll do is expose the outputs to the action itself so there's never a need to do an `install-only`

> Cache access restriction across PR/branches is automatically handled by GitHub so you could directly use:

That's definitely worth exploring, thank you!

**Review by aluzzardi — APPROVED** [review]

**Comment by TomChv** [comment]
@crazy-max Can you rebase your PR so we can merge it as soon as possible?

**Pull request merged**
