### PR TITLE
Python: restructure internal packages and modules

### LINKED ISSUE #4685: Python: `dagger.api.gen` should be just `dagger` in reference docs
https://discord.com/channels/707636530424053791/1037455051821682718/1080836880356102265

cc @vikram-dagger @helderco

### LINKED ISSUE #4702: Python: `path` and `location` should be optional in a `QueryError`
From [Error Result Format](http://spec.graphql.org/draft):

> **If an error can be associated to a particular point in the requested GraphQL document**, it should **contain an entry with the key `locations`** with a list of locations, where each location is a map with the keys `line` and `column`, both positive numbers starting from `1` which describe the beginning of an associated syntax element.
>
> **If an error can be associated to a particular field in the GraphQL result**, it must contain an **entry with the key `path`** that details the path of the response field which experienced the error. This **allows clients to identify whether a `null` result is intentional or caused by a runtime error**.

_Emphasis mine._

### LINKED ISSUE #4703: Python: Add custom exceptions to reference documentation
Section "Errors" with custom exceptions added in #3805, maybe including example code.

### LINKED ISSUE #4704: Python: Update reference docs
```[tasklist]
### Tasks
- [ ] #4703
- [ ] #4685
- [x] Autodoc from `__init__`?
- [ ] Add link to Conda package
- [ ] Expose (public) inherited members like `with_`
```

### PR DESCRIPTION
**Pull request by helderco**
## What?

This is a restructure of internal packages and modules in the Python SDK, mainly to rename many to private, and secondly to improve organization. This makes it **clearer** that they're not part of the **"public API" of the library**.

## Reference docs

Additionally, this also updates the reference docs with a few long standing issues.

Closes #4704
Closes #4685
Closes #4703
Closes #4702

## Compatibility

This doesn't change anything that was considered public API of the library (imported in `__init__.py`, present in reference docs), but it'll likely break users who are importing internal modules. The change makes it clearer what is considered internal due to the leading `_` (underscore) in module names.

Example:
```diff
-from dagger.engine.conn import Engine
+from dagger._engine.conn import Engine
```

Some users may have been misled by the imports in the reference docs (before PR):

Screenshot 2023-08-02 at 18 19 50

The full path is now `dagger.client.gen.Container`, however we've always advised towards simply `dagger.Container`. The reference documentation has been updated to reflect this and hopefully avoid confusion (with this PR):

Screenshot 2023-08-02 at 18 20 03

- **Before:** https://dagger-io.readthedocs.io/en/sdk-python-v0.6.4/api.html#dagger.api.gen.Container
- **After:** https://dagger-io--5558.org.readthedocs.build/en/5558/client.html#dagger.Container

### CODE REVIEW

**Review by gerhard — COMMENTED** [review]
I went through all the files, the changes look good to me.

Apart from the 2 failing checks, I am wondering how can I use a local version of this package to try running a few examples. I was going to start with cowsay, then throw in a few twists and check if everything works as expected.

This is how far I was able to get:

```python
import sys
sys.path.append('./src')

import anyio
import dagger


async def main(args: list[str]):
    async with dagger.Connection() as client:
        # build container with cowsay entrypoint
        ctr = (
            client.container()
            .from_("python:alpine")
            .with_exec(["pip", "install", "cowsay"])
            .with_entrypoint(["cowsay"])
        )

        # run cowsay with requested message
        result = await ctr.with_exec(args).stdout()

    print(result)


anyio.run(main, sys.argv[1:])
```

And here is the output:

```console
> python main.py "foo"
Traceback (most recent call last):
  File "/Users/gerhard/github.com/dagger/dagger/sdk/python/main.py", line 24, in <module>
    anyio.run(main, sys.argv[1:])
  File "/usr/local/lib/python3.11/site-packages/anyio/_core/_eventloop.py", line 68, in run
    return asynclib.run(func, *args, **backend_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 204, in run
    return native_run(wrapper(), debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 199, in wrapper
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/Users/gerhard/github.com/dagger/dagger/sdk/python/main.py", line 9, in main
    async with dagger.Connection() as client:
  File "/usr/local/lib/python3.11/site-packages/dagger/_connection.py", line 75, in __aenter__
    if not await client.check_version_compatibility(CLI_VERSION) and (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagger/client/_guards.py", line 129, in async_wrapper
    return await bear(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(dagger.client.gen.Client.check_version_compatibility) at 0x11055e200>", line 31, in check_version_compatibility
  File "/usr/local/lib/python3.11/site-packages/dagger/client/gen.py", line 2822, in check_version_compatibility
    return await _ctx.execute(bool)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagger/client/_core.py", line 168, in execute
    query = self.query()
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagger/client/_core.py", line 156, in query
    return dsl_gql(DSLQuery(self.build()))
                            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagger/client/_core.py", line 153, in build
    return root.to_dsl(self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagger/client/_core.py", line 71, in to_dsl
    field_ = getattr(type_, self.name)(**self.args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gql/dsl.py", line 645, in __getattr__
    raise AttributeError(
AttributeError: Field checkVersionCompatibility does not exist in type Query.
⠇ Running pipelines%
```

I will try running this against a dev Engine.

**Comment by helderco** [comment]
Not the first time I assigned instead of requesting review 😅

**Comment by gerhard** [comment]
It's been a long week, I know 💪

**Comment by helderco** [comment]
@gerhard failed provision tests are due to path to `_version.py` having changed which triggered the provisioning tests with usually only run on version bump or merge to main. So it's not running the dev engine here and is missing an API field (version compatibility check).

The provision tests are too expensive to run on every PR, they're run less often but still early enough to catch something so we can fix before release. Which means, the simplest thing here is to just merge with these provision failures.

**Pull request merged**
