### PR TITLE
Merge the concepts of "plan" and "project"

### LINKED ISSUE #2462: Project, Plan: keep one
## Problem

Dagger defines two slightly different concepts: "project" and "plan". This made sense in 0.1 with `dagger up`, but in 0.2 with `dagger do`, it is less needed and adds unnecessary complexity to the developer experience.

## Solution

Merge the two concepts, and keep only word. I propose to keep the word "project" because it is more familiar to developers.

### How it works today

* A *project* is a shared context for developping and running Dagger actions. Often it maps to a developer's git repository, but that is not mandatory. Dagger uses the project to 1) load CUE files, and 2) store information about CUE dependencies.
* A *plan* is a directory within a project which can be loaded. Often the project directory is a valid plan (the project's "root plan"), but any sub-directory could also be a plan.

### What changed?

In 0.2, we deprecated `dagger up` and introduced `dagger do`. This made a big difference:

* With `dagger up`, users had no choice but to run an entire configuration. So to run different workflows (deploy to staging, run integration tests..) you had to maintain different plans.
* But now with `dagger do`, users only run one action at a time. So all workflows can co-exist in the same plan. Why bother maintaining different plans when users will need to select an action anyway?

In other words, with Dagger 0.2 a first-class concept of "plan" is unnecessary

### What about power users?

Power users can still use the same CUE layered loading feature. It will all work exactly the same, we just won't use the name "plan". Instead we'll say "Dagger supports all CUE features, including layered loading. If you load the project from one of its subdirectories, all files in the same CUE package will be layered together following the loading CUE standard. See [advanced CUE feature: layered loading] to learn more).

### PR DESCRIPTION
**Pull request by shykes**
This basically renames "plan" to "project" everywhere.

Fixes #2462 

NOTE: this is work in progress. Please consider helping me converting all the remaining docs :)

### CODE REVIEW

**Comment by shykes** [comment]
That would be nice. Also if there's a way to move it up in priority for everyone (not just employees who are on maintainer rotation) that would be helpful too.

**Comment by mircubed** [comment]
@helderco @grouville if possible, this would be a good one to pick up during maintainer duty this week. 

> That would be nice. Also if there's a way to move it up in priority for everyone (not just employees who are on maintainer rotation) that would be helpful too.

Yeah, I have some ideas around that, so I shared them with @gerhard. We don't have priorities for PRs yet, but we could make it happen with a public GitHub board.

**Comment by shykes** [comment]
Don’t need priorities for PRs, just the underlying issues :) In this case #2462

**Comment by mircubed** [comment]
opening since we still need to do this. @gerhard to review for maintainer rotation

**Comment by mircubed** [comment]
Talked to Solomon and we can close this

**Pull request closed without merging**
