### PR TITLE
Improve releasing during v0.11.3

### PR DESCRIPTION
**Pull request by jedevc**
Signed-off-by: Justin Chadwell <me@jedevc.com>

### CODE REVIEW

**Comment by jedevc** [comment]
Due to https://github.com/dagger/dagger/issues/7320, we can't merge this as is - we need to either: run the next release with 0.11.2 (instead of 0.11.3), or modify our `Publish`/`TestPublish` functions to now take a list of scalars.

I think it's probably worth adapting to the regression and temporarily disabling the list of scalars for the time being.

**Comment by jedevc** [comment]
> I am most interested in checking if the panic in #7192 was addressed in `v0.11.3`

Yup! I guess we just have to wait to see if it happens :eyes:

> How difficult would it be to adapt to the regression?

Just pushed a commit for it, we can revert it once v0.11.4 releases.

> I was also wondering how did the Helm instructions work in practice.

Excellently :tada: I literally just copy-pasted them, works perfectly :heart:

**Comment by gerhard** [comment]
Before we merge this, I would like to add some more details for the dagger-for-github release so that we have a quick fix for what @jpadams was mentioning earlier today. Taking that action item on as I review & merge this.

**Review by gerhard — APPROVED** [review]
This now looks good to me!

OK to merge when all checks pass 👍 🚀

**Pull request merged**
