### PR TITLE
sdk(dotnet): Use same Apache 2.0 license as all other SDKs

### PR DESCRIPTION
**Pull request by nabsul**
Engine & CLI use the same Apache 2.0 license.

### CODE REVIEW

**Comment by nabsul** [comment]
https://github.com/dagger/dagger/pull/5778

**Comment by nabsul** [comment]
@gerhard I'm not sure if I did this right or it's messed up. Lots of commits after rebasing and trying to amend :-)

**Comment by nabsul** [comment]
@gerhard Nevermind, I think I cleaned everything up. I made the mistake of trying to do things in the VSCode. CLI was much more predictable :-D

**Review by gerhard — APPROVED** [review]
Looks good! Thank you @nabsul 💪

**Pull request merged**
