### PR TITLE
universe: Set bash.#Run entrypoint to `/bin/bash`

### LINKED ISSUE #2285: 🐞 bash.#Run does not work with a container image with an `entrypoint`
### What is the issue?

When there is an entrypoint set on a base image, `bash.#Run` ends up with invalid arguments (bash cmd and arguments are appended to the existing entrypoint).

Instead it should always set an entrypoint to `/bin/bash` to work with all kind of base images.

### Log output

_No response_

### Steps to reproduce

_No response_

### Dagger version

dagger 0.2.7 (18c19174) darwin/arm64

### OS version

macOS 12.13.1

### PR DESCRIPTION
**Pull request by TomChv**
Resolves #2285

Signed-off-by: Vasek - Tom C <tom.chauveau@epitech.eu>

### CODE REVIEW

**Review by shykes — CHANGES_REQUESTED** [review]
What is the rationale for this? I can think of a few downsides, but no obvious upsides.

**Comment by TomChv** [comment]
The issue #2285 created by @samalba explain everything :D 

Basically, `bash.#Run` is used to run bash script so when you use an image that only have an entrypoint, you cannot use `bash.#Run`.

So I'm not sure there is a downside, you should use `bash.#Run` to run bash, if you want to use default entrypoint set by the image, then use `docker.#Run`.

**Comment by shykes** [comment]
Ok, I understand.

It appears that we have do exactly what I was hoping we would avoid: the Docker image entrypoint hack has infected the Dagger API and now we will never be able to get rid of it. I don’t have a good solution to propose but this is definitely a bad thing for our DX.

**Review by shykes — APPROVED** [review]
LGTM - Having to deal with docker image entrypoints everywhere is a very bad thing for our DX… We failed to contain the hack. But since we’re already in this situation, we might as well merge this.

My comment on downsides was based on a misunderstanding. I thought you were setting the command to execute the script itself - requiring executable permissions + a shebang. I had missed the entrypoint part (because entrypoints are confusing and a bad API which we are now stuck with. Did I mention I’m sad about that? 😉)

**Comment by TomChv** [comment]
> It appears that we have done exactly what I was hoping we would avoid: the Docker image entrypoint hack has infected the Dagger API

Yeah it's really painful to deal with it but we can now use `bash.#Run` to override it so it should be ok?

**Comment by shykes** [comment]
FYI this breaks flags. I had to revert it in my fork to get yarn to work. This needs to be either fixed or reverted.

cc @aluzzardi @helderco

**Pull request merged**
