### PR TITLE
map |> intersperse -> map_intersperse

### PR DESCRIPTION
**Pull request by bradhanks**

### CODE REVIEW

**Review by wingyplus — DISMISSED** [review]
❤️

**Comment by wingyplus** [comment]
@bradhanks thank you for your contribution. To make it merge, you need to sign off the commit. See the details in https://github.com/dagger/dagger/blob/main/CONTRIBUTING.md#dco for the information.

**Comment by wingyplus** [comment]
@bradhanks please help rebase the branch. 🙂

**Comment by bradhanks** [comment]
Helping child with math but I will right after

**Comment by bradhanks** [comment]
> @bradhanks please help rebase the branch. 🙂

done :)

**Review by wingyplus — APPROVED** [review]

**Pull request merged**
