### PR TITLE
Bump internal tooling to v0.9.8

### PR DESCRIPTION
**Pull request by gerhard**

### CODE REVIEW

**Comment by gerhard** [comment]
Seems to be working finer on Linux so far, when everything is local. Checking if this works fine on macOS if Dagger Engine is local, rather than running on a remote Docker.

**Comment by sipsma** [comment]
@gerhard just tried this too (`gh pr checkout 6562` and `./hack/make engine:testimportant`) and it is working direct on macos for me (with docker on the same machine), just FYI.

**Comment by gerhard** [comment]
Yes, I am seeing the same thing. All working fine when everything is locally, both on macOS & Linux.

**Comment by gerhard** [comment]
First run failed on macOS too:
image

Re-running to check if this is a flake or genuine issue.

**Comment by gerhard** [comment]
I think this was the case in the past, but just realised that even though nothing changes, each test run takes just as long as the first, meaning that there is no caching between runs. Leaving a note for self here - this was surprising!

**Comment by gerhard** [comment]
After the `30m` timeout bump, hit this on Linux:

image

Clearing all local volumes and starting again with a clean `v0.9.8` Engine.

**Comment by gerhard** [comment]
`./hack/make engine:test` succeeded after `15m 31s` on macOS:

image

**Comment by gerhard** [comment]
I ran a simpler pipeline with `0.9.8` Go SDK & a remote Engine & everything worked as expected. All good to move on.

**Comment by sipsma** [comment]
FWIW I ran locally on Linux (vm on my m1 mac) and while I did also need the 30m timeout it passed.

**Review by sipsma — APPROVED** [review]

**Review by helderco — APPROVED** [review]

**Comment by gerhard** [comment]
Thank you for confirming @sipsma . There must be something different about my Linux setup then. Don't think that running NixOS Unstable is helping. Will switch back to `23.11` and see if that improves things.

**Pull request merged**
