### PR TITLE
feat: bump cuemod

### PR DESCRIPTION
**Pull request by morlay**
spike for #2163

Now will automate to fetch dependencies if not exists, like go did.

### CODE REVIEW

**Comment by aluzzardi** [comment]
Thanks @morlay!

`dagger` is currently broken with the latest version of CUE -- @jlongtine is looking into that, but for now we're stuck with an older version

**Comment by helderco** [comment]
> `dagger` is currently broken with the latest version of CUE -- @jlongtine is looking into that, but for now we're stuck with an older version

This PR isn't about upgrading CUE, it's for using @morlay's _cuemod_ tool for managing package dependencies. So this has to do with:
- #2163

**Comment by TomChv** [comment]
@morlay What should we do with the PR? Do you plan to continue it or should we close it?

**Comment by morlay** [comment]
added `dagger get`, totally same as `go get`

```shell
# download dep
$ dagger get ./...

# upgrade to latest
$ dagger get -u ./...
```

**Comment by morlay** [comment]
go 1.18 required because internal code of go std is from go 1.18

**Comment by morlay** [comment]
@TomChv Not sure.

My tool cuemod already support most features list here https://github.com/dagger/dagger/issues/2163
If dagger team decide to implement  by your self, could just close this PR directly.

**Comment by samalba** [comment]
@helderco Assigning to you for review, to either close or approve.

**Comment by morlay** [comment]
cuemod v0.5.0 

added embed stdlib support.
Now no need to added `dagger.io` and `universe.dagger.io` in replace

**Comment by helderco** [comment]
Hey @morlay, I'm sorry this took so long. There were other priorities, downtime and internal discussions delaying this.

I'm closing for the same reasons as https://github.com/dagger/dagger/pull/2310#issuecomment-1151850224, essentially. Specifically, the package management stuff is quite a bit in flux especially now.

I tried drafting a plan for following CUE's proposal closely in small steps such that when the CUE team publishes their tool, we could just replace our stop-gap solution for theirs. There's a few things in *cuemod* not following that spec that would need fixing.

On the other hand, by forking Go's internals you're able to take advantage of a lot of features from Go modules that we have in our "whishlist", since it's also CUE's proposal to mirror Go modules (with some exceptions). But there's also the maintainability aspect of it to consider, licensing issues, migrations, etc.

The main concern though is that it's just a big dependency for us to have without a stronger comunity behind using it. We feel it's more sensible for us to accept **incremental contributions to the [plan we have](https://github.com/dagger/dagger/issues/2163), including to the plan itself**, and have more control on the outcome. And as always, discussing design before implementation.

As I said before, this plan is very much in flux right now. For one, we'll be loosening the requirement to match CUE's proposal so closely in favor of improving DX as much as possible. On another hand, we're **exploring** the possibility of offloading **some** of our CUE complexity to other languages (SDKs). This means you'd be able to write an action's implementation in Typescript (for example), in which case you'd use *npm* to manage your dependencies.

It also means you still need a CUE package manager if you want to write actions with the CUE SDK, so the CUE package manager is no longer everything, but just one in several.

I'd love if *cuemod* could fill the gap for CUE users until it gets replaced by CUE's official tool. Please keep improving the tool and gather user support behind it. You should already be able to use it with dagger for third-party CUE packages. This is what dagger actually needs:

- `dagger project init` just needs to make sure there's a `cue.mod` because that's what we use to detect the root of the "dagger project"
- `dagger project update` can be used just to install `dagger.io` and `universe.dagger.io` modules into `cue.mod/pkg`

For third party packages, you can use any system you want that puts those packages in `cue.mod/pkg`, including *cuemod*. There's even an issue for handling our [built-in modules as external packages](https://github.com/dagger/dagger/issues/2506) so there's that.

Thanks for your effort contributing to dagger, we do appreciate it. Again, we're currently re-thinking our plan for package management in light of other initiatives we're starting, so for now, we need to have full control over `dagger project` to move quickly.

**Pull request closed without merging**
