### PR TITLE
docs: fix lint errors on docs sample code

### PR DESCRIPTION
**Pull request by sipsma**
There's linting errors on main right now, just including the generated code for these so we can lint them (also patched one legit linter complaint about extra whitespace in one of the files)

### CODE REVIEW

**Comment by sipsma** [comment]
Hm I guess this doesn't show up in PRs and only on `main` due to the fact that we ignore `docs/**` for the engine lint workflow *only on PRs*: https://github.com/sipsma/dagger/blob/30925fc1006ca1cacafe5424c381063cc585feab/.github/workflows/engine-and-cli.yml#L13-L13

This leads to an inconsistency in that in PRs where you *don't* change docs then you get lint errors about the docs, but if you *only* changes docs then you don't see them...

If possible, I'm inclined to just run the linting on `docs/**` no matter what (while still skipping the engine tests if only `docs` was modified). I'll push that as a separate commit, but let me know if there's some other decision we made around all this that I'm not aware of. I think it's valuable to lint these snippets if possible, so it would be my preference to keep that. cc @vikram-dagger

**Review by vito — APPROVED** [review]
Well this nearly gave me a heart attack: 
image

(would be neat if GitHub distinguished generated lines of code from these stats :sweat_smile:)

Agree with linting `docs/`, seems like the much lesser evil to having bugs in our sample code.

**Comment by sipsma** [comment]
> Well this nearly gave me a heart attack:

Yes please review all 70k lines of `dagger.gen.go`s too plz 🙏

> (would be neat if GitHub distinguished generated lines of code from these stats 😅)

💯

**Comment by vikram-dagger** [comment]
I'm not sure if related but see https://github.com/dagger/dagger/pull/6649 which turned off some tests

**Pull request merged**
