### PR TITLE
feature: install completion script for bash, zsh and fish

### PR DESCRIPTION
**Pull request by dolanor**
For now, it works on debian derived system.

I need people to test on Mac OS to tell me if that works as well.

<a href="https://gitpod.io/#https://github.com/dagger/dagger/pull/2950"></a>

### CODE REVIEW

**Comment by grouville** [comment]
@dolanor, I get breaking errors when running `./install`

```
./install.sh debug downloading files into /var/folders/y6/3xb6hfpn7kv7vf6n9j3bq4c40000gn/T/tmp.tAWIYEsA
./install.sh debug http_download https://dagger-io.s3.amazonaws.com/dagger/releases/0.2.30/dagger_v0.2.30_darwin_arm64.tar.gz
./install.sh debug http_download https://dagger-io.s3.amazonaws.com/dagger/releases/0.2.30/checksums.txt
./install.sh: line 298: /usr/share/bash-completion/completions/dagger: No such file or directory
./install.sh: line 299: /usr/share/zsh/vendor-completions/_dagger: No such file or directory
./install.sh: line 300: /usr/share/fish/vendor_completions.d/dagger.fish: No such file or directory
```

**Review by grouville — CHANGES_REQUESTED** [review]
We can sync-up today to fix the mac install issue

**Comment by crjm** [comment]
It's not working correctly for me on Ubuntu 20.04 either.
Maybe I'm doing something wrong:
* Checkout this branch
* `sudo ./install.sh` in `/dagger` (I'm not able to write to /usr/share... without `sudo`)

**Comment by crjm** [comment]
It's working for me on Ubuntu 20.04
```
~ via nodejs v16.16.0 
> dagger 
do                                  project  (Manage a Dagger project)
help     (Help about any command)   version  (Print dagger version)
```

**Comment by dolanor** [comment]
> @dolanor, I get breaking errors when running `./install`
> 
> ```
> ./install.sh debug downloading files into /var/folders/y6/3xb6hfpn7kv7vf6n9j3bq4c40000gn/T/tmp.tAWIYEsA
> ./install.sh debug http_download https://dagger-io.s3.amazonaws.com/dagger/releases/0.2.30/dagger_v0.2.30_darwin_arm64.tar.gz
> ./install.sh debug http_download https://dagger-io.s3.amazonaws.com/dagger/releases/0.2.30/checksums.txt
> ./install.sh: line 298: /usr/share/bash-completion/completions/dagger: No such file or directory
> ./install.sh: line 299: /usr/share/zsh/vendor-completions/_dagger: No such file or directory
> ./install.sh: line 300: /usr/share/fish/vendor_completions.d/dagger.fish: No such file or directory
> ```

**Comment by gerhard** [comment]
While looking at this, I have noticed that this branch was created directly on the `dagger/dagger` repo. This is no biggie for this pull request, but going forward it would be great if you could submit a PR from your `dagger` fork @dolanor. Leaving this here: https://docs.dagger.io/1227/contributing#github-workflow

I've hit my time-box today, but this PR is the first one on my list tomorrow.

**Comment by gerhard** [comment]
This is related: https://github.com/dagger/dagger/issues/1159#issuecomment-1217108101

FTW, it's worth looking at how the bottled formula is doing it. This is the implementation for the last released version, v0.2.30: https://github.com/dagger-ci/homebrew-core/blob/fa5241e558b7467841a9e573dd1eb4efb35c0ff2/Formula/dagger.rb

**Comment by dolanor** [comment]
> FTW, it's worth looking at how the bottled formula is doing it. This is the implementation for the last released version, v0.2.30: https://github.com/dagger-ci/homebrew-core/blob/fa5241e558b7467841a9e573dd1eb4efb35c0ff2/Formula/dagger.rb
I have looked at it. The completion save abstraction from brew is great, in 1 line, it's done.
Unfortunately, I haven't found one as easy in shell, yet. Each distribution, each OS, each shell setup might have set their FS a different way, which makes it very work intensive to save the correct file in the correct directory. If anybody have some pointers, I'm taking it.

**Comment by crjm** [comment]
I think I might have found something for bash.
From the [bash-completions README](https://github.com/scop/bash-completion/blob/master/README.md#faq).
> Q. I author/maintain package X and would like to maintain my own completion code for this package. Where should I put it to be sure that interactive bash shells will find it and source it?
>
> A. Install it in one of the directories pointed to by bash-completion's pkgconfig file variables. There are two alternatives:
>
>    The recommended directory is completionsdir, which you can get with `pkg-config --variable=completionsdir bash-completion`

For me, this command works:
image

Maybe we can use it to see where the bash-completion directory is located on each distro.

**Comment by dolanor** [comment]
> > Q. I author/maintain package X and would like to maintain my own completion code for this package. Where should I put it to be sure that interactive bash shells will find it and source it?
> > A. Install it in one of the directories pointed to by bash-completion's pkgconfig file variables. There are two alternatives:
> > The recommended directory is completionsdir, which you can get with `pkg-config --variable=completionsdir bash-completion`

Good one, I didn't know we could use this for that.
Doesn't work on mac os by default, though, so then you need homebrew, so then you already have brew and you can install dagger this way.
And the fact that it doesn't work on CentOS or fedora kills the point of it.

Anyway, I'm aiming for just document how to get the completion, but everyone need to check their distribution of their shell to know where to save (and with what name) in the completionsdir.
Discovering which shell is used, or installed and where the distribution people decided to put the files is still a big PITA. Even if XDG helped veer in the right direction, it doesn't solve everything, so document it is.

**Comment by gerhard** [comment]
Does not work for me on macOS 12.5 with zsh 5.8.1:

image

Attempting a fix now.

**Comment by gerhard** [comment]
WDYT @dolanor?

image

FTR, there are a bunch of steps that we need to manually perform after this gets merged. #1819 has all the details. I am thinking of adding the steps as comments to the top of `install.sh` before this gets merged.

**Comment by dolanor** [comment]
I updated the help to use the personal bash completion's dir without polluting the `.bash_profile`.

**Comment by dolanor** [comment]
I updated the help to use the personal bash completion's dir without polluting the `.bash_profile`.
I don't think the `eval` is necessary at each bash invocation.

**Review by aluzzardi — APPROVED** [review]

**Comment by aluzzardi** [comment]
LGTM

@gerhard Can you upload install.sh after merge?

**Comment by gerhard** [comment]
image

💡 https://github.com/dagger/dagger/pull/1819#issuecomment-1078511779

image

**Pull request merged**
