### PR TITLE
Node.js: Fix returning lists of objects

### PR DESCRIPTION
**Pull request by TomChv**
Add more common functions in Go and Node generator
Generate list of object in Node template
Update test with new generation
Regenerate Node client

Resolves: https://github.com/dagger/dagger/issues/3457

### CODE REVIEW

**Comment by helderco** [comment]
@gerhard I removed this from the milestone because it's already there with the linked issue:
- https://github.com/dagger/dagger/issues/3457

**Review by helderco — APPROVED** [review]
I'm going to trust the test 🙂

**Comment by helderco** [comment]
Not sure why the DCO has been failing sometimes.

**Comment by gerhard** [comment]
@helderco we seem to have a mix of issues & PRs in the milestone. Since there are more PRs than issues, I re-added this to the milestone so that we can stay consistent: PRs only.

Going forward, I'm all for sticking with issues instead. Do you have a preference @helderco?

**Comment by helderco** [comment]
For a milestone issues make more sense since they indicate what's planned to do, but sometimes we have PRs without an issue or PRs that are part of an issue but don't close it. So I don't see how we can stick to one or another. Imagine we're one months out. It'll be mostly issues then. But now that we're close to the finish line, it's a different story.

**Pull request merged**
