### PR TITLE
docs: fix typo in what-is-cue docs 

### PR DESCRIPTION
**Pull request by fldu**
Hey,

There were a small typo in this page.

Cheers

### CODE REVIEW

**Review by jpadams — APPROVED** [review]
Thank you for this! Great catch!

**Review by TomChv — APPROVED** [review]

**Comment by TomChv** [comment]
Thanks for your contribution :)
Can you rebase your PR and update your commit's prefix to `docs`, to be ok with our contribution [guidelines](https://docs.dagger.io/1227/contributing#commit-messages).

We can merge your PR once it's done :rocket:

**Comment by grouville** [comment]
@fldu, I took the liberty to rebase your PR on latest main + fix the commit name + fix the commit message. It's quite important for us, in order to have clean changelog 😇

**Review by grouville — COMMENTED** [review]
LGTM

**Comment by fldu** [comment]
@grouville thanks a lot. I guess I used the wrong alias in my terminal or something

**Pull request merged**
