### PR TITLE
Import Java SDK as Experimental

### PR DESCRIPTION
**Pull request by gerhard**
This imports https://github.com/jcsirot/dagger-java-sdk under `sdk/java` as an **experimental** SDK.

## @gerhard action items (part of this PR)
- [x] Open PR with https://github.com/jcsirot/dagger-java-sdk history import
	- [x] Capture commands used for history import
```console
git remote add dagger-sdk-java https://github.com/jcsirot/dagger-java-sdk
git fetch dagger-sdk-java --no-tags
git checkout -b sdk/java dagger-sdk-java/main
mkdir -p sdk/java
git ls-tree -z --name-only HEAD | xargs -0 -I {} git mv {} sdk/java/
git commit --gpg-sign --signoff

git checkout main
git pull
git checkout -b import-sdk-java

git merge --gpg-sign --signoff --allow-unrelated-histories sdk/java

git push -u fork
```
- [x] Give @jcsirot write permissions to `dagger` repository
- [x] Add @jcsirot to [`CODEOWNERS`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) (`@dagger/sdk-dotnet` group)
- [x] Mention in SDK's README that it is currently experimental
- [x] Review `internal/mage/sdk/java.go`
- [x] Complete https://central.sonatype.org/publish/ for dagger.io
- [x] Ensure we are using Apache 2.0 license, same as all other SDKs
- [ ] Merge PR 🚀

## @jcsirot action items (part of this PR)
- [x] Rename package names `org.chelonix.dagger.*` to `io.dagger.*`
- [x] Move (and rename) GHA workflows from `sdk/java/.github` to `.github/`
  - you may want to add the Java workflow to `internal/mage/sdk`, e.g. https://github.com/dagger/dagger/blob/e454aa6b8ff40bf1502927fcdf1badb6cb4998a7/internal/mage/sdk/elixir.go
- [x] Review & approve the PR

## Follow-ups (outside / after this PR)

- Migrate https://github.com/jcsirot/dagger-java-sdk/pull/10
- Migrate https://github.com/jcsirot/dagger-java-sdk/pull/12
- Add commit to https://github.com/jcsirot/dagger-java-sdk that removes all files except the README
	- Add repo migration notice to `README.md`, e.g. https://github.com/nabsul/DaggerSDK/blob/main/README.md
	- Archive repository in GitHub, e.g. https://github.com/nabsul/DaggerSDK/issues/2

Did I miss anything @jcsirot?

---
[Fixes DEV-2320](https://linear.app/dagger/issue/DEV-2320) cc @shykes @helderco @mircubed @d3rp3tt3

### CODE REVIEW

**Comment by jcsirot** [comment]
@gerhard among the actions which are part of this PR I would also add:
* rename package names `org.chelonix.dagger.*` to `io.dagger.*`

**Comment by gerhard** [comment]
OK! I just added that.

**Comment by gerhard** [comment]
I am stopping for the day, but I intend to pick this one up tomorrow.

**Comment by gerhard** [comment]
Second on my list.

**Comment by gerhard** [comment]
Still on my list.

**Comment by wingyplus** [comment]
@jcsirot Hi, I'm the Elixir maintainer. Just see that Elixir pipeline jobs failed on this PR. This failure has already been solved on the main branch. Rebasing it should solve. 

If you still facing an issue. Feel free to ping me. I can help to take a look to make sure you can get merged when it's ready.

**Comment by jcsirot** [comment]
@wingyplus Thank you. I'm going to rebase on the main branch and monitor the pipelines

**Comment by jcsirot** [comment]
@wingyplus I tried to rebase on main but the process encounters a lot of conflicts. I think this is because a lot of files were moved from the root of the repo to `sdk/java` when @gerhard imported the code from the original SDK repo. Maybe for the moment I could cherry-pick the commits that fixes the issue with the Rust SDK?

@gerhard I also tried to squash the commits in the PR but I also have the same issues with a lot of conflicts, for instance on `README.md` or the files in `.github/` directory. Maybe you acquired some experience with the SDK you previously imported?

**Comment by talios** [comment]
@jcsirot If the branch you're rebasing has just moved wholesale into the sub dir - you _could_ possibly rewrite your local checkout with filter-branch with the `--index-filter` (https://git-scm.com/docs/git-filter-branch) - so you're existing version is now under that path, then return to normal rebasing?

It almost feels similar to what I did when migrating our old subversion repos which I wrote about ages ago on https://www.theoryinpractice.net/post/1350252794/repository-migration-from-subversion-to-git using that and a bit of `awk`.

**Comment by wingyplus** [comment]
> @wingyplus I tried to rebase on main but the process encounters a lot of conflicts. I think this is because a lot of files were moved from the root of the repo to `sdk/java` when @gerhard imported the code from the original SDK repo. Maybe for the moment I could cherry-pick the commits that fixes the issue with the Rust SDK?
> 
> @gerhard I also tried to squash the commits in the PR but I also have the same issues with a lot of conflicts, for instance on `README.md` or the files in `.github/` directory. Maybe you acquired some experience with the SDK you previously imported?

I remember that I face similar issue during move Elixir SDK into Dagger. But at that time, I manually resolve it one-by-one. 😂

**Comment by gerhard** [comment]
I am picking this one up now @jcsirot.

The merge with `main` addressed all conflicts.

I am going over the remaining action items now.

**Comment by gerhard** [comment]
I submitted a JIRA ticket for https://central.sonatype.org/publish/, waiting for https://issues.sonatype.org/browse/OSSRH-94866 to be resolved.

**Comment by gerhard** [comment]
Also finished reviewing `internal/mage/sdk/java.go`, all these work as expected & pass locally:
- `dagger run ./hack/make sdk:java:lint`
- `dagger run ./hack/make sdk:java:test`
- `dagger run ./hack/make sdk:java:generate`

**Comment by gerhard** [comment]
The last thing to check are the GHA worklfows.

**Comment by gerhard** [comment]
All checks are now green, including: https://github.com/dagger/dagger/actions/runs/6125459830?pr=5504
image

There are 2 actions items left @jcsirot before this will be merged:
1. Use Apache 2.0 license in `sdk/java/LICENSE` so that we are consistent (Engine + CLI & all our SDKs use it), e.g. https://github.com/dagger/dagger/blob/main/sdk/elixir/LICENSE
2. Approve the PR

This one has been a long time coming, it will be so amazing to merge this as soon as the above are done @jcsirot. Thank you for sticking with me on this one 💪

**Comment by gerhard** [comment]
https://issues.sonatype.org/browse/OSSRH-94866 has now been solved too.

How do you want us to move ahead with it @jcsirot?

---
FTR:
image

**Comment by gerhard** [comment]
Anything else that I can do @jcsirot to help move this one along?

**Comment by jcsirot** [comment]
@gerhard I'm planning to review everything tonight or tomorrow

**Comment by gerhard** [comment]
If you agree with my last commit @jcsirot:
- edit the commit message & remove this paragraph
- append your `Signed-off-by`
- commit & force push

Today is a great day to merge this @jcsirot 💪

**Comment by jcsirot** [comment]
@gerhard everything LGTM

Should I squash all commits or leave the history as is?

**Comment by gerhard** [comment]
Hey @jcsirot!

First step for you is to make the change that I mentioned in my previous comment.

Second step is to approve the PR via:
image

As you can see above, I cannot approve my own PR.

**Review by jcsirot — APPROVED** [review]
LGTM

**Comment by gerhard** [comment]
Thank you @jcsirot!

Will get this merged as soon as `v0.8.6` is out - mid-release right now.

**Pull request merged**
