### PR TITLE
fix(go): Retract v0.11.7 release

### PR DESCRIPTION
**Pull request by gerhard**
This is a follow-up to:
- https://github.com/dagger/dagger/pull/7631

Fixes:
- https://github.com/dagger/dagger/issues/7630

---
After this is merged:
- [ ] Tag `sdk/go/v0.11.8-rc.1`
- [ ] Ensure that https://pkg.go.dev/dagger.io/dagger@v0.11.8-rc.1 becomes available
- [ ] Ensure that `v0.11.8-rc.1` shows up in https://pkg.go.dev/dagger.io/dagger@v0.11.6?tab=versions
- [ ] Pull this new version in https://github.com/dagger/dagger/pull/7616

### CODE REVIEW

**Review by jedevc — APPROVED** [review]

**Comment by gerhard** [comment]
Stopping here for the day. The checks are still failing due to hangs. Started discussing https://github.com/dagger/dagger/pull/7616#issuecomment-2163612643 as I thought this was related to `v0.11.7`, but it's actually happening on `v0.11.6` since we have not merged that PR yet. This is the best place to follow that conversation https://github.com/dagger/dagger/pull/7616#issuecomment-2163617694

**Comment by gerhard** [comment]
Actually, since this is a known failure and is currently being investigated, we will go ahead with this even though not all checks are green.

**Comment by gerhard** [comment]
[`Publish Go SDK`](https://github.com/dagger/dagger/actions/runs/9487624773/workflow) workflow does not behave as it used to, the tag is not published to the dagger-go-sdk repository anymore:

image

Doing it manually for now, adding an item to the todo list at the top-level of this PR.

cc @jedevc

**Comment by jedevc** [comment]
Ah, I know why this is - I'll investigate tomorrow, the git fetch is incorrect in it's current form in the publish.

**Comment by gerhard** [comment]
Because we tried to fetch `v0.11.8-rc.1` when it was a branch, we got this version in a bad state too:

image

We already know that the only way to fix this is to retract, and resume the whole process again, which we can do for the next release, most likely `v0.11.8`. For now, we are doing this manually since `v0.11.8-rc.2` is exactly the same as `v0.11.8-rc.1`, just with a different tag to fix the above.

**Pull request merged**
