### PR TITLE
feat: add Pulumi up action

### PR DESCRIPTION
**Pull request by rawkode**

### CODE REVIEW

**Review by shykes — APPROVED** [review]
Looks good! I have a few questions (no changes required)

* Have you thought about integration testing? We have testing infrastructure for other packages that require integrations with third-party services. But so far it's only been accessible to Dagger employees. This is a good opportunity to test how to expand that model, so that you can "plug" into universe's testing infra.

* I'm not super familiar with Pulumi best practices, but I'm guessing some operators like to use the saas, while others like to store their state in eg. S3? If I wanted to do the latter, is that supported?

Thanks again for the contribution and for being patient with us as we figure out the model :)

**Comment by marcosnils** [comment]
> * Have you thought about integration testing? We have testing infrastructure for other packages that require integrations with third-party services

Does this action requires integrations tests though? Shouldn't exporting the `pulumi up` plan and comparing that plan with the expected output should be enough? In this particular case I'm not actually sure if it adds value to make the integration test provisioning some sort of infra somewhere since as stated before, we can already validate "exactly" what pulumi's plan will be doing.

**Comment by rawkode** [comment]
> * Have you thought about integration testing? We have testing infrastructure for other packages that require integrations with third-party services. But so far it's only been accessible to Dagger employees. This is a good opportunity to test how to expand that model, so that you can "plug" into universe's testing infra.

I have. I plan to include a simple Pulumi program that generates some random values and assert against their creation. We'll avoid speaking to any external providers.

> * I'm not super familiar with Pulumi best practices, but I'm guessing some operators like to use the saas, while others like to store their state in eg. S3? If I wanted to do the latter, is that supported?

Yeah, I do plan on adding a configuration option for state location when `passphrase` option is used; though I was kind of keen to go down the BuildKit as state storage route. Using S3 does require permissions for AWS/GCP/et al.

I guess we can expand support as new consumers begin to kick the tires?

**Comment by shykes** [comment]
> Does this action requires integrations tests though? Shouldn't exporting the `pulumi up` plan and comparing that plan with the expected output should be enough? In this particular case I'm not actually sure if it adds value to make the integration test provisioning some sort of infra somewhere since as stated before, we can already validate "exactly" what pulumi's plan will be doing.

That's true. I was thinking of integration tests for the state storage backend (for Pulumi's state itself). This would be either S3 or Pulumi's SaaS (from my experience with the Terraform community, both are probably equally important). I'm sure there will be requests for other storage backends beyond S3, too.

**Comment by shykes** [comment]
> Yeah, I do plan on adding a configuration option for state location when `passphrase` option is used; though I was kind of keen to go down the BuildKit as state storage route. Using S3 does require permissions for AWS/GCP/et al.
> 
> I guess we can expand support as new consumers begin to kick the tires?

Yes absolutely. That's the beauty of an experimental namespace :)

**Review by helderco — APPROVED** [review]
Looks good 🙂

**Comment by rawkode** [comment]
@helderco Should be good now

**Pull request merged**
