### PR TITLE
sdk: python: Add a few more tests

### LINKED ISSUE #3675: Add a few essential tests
There's a lot of tests to be added, for sure, but I should add at least a few more basic ones for next launch.

- Reuse some test examples from Go (integration)
- Add a few deserialization test cases (unit)[^1]

[^1]: This is where I am most unsure, helps to build confidence.

### PR DESCRIPTION
**Pull request by helderco**
Fixes #3675

Easy win from porting test examples from the Go SDK[^1].
- Fixed mutability issue in query builder
- Fixed default timeout being too low

[^1]: It's also good that you can reuse buildkit's cache between Go and Python's tests since they are producing the same build instructions!

Signed-off-by: Helder Correia

### CODE REVIEW

**Comment by gerhard** [comment]
While this error is unrelated to this PR, I couldn't check if this works [not just your machine](https://nixcraft.tumblr.com/post/173038971847/it-works-on-my-machine-ship-it):

image

I was following [sdk/python/README.md](https://github.com/dagger/dagger/pull/3656/files#diff-73be8f6fa2dd9e669bfdfa8a5732ce9aede74f50a230b04fa9bda67ac5930e46).

**Comment by helderco** [comment]
That's because the SDK isn't provisioning the engine yet. See 1) in 
- https://github.com/dagger/dagger/issues/3642#issuecomment-1302054382

**Comment by gerhard** [comment]
I pushed 2 tiny changes, but still no cigar:

image

As a follow-up PR, we should add these Python tests as a GitHub Workflow - WDYT?

**Comment by helderco** [comment]
> I pushed 2 tiny changes, but still no cigar:

1. You need to run the engine with the sdk's workdir for the tests: `go run ./cmd/cloak dev --workdir sdk/python`
2. When you run `generate` you should then run `lint:fmt` to keep consistent output

> As a follow-up PR, we should add these Python tests as a GitHub Workflow - WDYT?

Yes, it's on the list, just waiting for you 😛

**Comment by helderco** [comment]
I have a few more tests on the way.

**Review by gerhard — APPROVED** [review]
OK to merge as soon as you are ready @helderco.

Works on my machine:

image

Maybe related:

image

Unrelated:

image

**Comment by helderco** [comment]
The mypy warnings are expected for now. Not in scope for next release.

**Pull request merged**
