### PR TITLE
WIP support for cache import/export.

### PR DESCRIPTION
**Pull request by sipsma**
Signed-off-by: Erik Sipsma <erik@sipsma.dev>

Current major caveats:
* Only supports registry cache import/export at the moment; other types can be added pretty easily though.
* The UX is technically usable but needs to be replaced with something better

---

The current (***very much placeholder***) interface is:
* set `DAGGER_CACHE_IMPORT` to e.g. `type=registry,ref=registryA.com/foo:tag;type=registry,ref=registryB.com/bar:tag2`. Include as many imports as you want separate w/ `;`
* Use the `exportCache` field on `Container` to export the cache:
```go
ctr := c.Container().From("alpine:3.15").Exec(dagger.ContainerExecOpts{
	Args: []string{"sh", "-c", "echo $RANDOM > /random && cat /random"},
})
cacheRef := "127.0.0.1:5000/testcacheexport:latest"
_, err = ctr.ExportCache(ctx, "registry", cacheRef, dagger.ContainerExportCacheOpts{Max: true})
```

We'll come up with a better interface before merging this.

### CODE REVIEW

**Comment by aluzzardi** [comment]
Totally missed this PR

> set DAGGER_CACHE_IMPORT to e.g. type=registry,ref=registryA.com/foo:tag;type=registry,ref=registryB.com/bar:tag2. Include as many imports as you want separate w/ ;
> Use the exportCache field on Container to export the cache:

Why not `DAGGER_CACHE_EXPORT`?

Since migrating bits of the CI to dagger, I wish we had cache import/export support. However, I'd probably stick that into the "environment" rather than the code.

Doing a `ctr.ExportCache` from our magefiles wouldn't work locally.

**Comment by sipsma** [comment]
@aluzzardi 

> Totally missed this PR

No worries, I rushed out something for a user who wanted it on short notice and was okay with a separate branch. None of the interface here should be taken as anything but placeholder.

> Why not DAGGER_CACHE_EXPORT?

It's not really possible to know *what* to export in that case. The difference from Dockerfiles/buildx is that for them, there's a well defined "target", which is the ref you want to export. We support arbitrary code and queries, so we don't have a way of knowing what, if any particular result is the one the user actually wants to export cache for. 
* In our code, this is reflected in the fact that we only ever return [an empty result here](https://github.com/dagger/dagger/blob/4edc2a615a8f2c41c5d4eef0980ca334acb47c17/engine/engine.go#L175)

We could export every single ref that we solved in the session, but I'm not actually sure how practical that is and I also don't think that's what all users would want.

> Doing a ctr.ExportCache from our magefiles wouldn't work locally.

Because of the difference between CI and local env? Yeah that's true, but that's also true of exporting an image to a registry right? We should definitely think about how to model those environmental differences, but thankfully we'll have many many more options available to us compared to when we tried to tackle this same problem w/ cue!

---

I need to update with a full proposal here, but the really quick sketch in my head is:
1. `RemoteCache` is a first-class object, has an ID.
   * For now it's just used to configure import sources and to export to, but I think we could consider adding fields that let you query its state (like how much storage is being used)
2. We support `ExportCache(containers: [ContainerID!], directories: [DirectoryID!])` on the `RemoteCache` object. 
3. We support `WithRemoteCacheImport(remoteCache: RemoteCacheID!) Query!` right on the `Query` object
   * yes I am going to lobby for that sort of approach again :-), I think it makes even more sense this time though!

**Comment by aluzzardi** [comment]
> It's not really possible to know _what_ to export in that case. The difference from Dockerfiles/buildx is that for them, there's a well defined "target", which is the ref you want to export. We support arbitrary code and queries, so we don't have a way of knowing what, if any particular result is the one the user actually wants to export cache for.
> 
> * In our code, this is reflected in the fact that we only ever return [an empty result here](https://github.com/dagger/dagger/blob/4edc2a615a8f2c41c5d4eef0980ca334acb47c17/engine/engine.go#L175)
> 
> We could export every single ref that we solved in the session, but I'm not actually sure how practical that is and I also don't think that's what all users would want.

Yeah, that's what we've been doing in 0.2 -- keep track of all references and create a dummy result for cache export:

https://github.com/dagger/dagger/blob/v0.2.x/client/client.go#L242-L256

> Because of the difference between CI and local env? Yeah that's true, but that's also true of exporting an image to a registry right? We should definitely think about how to model those environmental differences, but thankfully we'll have many many more options available to us compared to when we tried to tackle this same problem w/ cue!

Not really the same I think.

Cache settings, how many CPUs to use, network proxying, etc to me feel like "environmental" settings. They change depending on which environment dagger is running, it feels better to me to move them close to where they are needed.

Those settings will change depending on my infrastructure: we might use use GHA cache right now, if moving to self-hosted GHA runners we might want to NOT use any cache (local buildkit), if moving to Jenkins we might want to use a registry instead.

Exporting an image to a a registry instead is core to the pipeline IMHO. I might actually deploy to the same registry all the time (e.g. `mage engine:publish` publishes to the prod registry, either on CI or locally *if you have the right credentials*). Or we might decide to do that conditionally. Or maybe a different `mage` target. But that's really core to our pipelines rather than being *environmental*

**Comment by sipsma** [comment]
I opened an issue to continue discussing the design of this: https://github.com/dagger/dagger/issues/3965

Gonna close this PR for now, will reopen once we have consensus

**Pull request closed without merging**
