### PR TITLE
Docs - Upgrading to Docusaurus v3

### PR DESCRIPTION
**Pull request by slumbering**
This PR is an attempt of upgrading our current docs using Docusaurus v2 towards v3.

Docusaurus migration guide available here: https://docusaurus.io/docs/migration/v3

Tasks list:
- [x] Update the docusaurus.config file to be compliant with the new version (particularly for the theme)
- [x] Update `.md` and `.mdx` files to be complient with MDX v3
- [x] Update `.graphqls` to escape `{` characters causing errors during the building phase
- [x] Update `docusaurus-plugin-typedoc` plugins to the latest version so it escape `{` characters during the SDK reference docs building phase
- [ ] Review and update `BrowserOnly` component

I don't know why but the php `additionalLanguages` for prismJS thrown an error. If I remove it everything works fine 🤔 
cc @vikram-dagger 👉 https://github.com/dagger/dagger/pull/6149/files#diff-bc4913d026ae51bef2bc8b7a1c040fdf52b999d99e6fa40d87b379f98a60e0eaR23

### CODE REVIEW

**Comment by gerhard** [comment]
@slumbering why do we have `website/src/theme` instead of using the Docusaurus one?

**Comment by gerhard** [comment]
We (+@vikram-dagger) tried to get native mdx imports to work, but for a reason that we cannot explain the official instructions do not work for our Docusaurus setup: https://docusaurus.io/docs/markdown-features/react#importing-markdown

Starting with a clean Docusaurus project worked first time.

Rather than figuring what the issue, we are thinking of starting Docusaurus v3 from scratch, in the `docs` directory, and import all the content part of this.

Stopping here for the day, the next step is for Vikram to continue with the above.

**Comment by vikram-dagger** [comment]
I found two errors which were causing the includes to break in the syntax `\{@include:  ../../path\}`:
- The backslashes were not being parsed properly
- There was an extra space before the file path, which was breaking the path reference
I have corrected both these and the includes are now working correctly.

---

I noticed that after doing this, there are still a few pages which are generating this error:

```
ERROR
Docusaurus error: The children of <BrowserOnly> must be a "render function", e.g. <BrowserOnly>{() => <span>{window.location.href}</span>}</BrowserOnly>.
Current type: object
Error: Docusaurus error: The children of <BrowserOnly> must be a "render function", e.g. <BrowserOnly>{() => <span>{window.location.href}</span>}</BrowserOnly>.
```

Pages with this error are `/cli/465058/install` and `/sdk/cue/526369/install`.

I narrowed the error down to these two files:

```
docs/current/partials/_install-cli.md
docs/current/partials/_install-sdk-cue.md
```

Both these files include the following code:

```
<BrowserOnly>
\{() =>
<Tabs defaultValue={
 window.navigator.userAgent.indexOf('Linux') != -1 ? 'linux':
 window.navigator.userAgent.indexOf('Win') != -1 ? 'windows':
 'macos'}
groupId="os"
values={[
{label: 'macOS', value: 'macos'}, {label: 'Linux', value: 'linux'}, {label: 'Windows', value: 'windows'},
]}>
```

image

My guess is that the above code is not producing the render result Docusaurus expects. I think this code needs a modification (or deletion?). I will defer to @slumbering to review this code and make the necessary changes.

Note also that the above error was causing the Docusaurus build to fail. To work around it temporarily so that I could test the pages, I enclosed the include path refs for the above files in double quotes. See https://github.com/dagger/dagger/pull/6149/files#diff-b457a106658af989941d41ef311235ccbefa5e8354ce5483de43008cdb035050R32 for an example. I don't know why this works, but it seems to at least allow the build to complete and the server to start. Accessing any page referencing these two includes continues to fail and produce the above error. Once we fix the above code, we should also remove the double quotes around the include path ref.

**Comment by gerhard** [comment]
As a separate thought, I wonder if starting from a clean Docusaurus v3.0 install, without any plugins or additions, would make the upgrade smoother, and result in fewer dependencies overall.

For example, we have learned yesterday that the plugin which we use for including partials is now redundant. Docusaurus supports this functionality natively: https://docusaurus.io/docs/markdown-features/react#importing-markdown

Maybe there are other components that we no longer need, and perhaps the overall config could be simplified. Starting from scratch would allow us to only add what we need, and leave everything else out, step by step.

If we leave the current Docusaurus v2.0 setup as is, and start with a new Docusaurs 3.0 setup (requires new `devel.docs` site), we can do it across multiple PRs, try it out in production incrementally, and when the new version behaves like the old one, we can just re-configure `docs` to use the new setup.

Happy to defer the final decision to you @slumbering @vikram-dagger.

**Comment by vikram-dagger** [comment]
> If we leave the current Docusaurus v2.0 setup as is, and start with a new Docusaurs 3.0 setup (requires new `devel.docs` site), we can do it across multiple PRs, try it out in production incrementally, and when the new version behaves like the old one, we can just re-configure `docs` to use the new setup.
> 
> Happy to defer the final decision to you @slumbering @vikram-dagger.

I'm happy to try this. I would do it in a separate PR though and try to get this one working in parallel. This way, we have a backup plan (also considering timeline requirements). If we are able to achieve an equivalent result with the new "clean" version, we can merge whichever PR we feel is better. WDYT?

**Comment by gerhard** [comment]
OK, sounds good!

Please continue with `BrowserOnly` @slumbering as time permits. Thank you!

**Comment by gerhard** [comment]
This was superseded by https://github.com/dagger/dagger/pull/6164

**Pull request closed without merging**
