### PR TITLE
Rename cloak to dagger

### PR DESCRIPTION
**Pull request by gerhard**
⚠️ This is a significant & disruptive change, please read this message with the care & attention so that the surprises are kept to a minimum ⚠️

"Project Cloak" was the codename for what will become Dagger v0.3.x. As we start preparing to ship Dagger v0.3.x pre-releases, we need to use the same "dagger" name everywhere so that:

1. Users keep the same entrypoint: the `dagger` binary

2. The tooling that installs `dagger` (e.g. HomeBrew, install.sh, install.ps) largely continues working as is. The only difference is that now the tooling will gain the functionality to install pre-releases of `dagger`.

There is more context here (including what happens after this gets merged): https://github.com/dagger/dagger/issues/3176#issuecomment-1267359683

### CODE REVIEW

**Comment by gerhard** [comment]
There is an ongoing incident with GitHub Actions which explains why the checks are not running currently: https://www.githubstatus.com/incidents/smn1qtqvbsb6

**Comment by aluzzardi** [comment]
@gerhard Do you want to go ahead and merge this? Must be painful to maintain ... /cc @sipsma

**Comment by sipsma** [comment]
I only have one concern, which is that the nodejs and python engine sdks relied on finding the `cloak` binary in their path, now they rely on `dagger`. This means that users have to be sure that they have the most recent `dagger` built from the cloak branch. That's fine, I just fear that it's more likely users have some existing europa dagger binary laying around and now the engine sdk will find that and not work.

There's not all that much we can do here in the immediate term besides document that users need to build `dagger` from cloak branch and put that in their PATH. Longer term this will be improved by including the binary w/ the npm/python packages.

Above isn't a blocker though, I agree that it will be highly painful to maintain this branch so we should be biased towards merging asap.

**Comment by gerhard** [comment]
> @shykes 1. Can we have the checklist in its own issue?

Done: https://github.com/dagger/dagger/issues/3176#issue-1390192888

> 2. At what point to we finalize the syntax for the new `dagger`? The current syntax is ad hoc and we never discussed its design end to end. I would like an opportunity for that.

I expect this to happen over the next week. From a pre-release process perspective, this can happen in parallel - I don't see any coupling. My aim is to get `alpha` pre-releases published. We don't have to announce them, they just need to be available. People can try them out, but there is no guarantee on anything (the syntax can change as it needs to).

As we make progress over the coming weeks, we can decide to move onto `betas` or `rcs`. `Beta` to me signals one step closer to the GA and less change, but still no guarantees. At that point, we should start involving users and aim to finalise the big items like the syntax things. As soon as we hit the `RCs` stage, I would expect us to freeze new features and only publish fixes. By then, I would expect the new `dagger` syntax to be locked in. We can start any of these stages whenever we feel we are ready. We can also skip them. My preference would be not to, but I am easy. As long as we are exercising the release process regularly, I am easy on the steps towards GA. This PR is the first step towards building a release process for `v0.3.x`.

**Comment by gerhard** [comment]
> Do you want to go ahead and merge this? Must be painful to maintain ...

@aluzzardi as soon as we have confidence that the tests pass and everything looks good, yes.

I have a few more questions to answer and figure out why the tests GitHub Action has not run. I am keen on converting this into **Ready for review** in the next hour or so. Will update if I don't get there within this time-box.

**Comment by gerhard** [comment]
> @sipsma I only have one concern, which is that the nodejs and python engine sdks relied on finding the `cloak` binary in their path, now they rely on `dagger`. This means that users have to be sure that they have the most recent `dagger` built from the cloak branch. That's fine, I just fear that it's more likely users have some existing europa dagger binary laying around and now the engine sdk will find that and not work.

WDYT about the SDKs failing if the `dagger` binary version does not start with `0.3.` ?

> @sipsma I agree that it will be highly painful to maintain this branch so we should be biased towards merging asap.

I am giving myself a 1h time-box for this.

**Comment by sipsma** [comment]
> WDYT about the SDKs failing if the dagger binary version does not start with 0.3. ?

That's a good idea, we can at least have a clear error message then

**Comment by gerhard** [comment]
I am stopping now. I am trying to understand why the buildkitd version is empty:

```
go test -v -run TestContainerWithMountedDirectory ./core/integration/container_test.go

=== RUN   TestContainerWithMountedDirectory
=== PAUSE TestContainerWithMountedDirectory
=== RUN   TestContainerWithMountedDirectorySourcePath
=== PAUSE TestContainerWithMountedDirectorySourcePath
=== RUN   TestContainerWithMountedDirectoryPropagation
=== PAUSE TestContainerWithMountedDirectoryPropagation
=== CONT  TestContainerWithMountedDirectory
    container_test.go:440:
                Error Trace:    /workdir/core/integration/container_test.go:440
                Error:          Received unexpected error:
                                buildkitd version is empty
                Test:           TestContainerWithMountedDirectory
=== CONT  TestContainerWithMountedDirectoryPropagation
--- FAIL: TestContainerWithMountedDirectory (0.00s)
=== CONT  TestContainerWithMountedDirectorySourcePath
=== CONT  TestContainerWithMountedDirectoryPropagation
    container_test.go:581:
                Error Trace:    /workdir/core/integration/container_test.go:581
                Error:          Received unexpected error:
                                buildkitd version is empty
                Test:           TestContainerWithMountedDirectoryPropagation
=== CONT  TestContainerWithMountedDirectorySourcePath
    container_test.go:517:
                Error Trace:    /workdir/core/integration/container_test.go:517
                Error:          Received unexpected error:
                                buildkitd version is empty
                Test:           TestContainerWithMountedDirectorySourcePath
--- FAIL: TestContainerWithMountedDirectoryPropagation (0.00s)
--- FAIL: TestContainerWithMountedDirectorySourcePath (0.00s)
FAIL
FAIL    command-line-arguments  0.011s
FAIL
```

I found this https://github.com/dagger/dagger/blob/9fbea2eec8c3840a104dfcae930ada27dfff0af3/internal/buildkitd/buildkitd.go#L87-L100, but this workaround is not being used in the `cloak` branch when invoked as above (the same failure happens). Am I missing something @sipsma?

**Comment by sipsma** [comment]
> I am stopping now. I am trying to understand why the buildkitd version is empty:

I am not at all sure, but I also am not seeing that failure in CI. In CI runs I'm seeing us consistently get:
```
        	Error:      	Received unexpected error:
        	            	input:5: core.filesystem.file failed to read file: ResourceExhausted: grpc: received message larger than max (10315513 vs. 4194304)
        	Test:       	TestGoGenerate
--- FAIL: TestGoGenerate (64.67s)
```

Which is... extremely odd. I can reproduce it locally though when pulling this branch, so I will debug and push a fix here.

**Comment by sipsma** [comment]
@gerhard noticed that the PR seemed to accidentally have a `go` binary committed, that was the cause of the `grpc: received message larger than max` error. Tests pass for me locally after that.

For the original issue you posted about the `buildkitd version` error, I can reproduce it if I run your exact command, but if I run the slight variant of `go test -v -run TestContainerWithMountedDirectory ./core/integration/` then the test passes.

I think this is because our integration tests rely on some special magic done in an `init` func in `suite_test.go` in that package, and without that init func running they can't start `buildkitd`. There's a whole back story here, happy to share more and dig up the original commits if desired, but suffice it to say that you need to specify the full `./core/integration` package when running tests.

That's not obvious though of course. I guess we need some developer documentation. I'll add a bare-bones `TESTING.md` for now.

**Comment by gerhard** [comment]
@aluzzardi please review and merge if it all looks good to you.

I will add the next PR on top of this one.

**Comment by aluzzardi** [comment]
> WDYT about the SDKs failing if the dagger binary version does not start with 0.3. ?

Alternatively, to avoid an extra roundtrip (e.g. SDK executing an additional "dagger version" command), we could just catch from the SDK "dev: command not found" and rewrite the error, since that's what's going to happen when using the SDK on 0.2.x.

**Review by sipsma — APPROVED** [review]
LGTM, thanks for updating back to cloak.yaml last minute

**Review by aluzzardi — APPROVED** [review]

**Pull request merged**
