### PR TITLE
docs: fixes docs code examples in the quickstart

### PR DESCRIPTION
**Pull request by samalba**
Fixes wrong directory path in the Getting Started code snippets.

### CODE REVIEW

**Comment by vikram-dagger** [comment]
@samalba thanks for noticing this! Seems like the error is only in the Go snippets so pinging @marcosnils as FYI since he created those. 

I also found a couple of other inconsistencies between the Go snippets and the others, so fixing those in this PR itself and will then regenerate the embeds with all changes.

**Review by vikram-dagger — APPROVED** [review]

**Comment by vikram-dagger** [comment]
@crjm embed ids have changed, this affects your PR #4537

**Review by marcosnils — APPROVED** [review]

**Comment by vikram-dagger** [comment]
Playground embeds still show errors for some pages, investigating further. Do not merge until I update here.

**Comment by vikram-dagger** [comment]
Update: I am still not able to generate new embeds for the updated code. This could be an error in the script I'm using or an issue with the Playground.

**Comment by marcosnils** [comment]
We got together with Vikram today and found the issue. Script should be good now.

**Comment by vikram-dagger** [comment]
Update: Embeds are now being generated correctly. Will re-test and merge if successful.

**Pull request merged**
