### PR TITLE
Add GPU access guide

### PR DESCRIPTION
**Pull request by matiasinsaurralde**

### CODE REVIEW

**Review by gerhard — COMMENTED** [review]
@vikram-dagger is the best one to review this, for sure 👍

Rebasing on top of `main` and addressing these linting issues will help it move along quicker @matiasinsaurralde https://github.com/dagger/dagger/actions/runs/6779732529/job/18427252624?pr=6084#step:5:189

Is there anything else that needs to happen before this moves out of draft?

image

**Comment by vikram-dagger** [comment]
@matiasinsaurralde thanks for drafting this guide. It is very interesting! 

I have a few initial comments/suggestions:
- The code listings in Steps 4 and 5 should ideally be saved as separate files and referenced inline in the guide, so that they can be linted. Refer to https://github.com/dagger/dagger/blob/main/docs/current/guides/183109-aws-codebuild-codepipeline.md?plain=1#L106 for an example of how to do this.
- Would it make sense to add a few screenshots in Steps 1 and 2 for the UI-related configuration? Refer to https://github.com/dagger/dagger/blob/main/docs/current/guides/183109-aws-codebuild-codepipeline.md?plain=1 for examples.
- Once you make the above changes, would it be OK for me to do a light copy edit on the content to have it better match our style guidelines? See https://github.com/dagger/dagger/blob/main/docs/STYLE_GUIDE.md

**Comment by gerhard** [comment]
What should happen with this next @matiasinsaurralde ?

**Comment by vikram-dagger** [comment]
@matiasinsaurralde please rebase this before merging, as the docs filesystem structure has changed. See https://github.com/dagger/dagger/pull/6164/ for details. Feel free to ping me if you need any help.

**Comment by matiasinsaurralde** [comment]
@vikram-dagger Sounds good - I'm just retaking this one

**Pull request closed without merging**
