### PR TITLE
docs: env var reference

### PR DESCRIPTION
**Pull request by grouville**
Exhaustive list of current env var available with Dagger

@crjm. The table is too small, I don't know how I could improve the design, to represent the same idea

Signed-off-by: Guillaume de Rouville

### CODE REVIEW

**Comment by crjm** [comment]
I think having a table is a good idea for this, it's straightforward and matches the layout of the other references.

In case we choose this layout, there are two options:
* Make a table component so when clicking an icon, the table expands and occupies the whole screen, like a modal. This will take time because the table component is not [swizzable](https://docusaurus.io/docs/swizzling) (it's not showing in the exported list when executing `yarn run swizzle @docusaurus/theme-classic -- --list`), so I'll have to hack the framework.
* The other way is simple and requires only one line in `13ec8-dagger-env-reference.md` metadata: add `hide_table_of_contents: true`. The downside is that you loose the table of contents of this particular doc, but you gain quite a lot of space for the table.
* 
If we are going with the first approach, we should push this as is IMO, and I'll open another PR with the table component.

**Comment by crjm** [comment]
But taking a step back, there are to many empty cells in the `Persist CLI options` table, so maybe we can benchmark against other tools to see how they document their CLI.
* [Netlify](https://cli.netlify.com/)
* [Vercel](https://vercel.com/docs/cli#commands)
* [Ionic](https://ionicframework.com/docs/cli/commands/build)

**Comment by grouville** [comment]
> But taking a step back, there are too many empty cells in the `Persist CLI options` table, so maybe we can benchmark against other tools to see how they document their CLI.
> 
> * [Netlify](https://cli.netlify.com/)
> * [Vercel](https://vercel.com/docs/cli#commands)
> * [Ionic](https://ionicframework.com/docs/cli/commands/build)
> 
> By seeing this, we can have a category called CLI inside the References section and several tiny doc pages inside that explain each command and their options. Or maybe, as we don't have too many commands, we can just put them all in the same page, with paragraphs instead of different docs (instead of a table).

I made an arbitrage between a menu split and env var references. I think it's the best ratio in tweaking dagger and lisibility.

**Review by crjm — APPROVED** [review]
Woah, way cleaner. Love it :ship:

**Comment by grouville** [comment]
Closes #2901

**Pull request merged**
