### PR TITLE
ci: Deploy todoapp with dev dagger AND ALSO latest 0.2.x release

### PR DESCRIPTION
**Pull request by gerhard**
Thanks to a great community contribution, we are improving the GitHub Actions integration further. We should probably do the same for the GitLab integration doc as a follow-up to this.

This should be merged **after** https://github.com/dagger/dagger/pull/1962. Maybe @ekinbarut wants to take a look at it 👋🏻

### CODE REVIEW

**Comment by gerhard** [comment]
https://github.com/gerhard/dagger/actions/runs/2161477495

image

**Comment by gerhard** [comment]
Adding @aluzzardi as a reviewer since this introduces a new testing pattern: latest release AND dev.

This will become increasingly important as we start thinking about 0.3 pre-releases in the context of 0.2 -> 0.3.

While 0.1 -> 0.2 was a one off, I don't expect us to do the same with 0.3.

**Comment by gerhard** [comment]
Fixing the merge conflict now.

**Comment by gerhard** [comment]
Question for @dagger/maintainers: should multiple areas be appended to a commit that introduces multiple changes, e.g. `docs: ci:`. This one would most certainly qualify as such.

**Review by ekinbarut — APPROVED** [review]

**Comment by gerhard** [comment]
WDYT @shykes?

**Comment by gerhard** [comment]
WDYT @dolanor @grouville @helderco @TomChv? Would like to get this one in is so that it informs #2181.

**Review by TomChv — APPROVED** [review]
That's a great improvement, I like that one :D

**Comment by TomChv** [comment]
> Question for https://github.com/orgs/dagger/teams/maintainers: should multiple areas be appended to a commit that introduces multiple changes, e.g. docs: ci:. This one would most certainly qualify as such.

There shouldn't be multiple change.
If you update doc then commit with `docs`, if you update ci then it should be `ci`
If you do both, then there should be two commits or ignore less important.

In your case, I think you could ignore `docs` or do it in another PR :D

**Comment by gerhard** [comment]
Rebase after https://github.com/dagger/dagger/pull/2195

**Comment by TomChv** [comment]
Why your commit is prefixed with `docs:` but your CI is prefixed with `ci:`?

**Comment by gerhard** [comment]
> Why your commit is prefixed with `docs:` but your CI is prefixed with `ci:`?

It is a `ci: ` change. Fixing it now, together with #2195 🙂

**Comment by gerhard** [comment]
https://github.com/gerhard/dagger/actions/runs/2168695527

image

**Comment by gerhard** [comment]
https://github.com/gerhard/dagger/actions/runs/2168714633

image

**Pull request merged**
