### PR TITLE
docs: Upgrades to Docusaurus 3.1.1

### PR DESCRIPTION
**Pull request by vikram-dagger**
This commit upgrades to Docusaurus 3.1.1

### CODE REVIEW

**Comment by vikram-dagger** [comment]
@crjm this produces the following error on startup

```
TypeError: utils.parseMarkdownString is not a function
    at docs/plugins/docusaurus-plugin-guides/index.js:21:38

[INFO] Docusaurus version: 3.1.1
Node version: v18.16.0
```

**Comment by crjm** [comment]
> @crjm this produces the following error on startup

Yes, I pointed this out here: https://github.com/dagger/dagger/pull/6504#issuecomment-1912810820

Bumping the version to 3.1.1 will break guide files parsing as we are using a Docusaurus internal lib for it, and `3.1.1` changes that library implementation.
I can work on a fix, what's the deadline for this dependency bump?

**Comment by vikram-dagger** [comment]
> > @crjm this produces the following error on startup
> 
> Yes, I pointed this out here: [#6504 (comment)](https://github.com/dagger/dagger/pull/6504#issuecomment-1912810820)

Ah, thank you for the reminder and for finding this issue already!

> Bumping the version to 3.1.1 will break guide files parsing as we are using a Docusaurus internal lib for it, and `3.1.1` changes that library implementation. I can work on a fix, what's the deadline for this dependency bump?

No deadline. Whenever you have some time to look at it :)

**Comment by vikram-dagger** [comment]
Done in https://github.com/dagger/dagger/pull/6812

**Pull request closed without merging**
