### PR TITLE
Prevents files to be used as input of dagger.#FS

### LINKED ISSUE #1977: 🐞 dagger hangs if a file is supplied to client filesystem read set as dagger.#FS
### What is the issue?

When using a file instead of a directory as the input of `dagger.#FS`, dagger hangs.

### Log output

N/A

### Steps to reproduce

Create a dagger with the following plan file and run `dagger do test` to reproduce.

```test.cue
package main

import (
	"dagger.io/dagger"
)

dagger.#Plan & {
	client: filesystem: "somefile.txt": read: contents: dagger.#FS
	actions: test: {
	}
}
```

### Dagger version

0.2.4

### OS version

Linux tp 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by marcosnils**
Errors out in the PreRun phase of the clientfilesystemreader task since
otherwise, dagger execution would hang
Fixes #1977

Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>

### CODE REVIEW

**Review by aluzzardi — APPROVED** [review]

**Comment by jlongtine** [comment]
I like failing over hanging and I'm wondering if we should do something smarter if it's a file. I can see only wanting a single file from the client. 

I suppose we could have our users just `include` the file, but then they have to do a readfile to get the contents. Thinking out loud. 🤷🏻‍♂️

**Comment by helderco** [comment]
We need more checks related to this:

- Check if reading a directory into "not a directory";
- Check if writing an `#FS`into "not a directory"
- Check if writing "not an `#FS`" into a directory;

**Comment by marcosnils** [comment]
> We need more checks related to this:
> 
> * Check if reading a directory into "not a directory";
> * Check if writing an `#FS` into "not a directory"
> * Check if writing "not an `#FS`" into a directory;

makes sense. I'll check those tomorrow and add the missing cases.

**Comment by marcosnils** [comment]
> I can see only wanting a single file from the client.

Well.. initially I thought about the same thing. I'd prefer to use `dagger.#FS` regardless if the input is a file or a FS tree. The main reason why this initial PR throws an error is mostly because currently there's a clear differentiation in the `plan.cue` about both types. I'm not sure if we could  treat both interchangeably withing the same type.

**Comment by shykes** [comment]
I only have superficial context, but it scares me to use `dagger.#FS` to represent either a tree or an individual file. I think it would cause too many special cases when manipulating a `dagger.#FS`. Everyone would constantly need to check "what type of dagger.#FS is this?". Probably easier to create a new top-level type (assuming that `string` or `bytes` is not enough).

**Comment by helderco** [comment]
> I only have superficial context, but it scares me to use `dagger.#FS` to represent either a tree or an individual file. I think it would cause too many special cases when manipulating a `dagger.#FS`. Everyone would constantly need to check "what type of dagger.#FS is this?". Probably easier to create a new top-level type (assuming that `string` or `bytes` is not enough).

No, @marcosnils is just checking easy to check potential errors like trying to read /write a file to/from a directory.

**Review by TomChv — APPROVED** [review]
LGTM

**Comment by marcosnils** [comment]
> * Check if writing an `#FS` into "not a directory"
> * Check if writing "not an `#FS`" into a directory;

Dagger is already corretly handling these cases.

**Comment by jlongtine** [comment]
> > I can see only wanting a single file from the client.
> 
> Well.. initially I thought about the same thing. I'd prefer to use `dagger.#FS` regardless if the input is a file or a FS tree. The main reason why this initial PR throws an error is mostly because currently there's a clear differentiation in the `plan.cue` about both types. I'm not sure if we could treat both interchangeably withing the same type.
> 
> thoughts?

Yeah, in thinking this through, the clarity/simplicity of "we only import folders through this mechanism" makes sense to me. The only way a single-file-client filesystem makes sense is if we're just doing an implicit `include` of just that file. But I think that breaks the simplicity. 

I say keep this pattern for now. If a user wants a single file, they can specify that `include`.

My two cents.

**Comment by helderco** [comment]
> Yeah, in thinking this through, the clarity/simplicity of "we only import folders through this mechanism" makes sense to me. The only way a single-file-client filesystem makes sense is if we're just doing an implicit `include` of just that file. But I think that breaks the simplicity.

It's not just that, when reading a file, you read it's contents into a string or a secret. You'd have to add those steps to read that file's contents if we always read into an `#FS` (with implicit include on a file).

**Pull request merged**
