### PR TITLE
fix: ensure cli handles scalar lists correctly

### PR DESCRIPTION
**Pull request by jedevc**
Fixes https://github.com/dagger/dagger/issues/7320.

Also added tests for this. cc @TomChv the typescript tests I added seem to fail, with:

```
$ dagger --progress=plain call --source=. test custom --race=true --pkg=./core/integration --run=TestModuleScalarType/typescript
...
    module_test.go:2989: 
        	Error Trace:	/app/core/integration/module_test.go:2989
        	Error:      	Received unexpected error:
        	            	input: container.from.withMountedFile.withWorkdir.withExec.withNewFile.withExec.stdout resolve: process "dagger --debug query" did not complete successfully: exit code: 1
        	            	
        	            	Stderr:
        	            	1: in dagger --debug query
        	            	1: Error: make request: returned error 400 Bad Request: failed to get schema for module "test": failed to create function "fromPlatforms": failed to find mod type for function "fromPlatforms" arg "platform" type
        	            	
        	            	15:42:31 DBG frontend exporting spans=1
        	            	15:42:31 DBG frontend exporting span trace=b9c43ba0461c6e244dabbe1406b06afa id=82e27b67a024516f parent=fd0d740fbafba8a2 span="dagger --debug query"
        	            	15:42:31 DBG recording span span="dagger --debug query" id=82e27b67a024516f
        	            	15:42:31 DBG recording span child span="dagger --debug query" parent=fd0d740fbafba8a2 child=82e27b67a024516f
        	            	15:43:01 DBG frontend exporting spans=1
        	            	15:43:01 DBG frontend exporting span trace=b9c43ba0461c6e244dabbe1406b06afa id=82e27b67a024516f parent=fd0d740fbafba8a2 span="dagger --debug query"
        	            	15:43:01 DBG recording span span="dagger --debug query" id=82e27b67a024516f
        	            	15:43:01 DBG recording span child span="dagger --debug query" parent=fd0d740fbafba8a2 child=82e27b67a024516f
        	            	15:43:31 DBG frontend exporting spans=1
        	            	15:43:31 DBG frontend exporting span trace=b9c43ba0461c6e244dabbe1406b06afa id=82e27b67a024516f parent=fd0d740fbafba8a2 span="dagger --debug query"
        	            	15:43:31 DBG recording span span="dagger --debug query" id=82e27b67a024516f
        	            	15:43:31 DBG recording span child span="dagger --debug query" parent=fd0d740fbafba8a2 child=82e27b67a024516f
        	            	15:43:43 DBG frontend exporting spans=1
        	            	15:43:43 DBG frontend exporting span trace=b9c43ba0461c6e244dabbe1406b06afa id=82e27b67a024516f parent=fd0d740fbafba8a2 span="dagger --debug query"
        	            	15:43:43 DBG new end old="0001-01-01 00:00:00 +0000 UTC" new="2024-05-08 15:43:43.799920182 +0000 UTC"
        	            	15:43:43 DBG recording span span="dagger --debug query" id=82e27b67a024516f
        	            	15:43:43 DBG recording span child span="dagger --debug query" parent=fd0d740fbafba8a2 child=82e27b67a024516f
        	            	15:43:43 DBG frontend exporting logs logs=1
        	            	15:43:43 DBG exporting log span=82e27b67a024516f body="Error: make request: returned error 400 Bad Request: failed to get schema for module \"test\": failed to create function \"fromPlatforms\": failed to find mod type for function \"fromPlatforms\" arg \"platform\" type\n\n"
        	            	
        	            	Error: make request: returned error 400 Bad Request: failed to get schema for module "test": failed to create function "fromPlatforms": failed to find mod type for function "fromPlatforms" arg "platform" type                                                                                            
        	            	
        	            	Error: make request: returned error 400 Bad Request: failed to get schema for module "test": failed to create function "fromPlatforms": failed to find mod type for function "fromPlatforms" arg "platform" type
```

Both go and python seem to pass, not quite sure as to why typescript doesn't, any chance you could lend a hand?

### CODE REVIEW

**Comment by helderco** [comment]
Looks like the `Platform[]` is being registered as `string[]`:

Screenshot 2024-05-09 at 10 24 58

Screenshot 2024-05-09 at 10 25 07

Screenshot 2024-05-09 at 10 25 14

**Comment by jedevc** [comment]
I think I've worked out what's wrong - this looks wrong:
https://github.com/dagger/dagger/blob/f1aa5e117e163449208519ce6c6b1dbdb8ef5d79/sdk/typescript/introspector/scanner/utils.ts#L75-L81

Essentially, if we're trimming off the end of the list here, we should also be modifying the `type` arg, and descending into it's element type here. However, I'm not *quite* sure how to do this - are all lists in typescript `EvolvingArrayType`? What's the type for an array?

**Comment by helderco** [comment]
There's a larger issue here:

https://github.com/dagger/dagger/blob/f1aa5e117e163449208519ce6c6b1dbdb8ef5d79/sdk/typescript/introspector/scanner/utils.ts#L95-L108

This makes `Platform[]` produce a list of objects.

**Comment by TomChv** [comment]
I can check that next week, I'm currently off and come back on Monday, I know where the issue come from, it's an easy fix

**Pull request merged**
