### PR TITLE
Added running typescript SDK tests inside bunjs runtime

### PR DESCRIPTION
**Pull request by benjaminstrasser**
As mentioned in #6591 I looked into running our current test suite inside the bun runtime. This is the result.
Currently unref is not working, but is already fixed and should be availaible soon [#](https://github.com/oven-sh/bun/issues/4333). The oven/bun:canary image already fixes the problem with unref().

All other tests seem to work just fine.

This approach is an alternative to #6590

### CODE REVIEW

**Comment by TomChv** [comment]
Nice! That's great that bun can work with our current test suite 🚀 
I think you can close #6590 if this one is just fine!

I see that it's still failing in the CI, do the test work locally?

**Comment by TomChv** [comment]
According to [Bun compatibility](https://bun.sh/docs/runtime/nodejs-apis#:~:text=Bun%20aims%20for%20complete%20Node,certain%20is%20to%20try%20it.). It says:

> This page is updated regularly to reflect compatibility status of the latest version of Bun. The information below reflects Bun's compatibility with Node.js v20

So I guess we can update our Node version to 20 and still be ok, that's a pretty decent upgrade and I'm open to give it a try.

Regarding the Bun version, which one is the most stable? Is `1.0.0` okay?

We must keep in mind that updating the module runtime version is way more sensitive than updating a simple dependency, and we aim to be as stable as possible on this part.
On the other hand, Bun is still working on Node compatibility so we might need to update the version if we need some more support.

As a conclusion, I think we can start with `1.0.0` and then upgrade the version if we need it in order to get the runtime working.

**Comment by benjaminstrasser** [comment]
> So I guess we can update our Node version to 20 and still be ok, that's a pretty decent upgrade and I'm open to give it a try.
> 
I just run our tests in node:20-alpine and they all pass as expected. Since node is mostly backwards compatible, I would say it is up to us to decide what the lowest release should be we reliable test for.

I would suggest we simply attach ourselves to the node maintainance end of life cycles. For `node:16` that would have been September 11th 2023. I therefore would upgrade to `node:18`. `node:18` should be EOL on April 30th 2025 and thats when I would upgrade to `node:20`. This way we always support the lowest maintained node version. Would love your input on this approach.

If we would like to test the current node version or potentially all stable versions, I would suggest a scheduled GitHub action, maybe running once a week. This way we know if our SDK works inside the current node version without unnecessarily interrupting PRs that have nothing do with the typescript SDK, which is something I always like to avoid whenever possible, while still getting the information that something is broken an might need some fixing. imo this is probably a bit much. Your thoughts?

> Regarding the Bun version, which one is the most stable? Is `1.0.0` okay?
> 
> We must keep in mind that updating the module runtime version is way more sensitive than updating a simple dependency, and we aim to be as stable as possible on this part. On the other hand, Bun is still working on Node compatibility so we might need to update the version if we need some more support.
> 
> As a conclusion, I think we can start with `1.0.0` and then upgrade the version if we need it in order to get the runtime working.

bun `1.0.0` does not work as even more node compatibility issues arise aside from `unref()`.
I totally agree with your sentiment that we want to be as stable as possible with runtime versions  for these kind of tests. I therefore suggest simply using the next bun release that works for us. This is probably `1.0.27` or `1.1.0` and that we use that version until we need to upgrade as you mentioned.

Similarly to my previous answer we could run scheduled actions against the latest bun release to gain some insight.

**Comment by TomChv** [comment]
I'm waiting for https://github.com/dagger/dagger/pull/6685 to be merged before reviewing that one

**Comment by benjaminstrasser** [comment]
@TomChv 
I just updated the PR but the tests seem to be somewhat flaky. I will look into this tomorrow remove the WIP flag and ping you when everything works.

**Comment by benjaminstrasser** [comment]
Ok I found the issue:

https://github.com/dagger/dagger/blob/aec81d10a55db52937a5e67e5ad8870b29fe9a35/sdk/typescript/api/test/api.spec.ts#L271-L286

**Comment by benjaminstrasser** [comment]
@TomChv 
Ok finally got some time to look at this for more than 15 minutes..
I think evertyhing should be in order now. Please have a look when you can.

Regarding the fixed test case that caused the flakiness. As far as I can tell we often had a race condition where the first execution got interrupted and therefore often threw a `GraphQLRequestError` instead of the `ExecError`. My assumption is that an `ExecError` should be thrown here as that is what happens when the code is awaited or runs in isolation. If that was not the intention of the test we have to look at this again. As far as I can tell bun being faster and handling `assert.reject` slightly different made it fail more often. I got wildly different results on the frequency of the error depending if I ran the tests on my laptop or desktop pc.

**Comment by TomChv** [comment]
> Ok finally got some time to look at this for more than 15 minutes..
I think evertyhing should be in order now. Please have a look when you can.

> Regarding the fixed test case that caused the flakiness. As far as I can tell we often had a race condition where the first execution got interrupted and therefore often threw a GraphQLRequestError instead of the ExecError. My assumption is that an ExecError should be thrown here as that is what happens when the code is awaited or runs in isolation. If that was not the intention of the test we have to look at this again. As far as I can tell bun being faster and handling assert.reject slightly different made it fail more often. I got wildly different results on the frequency of the error depending if I ran the tests on my laptop or desktop pc.

Thanks for your feedbacks! I plan to work on a refactor regarding the errors in the TS SDK to make them more helpfull.
It will probably happen next week.

I really want to merge this PR this week, I'll do one more review, @helderco can give an extra one too and we'll merge it so we can do some tests.
Because the default behaviour does not change, this will not break anything, it's only a bonus for our users

**Review by TomChv — APPROVED** [review]

**Pull request merged**
