### PR TITLE
add dagger login/logout commands

### PR DESCRIPTION
**Pull request by vito**
This PR adds a couple of commands for authenticating with Dagger Cloud.

* `dagger login` authenticates, prints your user ID, and saves credentials locally
* `dagger logout` removes local credentials

There is no change for the rest of the `dagger` CLI.

### CODE REVIEW

**Comment by gerhard** [comment]
I intend to check this out in the next few hours & merge if everything works as advertised so that it goes out in today's release.

**Comment by gerhard** [comment]
@vito I didn't mean to co-author all your commits. It was a side-effect of rebasing on top of the master so that the `go.mod` conflict would get fixed. Would you like to rewrite the history so that everything gets authored by you?

I am looking at this new failure now. This is the last PR which I would like to get merged before we cut the new release.

**Review by gerhard — APPROVED** [review]
Works as advertised!

There are a few follow-ups in my questions above, but nothing to block this from going in.

All good from me. Waiting on @vito @d3rp3tt3 @mircubed to approve before merging.

**Comment by shykes** [comment]
Answering the bikeshedding call :-D

> * `dagger cloud login` authenticates, prints your user ID, and saves credentials locally

`dagger login` -> nowhere else to login

> * `dagger cloud logout` removes local credentials

`dagger logout`

> * `dagger cloud org create` creates an org and adds you as admin + member

`dagger org create`

Note: not sure we want/need that in the CLI. Doesn't seem like the kind of thing you need or want to script or automate. I would argue for dropping this one.

> * `dagger cloud org add-user` adds a user (by ID) to the org with an optional `--role` (member or admin, default member)

`dagger user invite` ? To emphasize the invitation-based collaboration flow.

> * `dagger cloud org remove-user` does the opposite (one `--role` at a time)

`dagger user remove`

> * `dagger cloud org create-token` creates an engine ingestion token for recording events

`dagger runner add`

Instead of focusing on "tokens" (implementation detail), here we focus on what the user wants, which is: to add a runner machine to the fleet, so that it can send telemetry etc. Tokens are a means to an end.

> * `dagger cloud org delete-token` deletes the token

`dagger runner delete`


I propose that we make it a **non-goal** to have full CLI/API parity. CLI should focus on what is useful to do in the terminal. API should focus on making all things possible. If you want to script something that isn't available on the CLI (which should be very rare if we get the CLI UX right), you can just script a graphql query to the cloud API. Example: org creation / deletion doesn't deserve a CLI command IMO

**Comment by vito** [comment]
Update: removed all the org-related commands and moved `login` and `logout` to the root level:

```
❯ dagger --help
Usage:
  dagger [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  login       Log in to Dagger Cloud
  logout      Log out from Dagger Cloud
  query       Send API queries to a dagger engine
  run         Runs a command in a Dagger session
  version     Print dagger version

Flags:
      --cpuprofile string   collect CPU profile to path, and trace at path.trace
      --debug               Show more information for debugging
  -h, --help                help for dagger
      --pprof string        serve HTTP pprof at this address
  -s, --silent              disable terminal UI and progress output
      --workdir string      The host workdir loaded into dagger (default ".")

Use "dagger [command] --help" for more informa
```

Kept most of the internal scaffolding for making Cloud API requests, since we at least still need to make the "get current user" API request in order to print the user ID during `dagger login`. The other commands have been moved to our private repo.

**Review by gerhard — APPROVED** [review]
👍 Works as advertised locally:

image

---

👍 Fails - **as expected** - when connected to a remote host via SSH:

image

**Comment by vito** [comment]
@gerhard Good point for the remote flow, probably worth adding a prompt in the future so the user can manually enter the token. Had to implement something similar for `fly login`.

**Pull request merged**
