### PR TITLE
chore: Fix typo

### PR DESCRIPTION
**Pull request by yuyicai**
Signed-off-by: yuyicai <yuyicai@hotmail.com>

### CODE REVIEW

**Review by TomChv — APPROVED** [review]
Nice catch! Thank you :rocket:

I also spotted the same problem in [`#Copy`](https://github.com/dagger/dagger/blob/1d65f4640d3b340f82793c20fe89f424e3c37ae8/pkg/dagger.io/dagger/core/fs.cue#L79), may you can fix it too in this PR.

You should also prefix your commit with `chore:` so it will be ignore in `CHANGELOG.md`

After those change, the PR will be mergeable :zap:

**Comment by yuyicai** [comment]
> 



> Nice catch! Thank you 🚀
> 
> I also spotted the same problem in [`#Copy`](https://github.com/dagger/dagger/blob/1d65f4640d3b340f82793c20fe89f424e3c37ae8/pkg/dagger.io/dagger/core/fs.cue#L79), may you can fix it too in this PR.
> 
> You should also prefix your commit with `chore:` so it will be ignore in `CHANGELOG.md`
> 
> After those change, the PR will be mergeable ⚡

👌

**Review by TomChv — APPROVED** [review]
LGTM! 

Let's wait for @helderco to approve and merge it :rocket:

**Review by helderco — APPROVED** [review]
Thanks!

**Pull request merged**
