### PR TITLE
Use io.MultiWriter to write command output to stdout

### PR DESCRIPTION
**Pull request by kminehart**
Resolves https://github.com/dagger/dagger/issues/5196

Writes the tui Stdout to os.Stdout as well as the cmdVtx.Stdout().

Before this change, a simple workflow like this:

```go
package main

import (
	"context"
	"fmt"
	"os"

	"dagger.io/dagger"
)

func main() {
	client, err := dagger.Connect(context.Background())
	if err != nil {
		panic(err)
	}

	v, err := client.Container().From("alpine").WithExec([]string{"echo", "hello"}).Stdout(context.Background())
	if err != nil {
		panic(err)
	}

	fmt.Fprint(os.Stdout, v)
}
```

Would not write the program's output to stdout.

```
$ dagger run go run . > out.txt
...
$ cat out.txt

```

With these changes:

```
$ dagger run go run . > out.txt
...
$ cat out.txt
hello

```

### notes

both with and without these changes, redirecting stdout when `_EXPERIMENTAL_DAGGER_INTERACTIVE_TUI=true` is set causes BubbleTea to crash. I don't really know how TUIs work but I'm guessing stdout redirecting will probably never work with the interactive TUI.

```
goroutine 50 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
	/home/kminehart/.go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.2/tea.go:402 +0x95
panic({0x13f5fe0, 0xc0007100d8})
	/usr/lib/go/src/runtime/panic.go:890 +0x263
github.com/dagger/dagger/internal/tui.trunc(...)
	/home/kminehart/Work/Grafana/dagger/internal/tui/util.go:28
github.com/dagger/dagger/internal/tui.Details.headerView({{0x16a2120, 0xc000041950}, 0x0, 0xa, 0x0})
	/home/kminehart/Work/Grafana/dagger/internal/tui/details.go:67 +0x912
github.com/dagger/dagger/internal/tui.Details.View({{0x16a2120, 0xc000041950}, 0x0, 0xa, 0x0})
	/home/kminehart/Work/Grafana/dagger/internal/tui/details.go:92 +0x6b
github.com/dagger/dagger/internal/tui.Model.View({0xc0002c20c0, {0x1685900, 0xc0001e1c20}, 0xc0001e1ce0, 0xc0001e1d10, 0xc0001e1d40, 0xc00023a500, {{0x16a2120, 0xc000041950}, 0x0, ...}, ...})
	/home/kminehart/Work/Grafana/dagger/internal/tui/model.go:392 +0x2eb
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc000391ef0, {0x168eb30?, 0xc00021e000?}, 0x0?)
	/home/kminehart/.go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.2/tea.go:345 +0x647
github.com/charmbracelet/bubbletea.(*Program).Run(0xc000391ef0)
	/home/kminehart/.go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.2/tea.go:465 +0x7fd
main.interactiveTUI.func1()
	/home/kminehart/Work/Grafana/dagger/cmd/dagger/engine.go:92 +0x26
created by main.interactiveTUI
	/home/kminehart/Work/Grafana/dagger/cmd/dagger/engine.go:91 +0x24a
```

### CODE REVIEW

**Comment by jpadams** [comment]
I tested this out and it works as advertised  :)

```
cd /tmp
git  clone https://github.com/dagger/examples
cd examples/go/db-service
dagger run go run main.go > out.txt  #using dagger compiled from this PR
cat out.txt
```

I noticed some color differences. With this PR
image

vs current `dagger run` TUI:
image

**Comment by jpadams** [comment]
@d3rp3tt3 @shykes @vito would love to get your take on this

**Comment by vito** [comment]
Thanks for the PR!

Makes sense to address this, but I think this might break the TUI when you don't redirect stdout since multiple things will be writing to it. 

If so, could make sense to do this if and only if it detects stdout is redirected (i.e. not a terminal).

**Comment by gerhard** [comment]
Thanks for reporting the issue @kminehart & the quick fix. It would be great to include this in the follow-up patch release of `v0.6.0`. WDYT @vito? This could go out as early as this week if it looks good to you.

**Comment by vito** [comment]
Went ahead and submitted an alternative PR with my suggested change (+ supporting stderr redirect too because why not): https://github.com/dagger/dagger/pull/5231

**Comment by kminehart** [comment]
awesome! thanks for doing that

**Pull request closed without merging**
