### PR TITLE
sdk(rust): Use same Apache 2.0 license as all other SDKs

### PR DESCRIPTION
**Pull request by gerhard**
Engine & CLI use the same Apache 2.0 license.

If you agree with this change @kjuulh, please:
- edit the commit message & remove this paragraph
- append your `Signed-off-by`
- commit & force push

Otherwise, let's talk!

### CODE REVIEW

**Review by jpadams — APPROVED** [review]
LGTM!

**Review by kjuulh — APPROVED** [review]
Yep looks good

**Comment by kjuulh** [comment]
Will do so tomorrow xD

**Comment by kjuulh** [comment]
@gerhard done 🚀

**Comment by gerhard** [comment]
Thank you @kjuulh 💪

**Pull request merged**
