### PR TITLE
docs: move dagger cloud under logdebug docs section

### PR DESCRIPTION
**Pull request by marcosnils**
Fixes https://github.com/dagger/dagger.io/issues/432

Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>

### CODE REVIEW

**Comment by mircubed** [comment]
@marcosnils if the URL changed, will there be a automatic re-direct from the old URL since we have the old one posted in a few places?

**Comment by marcosnils** [comment]
> @marcosnils if the URL changed, will there be a automatic re-direct from the old URL since we have the old one posted in a few places?

hmm that's true.. I'll go back to the old URL so we don't break existing references

**Comment by marcosnils** [comment]
Done @mircubed, left the URL same as before, but now the article appears unders the "Logging and Debuggin" guides section.

**Review by mircubed — APPROVED** [review]

**Comment by mircubed** [comment]
@marcosnils the URL seems to be broken? https://docs.dagger.io/1241/dagger-cloud/ 

I will replace it with https://docs.dagger.io/1241/dagger-cloud-debugging in all the places, but I thought we kept it the same to ensure it wouldn't break?

**Pull request merged**
