### PR TITLE
Add `Container.sync` field to force evaluation

### LINKED ISSUE #5065: Force synchronous execution (disable laziness)
## Problem

Developers are [often confused](https://github.com/dagger/dagger/issues/4668) by a property of the engine called "laziness": pipelines are executed at the latest possible moment, to maximize performance.

Sometimes developers want to selectively resolve the laziness: they need to know that at a certain point in their code, the pipeline they have defined so far has actually been executed. Today this can only be done with painful workarounds.

## Solution

Allow developers to selectively resolve the laziness, by forcing synchronous execution of the pipeline up to a specific point. By default, lazy execution remains unchanged.

## Design

**Status:** in discussion

There are several design proposals for this. Some have been proposed as part of broader proposals, which has made consensus more difficult. This issue aims to narrow the focus to one specific problem, with one specific solution - hopefully a narrower scope of design will lead to consensus more easily.

The current candidate is proposed by @aluzzardi and @helderco :

```graphl
extend type Container {
  sync: ContainerID!
}

extend type Directory {
  sync: DirectoryID!
}

extend type File {
  sync: FileID!
}
```

In codegen, instead of returning the `ID`, **passthrough the object** so you can continue chaining lazily.

### Examples

Instead of using `ExitCode` for everything, especially when you don’t actually care about the command’s exit code value, replace with `Sync`:

```diff
- _, err = ctr.ExitCode(ctx)
+ _, err = ctr.Sync(ctx)
```

Unlike `ExitCode` however, `Sync` doesn’t assume you want to run the *entrypoint* when there’s no `WithExec`. This is perfect for making sure a `Dockerfile` **just builds** successfully, without running it’s command:

```diff
- _, err := client.Container().Build(src).Rootfs().Entries(ctx)
+ _, err := client.Container().Build(src).Sync(ctx)
```

If you do need to execute the command, than just add a `WithExec(nil)`. The empty arguments will be replaced by the entrypoint and default args.

You can also use the return value to continue chaining, without having to break into a before and after `Sync`:

```go
// just build, don't run command
ctr, err := client.Container().Build(src).Sync(ctx)
if err != nil {
    return err
}
// you can continue chaining
// (empty WithExec will run default command)
_, err := ctr.WithExec(nil).Sync(ctx)
if err != nil {
    return err
}
```

Same example in Python, which raises exceptions on errors (same in Node.js):

```python
# just build, don't run command
ctr = await client.container().build(src).sync()

# you can continue chaining
# (empty with_exec will run default command)
await ctr.with_exec([]).sync()
```

**Note:** This example is silly and is just for **illustration purposes**. If you do intend to execute the command, it’s best not to do the first `sync` since `build` is a dependency and will already run first and fail early.

### Which object types?

It doesn’t make sense to add `sync` to all types so we need to decide where this is useful.

```[tasklist]
### Tasks
- [x] https://github.com/dagger/dagger/pull/5071
- [ ] https://github.com/dagger/dagger/pull/5414
- [ ] https://github.com/dagger/dagger/pull/5416
```

### PR DESCRIPTION
**Pull request by helderco**
Initial implementation for https://github.com/dagger/dagger/issues/5065

Just `Container` for now, can add more types later.

### CODE REVIEW

**Review by aluzzardi — APPROVED** [review]
API LGTM

/cc @vito for the `Evaluate` call (it that enough to trigger actual evaluation?)

**Comment by helderco** [comment]
> /cc @vito for the `Evaluate` call (it that enough to trigger actual evaluation?)

Yes, it works (tested manually).

I had to pause here to update a bunch of other issues, but I'll return to it very soon.

Last I was working on it, I was doing an `Evaluate` on `Directory` but had to learn more about BuildKit. I may ask @vito for a few pointers when I get back to it.

I'm also still wondering which types to do this besides `Container`, `Directory` and `File`. Is there something from BuildKit/LLB that makes sense as a rule here?

**Comment by helderco** [comment]
It's mergeable now, I can add the rest in follow-ups.

**Review by gerhard — APPROVED** [review]
This one has been a long time coming. First https://github.com/dagger/dagger/issues/4205, then https://github.com/dagger/dagger/issues/4668 & eventually https://github.com/dagger/dagger/issues/5065.

Being able to merge the first step towards addressing a series of complications is mighty satisfying. Thank you @helderco for sticking with this and seeing it through, bit by bit.

**Pull request merged**
