### PR TITLE
feat: refactor module downloading

### PR DESCRIPTION
**Pull request by jcdickinson**
This significantly reworks how modules are downloaded. There are now different strategies for downloading modules.

* Git: downloads with git and maintains the old behavior
* Github: downloads using a .tar.gz from github. The API is used to find the latest tag
* HTTP: Example, `https://github.com/dagger/dagger#/archive/refs/tags/v0.2.7.tar.gz` results in the `github.com/dagger/dagger` module name and `https://github.com/dagger/dagger/archive/refs/tags/v0.2.7.tar.gz` download URL. Everything is simply dumped into the directory, and versions are not supported.

Support for providing a _full_ authentication header has also been added. This is done with the `authorization-header` flag. For example, `--authorization-header 'token ghp_...'`. This works for both HTTP and Github repos.

Finally, some of the require_tests were broken. The tests seemed to represent desired behavior, so I updated`parseDaggerRepoName`.

An alternative to #2275.

Signed-off-by: Jonathan Dickinson <jdickinson@cmgx.io>

### CODE REVIEW

**Comment by jcdickinson** [comment]
I want to follow this up with `dagger login` or something similar to set credentials.

**Comment by TomChv** [comment]
I think it would be really appreciate to have your point of view on that PR @aluzzardi @helderco

**Comment by jcdickinson** [comment]
I think the basic HTTP download might need some redesign. Currently it takes URLs in the form:

```
https://github.com/dagger/dagger#/archive/refs/tags/v0.2.7.tar.gz
```

The fragment portion is lost after the `project update`, meaning that any future `project update` (or `project install`) won't have the full URL to download from. Any ideas on how this could be improved?

**Pull request closed without merging**
