### PR TITLE
Improve releasing during v0.8.0

### PR DESCRIPTION
**Pull request by gerhard**

### CODE REVIEW

**Review by helderco — APPROVED** [review]

**Comment by gerhard** [comment]
@sipsma any idea how we can start debugging this? https://github.com/dagger/dagger/actions/runs/5753589739/job/15597714727#step:4:160

image

**Comment by sipsma** [comment]
> @sipsma any idea how we can start debugging this?
> 
> https://github.com/dagger/dagger/actions/runs/5753589739/job/15597714727#step:4:160 image

@gerhard I think I know the exact problem just from the error message, should be a quick fix if I'm correct, I'll go verify and send out a PR. Will be another thing for v0.8.1

**Comment by gerhard** [comment]
OK!

**Comment by gerhard** [comment]
Do these new errors ring a bell @marcosnils?

https://github.com/dagger/dagger/actions/runs/5753589739/job/15597714954?pr=5569#step:5:11694
image

I am unable to reproduce locally, when running same way as the CI runs.

**Comment by sipsma** [comment]
@gerhard fix here: https://github.com/dagger/dagger/pull/5570

Unfortunately, I think we might just need to skip updating our CI to v0.8 and wait for v0.8.1. Not a huge deal for us internally, but definitely unfortunate that it went unnoticed until now since this will be user-impacting. At least we'll have test coverage for it now after that PR 🥲

**Comment by gerhard** [comment]
That's OK, we knew that this one was going to be bumpy one.

I am pretty sure that we want to get a bunch of other fixes in, I've just hit 2 other issues in another repository that uses Go SDK `v0.8.0`.

**Comment by gerhard** [comment]
That is a sweet fix @vito, thank you very much 💪

Merging this now.

**Pull request merged**
