### PR TITLE
Remove graphiql from cloak dev command.

### LINKED ISSUE #3199: Remove graphiql from cloak engine
ref #3188

### PR DESCRIPTION
**Pull request by marcosnils**
As agreed on #3188, we're discontinuing graphiql from `cloak dev`. T

Fixes #3199

Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>

### CODE REVIEW

**Comment by mircubed** [comment]
fixes #3188

**Comment by marcosnils** [comment]
rebased

**Comment by jpadams** [comment]
@marcosnils @mircubed @shykes thinking we should remove the `playground/` directory as well, right?

**Comment by marcosnils** [comment]
> @marcosnils @mircubed @shykes thinking we should remove the `playground/` directory as well, right?

true. I'll rebase once more.

**Pull request closed without merging**
