### PR TITLE
feat: can use parent dir for a cloak file in -p

### PR DESCRIPTION
**Pull request by dolanor**
Reference: dagger/cloak#159

### CODE REVIEW

**Comment by gerhard** [comment]
What needs to happen before this is ready for review? cc @vito @sipsma @aluzzardi

**Comment by dolanor** [comment]
Since it seems we're getting rid of `cloak.yaml` in it's current form, and maybe any configuration file at all, maybe it's not that relevant?
cc @sipsma @aluzzardi

**Comment by sipsma** [comment]
@dolanor Our goal is to get [dagger.json in for the preview](https://github.com/dagger/dagger/pull/3281), so I'd prefer we merge that before this one, but I think that your PR here still makes sense even after that change

**Comment by aluzzardi** [comment]
dagger.json has been merged!

**Comment by gerhard** [comment]
Ready for you to rebase & re-submit @dolanor.

**Comment by gerhard** [comment]
@dolanor do we want to reopen & merge? cc @aluzzardi

**Pull request closed without merging**
