### PR TITLE
sdk: go: Merge client and generated API together

### PR DESCRIPTION
**Pull request by aluzzardi**
With this change we go from this:

```go
client.Core().Directory().WithNewFile("hello.txt", api.DirectoryWithNewFileOpts{
    Contents: "foo",
})
```

To this:

```go
client.Directory().WithNewFile("hello.txt", dagger.DirectoryWithNewFileOpts{
    Contents: "foo",
})
```

1. `client.Core()` is gone -- instead `client` IS the codegen API
2. codegen datatypes `api.DirectoryWithNewFileOpts` become top-level (`dagger.DirectoryWithNewFileOpts`)

**What's the catch?**

The separation was there in the first place because the codegen API used to NOT be baked into the client

- In "normal" times, with extensions, you're dealing with 2 packages: The SDK and the API generated just for you
- The baked-in codegen is following the same pattern

Now, when we add extensions back:

- Going back to having a separate codegen package should not be too painful (stop using ours and use yours instead)
- However, with this PR, it **will** be painful: everything is mixed together

### CODE REVIEW

**Comment by shykes** [comment]
@aluzzardi 

1. Love the shorter calls, it doesn't seem like much but it is a major DX improvement as it will accrue over many lines of code written by many people for many years :)

2. I don't fully understand the implications of the "catch", but I know it's important. Once I fully understand I will have an opinion on whether we should merge this ASAP, wait, or kill it. I hope the answer is merge!

**Comment by shykes** [comment]
> @aluzzardi
> 
> 1. Love the shorter calls, it doesn't seem like much but it is a major DX improvement as it will accrue over many lines of code written by many people for many years :)
> 2. I don't fully understand the implications of the "catch", but I know it's important. Once I fully understand I will have an opinion on whether we should merge this ASAP, wait, or kill it. I hope the answer is merge!

Update: I love it, the "catch" is manageable, we should absolutely merge it 👍

**Review by vito — APPROVED** [review]
Makes sense to me! I think this is more intuitive; we can cross the extension bridge when we get to it.

**Comment by shykes** [comment]
@kpenfound I would like to lodge a complaint, your demos don't work with the latest Go SDK as of 3 minutes ago.

**Comment by dolanor** [comment]
side eye

**Pull request merged**
