### PR TITLE
Improve releasing during 0.6.3

### PR DESCRIPTION
**Pull request by gerhard**
The biggest change this introduces is: https://changie.dev for release notes. This means that if you want a change to be present in the release notes of the upcoming release, you will need to run `changie new` when contributing a PR, in the correct directory, i.e.:
- `.` for Engine & CLI release notes
- `sdk/go` for Go SDK release notes
- `sdk/nodejs` for Node.js SDK release notes
- `sdk/python` for Python SDK release notes

Here is a real-world example of what that would like (cc @helderco @sipsma @vito @marcosnils):

image

Committing this yaml file - `.changes/unreleased/Fixed-20230714-201908.yaml` in the above example - is essential since that line will be added to the release notes when releasing via `changie batch <patch|minor>`. Here is an example of where that line will end up in:

image

We then use these release notes in GitHub releases, but also in the newly introduced `CHANGELOG.md` files (find them in this PR). FWIW, these are also produced at release time via `changie merge`.

If you wan to learn more about how this improves our release process, check out the updated `RELEASING.md` file. And if you are curious about `changie`, see the asciinema on https://changie.dev.

FWIW, this PR also bumps our internal tooling to the just released Dagger Go SDK v0.7.3.

---

💙 Special thanks to @sheldonhull for mentioning https://changie.dev with us. We first mentioned our intent to integrate it in our release process in the last paragraph of https://dagger.io/blog/how-dagger-releases

image

---

In the interest of getting this merged sooner rather than later, I will update `CONTRIBUTING.md` in a follow-up, most likely next week. Please review & merge if it looks good to you 💪

### CODE REVIEW

**Comment by sheldonhull** [comment]
🎉 very cool! I have mage tasks that wrap changie + Goreleaser for semver versioning if you want some inspiration for more in the future. You can also use auto for batching and it increments the version a single version type based on the changes.

keep up the amazing work 😎

**Review by jlongtine — APPROVED** [review]
LGTM!

:shipit:

**Comment by gerhard** [comment]
> @sheldonhull: I have mage tasks that wrap changie + Goreleaser for semver versioning if you want some inspiration for more in the future

Yes please! Where can I find that?

> @sheldonhull: You can also use auto for batching and it increments the version a single version type based on the changes.

I noticed that, thanks for the reminder. In our case, patch vs minor bump is **not** a technical decision. Our releases involve the entire team, including product, content & marketing, which may have a bunch of things ready for a minor. In that case, we typically drop the experimental label for a feature that has been already available for a few weeks / months, and do a team-wide effort in promoting it.

> @sheldonhull: keep up the amazing work 😎

Always Be Improving 💪 cc @jerodsanto @adamstac

**Comment by sheldonhull** [comment]
Here you go. I have others for single mage commands for generating the tag and merge etc. this should help with the Goreleaser part though. 

I’m in talks with creator on supporting monorepos better too so hopefully soon that will be improved. 

[Example](https://github.com/DelineaXPM/dsv-cli/blob/76dd7516b341b670d081e8973a51deaf5bb22479/magefiles/goreleaser.mage.custom.go#L161)

**Pull request merged**
