### PR TITLE
ci: print Buildkitd logs on failure

### PR DESCRIPTION
**Pull request by sipsma**
If an error happened, the buildkitd logs could be helpful in debugging.

Signed-off-by: Erik Sipsma <erik@sipsma.dev>

Trying to debug the `failed to execute plan: error detecting platform failed to list workers: Unavailable: connection closed before server preface received` error we've been getting.

### CODE REVIEW

**Review by jlongtine — APPROVED** [review]

**Review by aluzzardi — APPROVED** [review]

**Comment by sipsma** [comment]
I made this PR to try to investigate the "flaky" error but now I'm getting that error every run of the CI universe tests. I'll keep re-rolling the dice to see if I get lucky (since I don't think there's any chance this change could have made it worse) but may just let this sit if I hit my retry limit. Either way, gonna debug the error locally.

The buildkitd logs don't show anything interesting. I did notice that the error only happens on the first batch of tests and all the later tests pass, so I suspect it's a race condition where we are just talking to buildkit before it's ready. Running in a loop (killing and restarting buildkitd every time) locally should hopefully let me reproduce it.

**Comment by aluzzardi** [comment]
> I suspect it's a race condition where we are just talking to buildkit before it's ready

Relevant code: https://github.com/dagger/dagger/blob/4fc5cdd47e40c8c40ce3531ae171a82e87c4ba31/util/buildkitd/buildkitd.go#L222

IF we start a buildkit instance, we wait in loop until `ListWorkers()` returns a non-error. Is this enough?

**Comment by sipsma** [comment]
> IF we start a buildkit instance, we wait in loop until ListWorkers() returns a non-error. Is this enough?

I would have thought so, especially since the `detectPlatform` call where the error is coming from just makes that same API call. Still trying to reproduce locally, if I can then maybe some extra debug logs in buildkitd will help.

**Comment by sipsma** [comment]
Pushed a separate commit that appears to "fix" the error for now. It just updates the yarn tests to only run one job at a time instead of 4.

I tried this change on a hunch that there could be a race-condition where multiple dagger clients try to start up buildkitd in docker at the same time and interfere with each other. While the change does seem to work, I have not yet pieced together exactly what chain of events occurs here, so still up in the air what's actually going on and why it started suddenly.

While the change slows the tests down, given that we seem to be consistently hitting this error in every open PR right now, I think we should merge it and then figure out the root cause (and hopefully a better fix).

cc @aluzzardi @jlongtine, will wait for one of your re-approvals of the new commit before I merge.

**Review by jlongtine — APPROVED** [review]
As a temporary stopgap to reduce CI failures, LGTM.

Definitely seems worth exploring if initializing `buildkitd` before the tests are run is a good idea.

**Comment by aluzzardi** [comment]
> Pushed a separate commit that appears to "fix" the error for now. It just updates the yarn tests to only run one job at a time instead of 4.

Ohhh, interesting!

> I guess another approach is to try pre-initializing buildkitd before invoking the tests and then leave the tests running in parallel. Can update with that if preferred.

I'd rather fix the underlying issue altogether.

We did already fix concurrency related problems with vendoring (e.g. multiple `dagger` vendoring at the same time) by using a file lock (`gofrs/flock`), perhaps we could do the same here?

Related yet semi unrelated: I've noticed with OpenTracing that we're losing a good half a second at each dagger invocation because of checking on buildkit. We spawn a `docker inspect` command to figure out if the buildkit instance is the right version etc. 

Perhaps to kill two birds with one stone, dagger should use a file in `~/.config/dagger/` so that:

- We only do the `docker inspect` dance ONCE per dagger version (e.g. we won't do it again unless you upgrade dagger)
- We avoid concurrency (since it's once per dagger version)

That should both solve the CI problems and we should gain half a second or so in execution time.

**Comment by aluzzardi** [comment]
NOTE: Second part is totally optionally, we already have so much to do. But the first part (file lock) should solve our problems with a couple of lines of code.

**Comment by sipsma** [comment]
> But the first part (file lock) should solve our problems with a couple of lines of code.

Yeah I was thinking about that. It doesn't solve the case where docker is remote (and clients can thus be on separate machines), but that's a fairely obscure case. I was hoping that docker had some ability to make container creation idempotent, but didn't find anything, so I agree `flock` is probably the right fix for now. Will send out an update.

Also, I'm still confused why this started happening very consistently out of seemingly nowhere, but at this point we know what the issue is which is probably good enough.

**Pull request merged**
