### PR TITLE
docs: Add interactive debugging examples

### PR DESCRIPTION
**Pull request by vikram-dagger**

### CODE REVIEW

**Review by aluzzardi — APPROVED** [review]
Looks good!

**Comment by vikram-dagger** [comment]
@gerhard @matiasinsaurralde this PR shows CI failures related to Java and Rust, but the PR doesn't contain any examples for those languages. Also, the TypeScript failure is related to a timeout and I'm not sure how to rerun just that one test. Please let me know your thoughts (I'm trying to merge this one as it's approved but not sure how to handle the above failures).

**Comment by Neelajacques** [comment]
Are we missing the discussion of two ways of debugging (Terminal and -i). Also the first line of the whole section that introduces feels a little sparse .. can't we say more about when/why you'd want to use this killer feature.

**Comment by vikram-dagger** [comment]
> Are we missing the discussion of two ways of debugging (Terminal and -i). 

No, both are discussed: https://github.com/dagger/dagger/pull/8050/files#diff-4acff5df3745af1178fb8a7f35ccba20aa4d6499b55b318cc36f3d8fc059b954R14

> Also the first line of the whole section that introduces feels a little sparse .. can't we say more about when/why you'd want to use this killer feature.

Which line/section are you referring to? Also, happy to make changes, are there any specific things you'd like to add?

**Comment by Neelajacques** [comment]
I must have been looking at the an earlier PR, you're right both models are well discussed here. 

Re my other comment: "If you come across bugs, here are some simple debugging suggestions." I was thinking of something more along the lines of: Pipeline failures can be both frustrating and lead to wasted resources as the team seeks to understand what went wrong and why. Dagger provides two features that can help greatly when trying to debug a pipeline - at the failure point or by inserting explicit breakpoints throughout your pipeline code.

**Comment by vikram-dagger** [comment]
> Pipeline failures can be both frustrating and lead to wasted resources as the team seeks to understand what went wrong and why. Dagger provides two features that can help greatly when trying to debug a pipeline - at the failure point or by inserting explicit breakpoints throughout your pipeline code.

Added to cookbook section

**Pull request merged**
