### PR TITLE
Migrate from docsearch-scraper to docsearch.algolia.com

### PR DESCRIPTION
**Pull request by gerhard**
Instead of continuing with the now deprecated docsearch-scraper, we should instead migrate to DocSearch, as mentioned in this blog post: https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration

These are the next steps that I can see:
- [x] Apply for DocSearch → https://support.algolia.com/hc/en-us/requests/491210
- [x] Open a new PR which shows our DocSearch migration intent in our public repo
- [x] Update support request with PR details
- [x] [Migrate from the legacy scraper](https://docsearch.algolia.com/docs/migrating-from-legacy/). WDYT @slumbering?
- [x] Need to plug Docusaurus to our new Algolia app (token id etc..)

As a follow-up to this PR, we should add Dagger to [Docsearch showcase projects]
(https://github.com/algolia/docsearch/blob/next/packages/website/src/components/showcase-projects.json). One for @crjm perhaps?

My expectation is that we will figure out the remaining steps as we get remaining perspectives involved. I'm thinking @slumbering & @shortcuts.

For now, this is enough to kick it off ⚽️

---
Screenshot 2022-04-28 at 11 28 04

Screenshot 2022-04-28 at 11 28 17

image

### CODE REVIEW

**Comment by gerhard** [comment]
How can we trigger crawls programatically @shortcuts? I am thinking from our [deploy-docs](https://github.com/dagger/dagger/blob/main/.github/workflows/deploy-docs.yml) GitHub Action. [Reference](https://docsearch.algolia.com/docs/what-is-docsearch/#quick-description). FWIW, love the Why / What / How structure @shortcuts.

I suspect that [the existing Dagger_Docs index](https://www.algolia.com/apps/XSSC1LRN4S/explorer/browse/Dagger_docs) will become deprecated when we switch to https://docsearch.algolia.com/. Is that your understanding too @slumbering?

This is a question for both of you @slumbering & @shortcuts: do we want the Dagger logo on https://docsearch.algolia.com/?

image

**Comment by gerhard** [comment]
Initial invite expired, asked for another one.

**Comment by gerhard** [comment]
I have just activated the invite & added both you @crjm & @slumbering to the new app.

Let's continue with the setup tomorrow @slumbering.

image

**Comment by shortcuts** [comment]
Enjoy! :)

**Comment by gerhard** [comment]
💡 To access the Crawler, go to https://crawler.algolia.com/admin/crawlers. It uses the same algolia.com login, i.e. https://www.algolia.com/apps/XEIYPBWGOI/dashboard

**Review by slumbering — APPROVED** [review]
LGTM

**Pull request merged**
