### PR TITLE
who use dagger engine as dep, could use engine version from build info

### PR DESCRIPTION
**Pull request by morlay**

### CODE REVIEW

**Comment by gerhard** [comment]
This seems related to https://github.com/dagger/dagger/pull/5485. Want to check this out @grouville?

@morlay rebasing on top of `main` should fix the `test / sdk / rust` failure:
- https://github.com/dagger/dagger/pull/5626

**Comment by morlay** [comment]
@TomChv 

I maintain the cuelang on top of dagger. it is better to get correct image tag with "engine.Version".
https://github.com/octohelm/wagon/blob/main/pkg/engine/daggerutil/engine.go#L40-L53

**Review by TomChv — APPROVED** [review]
LGTM, thanks for the explanation @morlay

**Review by grouville — CHANGES_REQUESTED** [review]
Thanks for the contribution. I asked for changes because:

## 1. There is too much shared logic
Please take a look at: https://github.com/dagger/dagger/blob/main/sdk/go/internal/engineconn/session.go#L46-L63

As you can see, the logic is the same, with a few minor differences. Please either rely on this existing function, or change its implementation to comply with this one.

## 2. Your implementation impacts our development shield against mistakes

At engine initialization, we check:
https://github.com/dagger/dagger/blob/5e7b47d5cd7e58d9f6a30ab93231b1c984663d06/engine/version.go#L38-L40

Your implementation:
```go
if v := engineVersion(); v != "" {
	Version = v
}
```
 will most likely retrieve a valid Semver. Leading to the execution of [this line](https://github.com/dagger/dagger/blob/5e7b47d5cd7e58d9f6a30ab93231b1c984663d06/engine/version.go#L49-L50):
 ```go
 // Version is a semver tag, so use the engine image at that tag
return fmt.Sprintf("%s:%s", EngineImageRepo, Version)
```

 and not this one: https://github.com/dagger/dagger/blob/5e7b47d5cd7e58d9f6a30ab93231b1c984663d06/engine/version.go#L38-L40
 
We used to separate the logic for development purposes: in development mode, if you forget to set the env var linking to your local dev engine, it will use the latest engine built (main), which is probably the closest to the one you're currently developing on. That logic seems quite reasonable, as it prevents contributors to make engine compability mistakes.

Your PR has more depth than it seems. What blockers does it introduce ?

**Pull request closed without merging**
