### PR TITLE
Introduced value with status for host env variable

### PR DESCRIPTION
**Pull request by LokeshN**
Fixes https://github.com/dagger/dagger/issues/3986
Added "ValueWithStatus" type, to return the value and its status in one go.
Added tests

### CODE REVIEW

**Comment by LokeshN** [comment]
@marcosnils / @sipsma Can you please check this PR, when you get some time. Thanks!

**Comment by helderco** [comment]
> @LokeshN my initial thought was to make `value` nullable so we can express empty and non-existent values with `null`.

Yes, same here.

**Comment by LokeshN** [comment]
> @LokeshN my initial thought was to make `value` nullable so we can express empty and non-existent values with `null`. I'd like to know if you considered this alternative and the reason for the new field. Is it mostly to avoid breaking the API?

Yes, @marcosnils I was trying to avoid breaking the existing apis for backward compatibility and I thought we will slowly deprecate the "value" field. Do you think this approach is ok?

**Comment by LokeshN** [comment]
> IMO breaking the API looks like a fair enough trade-off to do at this point for the sake of a cleaner solution.
> 
> I'll defer to @shykes for an opinion.

Hi @marcosnils @shykes Just wanted to check whether we can proceed on this PR. Thanks!

**Comment by shykes** [comment]
In this case I don’t think it’s worth breaking APIs, because `host { envVariable }` itself might soon be deprecated by #4426 . Once we have full-blown dynamic secrets, there will be no need to use a dagger-specific API for something the client’s own OS APIs can do just as well.

So, why bother breaking it now?

cc @aluzzardi @vito

**Comment by marcosnils** [comment]
> because `host { envVariable }` itself might soon be deprecated by #4426

this also applies to container { envVariable }. Do we plan to deprecate that one as well?

**Comment by shykes** [comment]
> > because `host { envVariable }` itself might soon be deprecated by #4426
> 
> this also applies to container { envVariable }. Do we plan to deprecate that one as well?

Not to my knowledge, no.

In that case the “graphql way” might be to add an optional argument to `value`. Either to enable the new behavior (if we decide to avoid breaking) or to revert to the old behavior (if we decide to break).

**Comment by marcosnils** [comment]
> Either to enable the new behavior (if we decide to avoid breaking) or to revert to the old behavior (if we decide to break).

+1. My take on this one is to go ahead and break this API. cc @aluzzardi @vito?

**Comment by vito** [comment]
@marcosnils 

> this also applies to container { envVariable }. Do we plan to deprecate that one as well?

It looks like `container { envVariable }` already does the right thing in returning `String` (nullable) instead of `String!`: https://play.dagger.cloud/playground/KPVCCjfLBTE

Given that, I agree with @shykes; there's not much point changing this now since the next release will have dynamic secrets, which is really the only reason to use the host env var API. We should probably just mark it deprecated.

**Comment by marcosnils** [comment]
> It looks like `container { envVariable }` already does the right thing in returning `String` (nullable) instead of `String!`: https://play.dagger.cloud/playground/KPVCCjfLBTE

:facepalm:

I agree that `host` doesn't make sense to change. I think we got an agreement here. I'll go ahead and close in favor of the dynamic secrets feature. :pray:

**Pull request closed without merging**
