### PR TITLE
Refactor NodeJS codegen

### PR DESCRIPTION
**Pull request by dolanor**
## Goal

- remove extraneous template commands (use `}}` instead of `-}}` as we already have `{{-` in general)
- remove template files if too simple (simple range)

### CODE REVIEW

**Comment by slumbering** [comment]
@dolanor @TomChv Do we have any friction between this PR and this one ?

- https://github.com/dagger/dagger/pull/4415

**Comment by TomChv** [comment]
> Do we have any friction between this PR and this one ?

Not at all :D

**Comment by dolanor** [comment]
I'll check this one tomorrow!

**Comment by TomChv** [comment]
> Is this PR still relevant (cc @dolanor @TomChv ) ?

Of course! I'll rebase it and I'm waiting for Tanguy's review

**Comment by slumbering** [comment]
cc @dolanor ☝️

**Review by dolanor — COMMENTED** [review]
Excellent work, I think you really streamlined it better.
There are a few `-}}` that can be avoided I think.

I would need a new version of the client generated code part of the PR to make sure that we don't have regression now that we removed most of codegen unit test.
Can you run a `go run ./cmd/client-gen/ --lang nodejs -o ./sdk/nodejs/api/client.gen.ts` and commit it with this PR so we see if we didn't break anything during the refactor?

**Comment by slumbering** [comment]
@dolanor as you're the author of this PR, do you think it could be possible for you to make those changes above in order to ship this PR ?

**Comment by dolanor** [comment]
I'm gonna rebase this and fix conflicts.

**Comment by dolanor** [comment]
Ok, good to review/merge!

**Review by TomChv — APPROVED** [review]
LGTM

**Pull request merged**
