### PR TITLE
Prepare to publish dagger-cue artefacts

### PR DESCRIPTION
**Pull request by gerhard**
This PR is:

- part of https://github.com/dagger/dagger/issues/3471
- supersedes https://github.com/dagger/dagger/pull/3483
- partial follow-up to https://github.com/dagger/dagger/pull/3356

It changes the `release-v0.2.x.yml` workflow to publish `dagger-cue` binaries.

Linux `install.sh` & Windows `install.ps1` have been updated too. The Linux variant has been tested.

**Help wanted for the Windows one**.

This was tested via https://github.com/gerhard/dagger/actions/runs/3316263177/jobs/5477850676 & it published:

### 1/2. AWS S3 files

image

Tested with `./install.sh`

image

### 2/2. Homebrew tap

image

Tested with `brew install gerhard/tap/dagger-cue`

image

---

## Next steps

- [x] review & merge https://github.com/dagger/dagger/pull/3506
- [x] review & merge https://github.com/dagger/dagger/pull/3505
- [ ] review & merge this PR
- [ ] publish an official `dagger-cue`
- [ ] @vikram-dagger to update Dagger CUE SDK documentation (it will also ensure that it works as expected)

---

FWIW we ended up upgrading to GoReleaser Pro with @aluzzardi so that we get the monorepo support. It has a bunch of other useful features too that we might want to look into https://beckersoft.gumroad.com/l/goreleaser. The license key has been configured in GitHub Actions. The source of truth is the shared 1Password vault.

### CODE REVIEW

**Comment by gerhard** [comment]
@shykes what version should we use for `dagger-cue`? The last published `dagger` is [`v0.2.36`](https://github.com/dagger/dagger/releases/tag/v0.2.36).

**Comment by shykes** [comment]
> @shykes what version should we use for `dagger-cue`? The last published `dagger` is [`v0.2.36`](https://github.com/dagger/dagger/releases/tag/v0.2.36)

I was just wondering the same thing. The two logical options are 0.2.36 or 0.1.0. I think 0.1.0 makes more sense, it clarifies the relationship to engine version (decoupled) and is consistent with Go SDK. 0.2 branch will no longer move, so maintaining version mapping won't be needed.

wdyt?

**Comment by gerhard** [comment]
`0.1.0` makes sense to me too. I assume that the git tag which we want to use is `sdk/cue/v0.1.0`

**Comment by gerhard** [comment]
In the interest of time, going `sudo` and self-reviewing.

**Review by gerhard — COMMENTED** [review]
It all checks out. I will merge and try to produce a new `dagger-cue` release. If it all works as expected, power on. If it doesn't, I will open a follow-up PR right after this one.

I am **NOT** going to **Squash and merge** in case we need to revert any specific commits. It will also make it easier to understand why specific changes happened, since they tend to be atomic and commit messages relevant. Time to test this in practice.

**Comment by gerhard** [comment]
First run failed since I used the wrong `main` branch: https://github.com/dagger/dagger/actions/runs/3316976548/jobs/5479353848

Second run failed because the tag already existed: https://github.com/dagger/dagger/actions/runs/3316994706/jobs/5479388696

Third run was done from `cue-sdk` which has the correct `.goreleaser.yml` config https://github.com/dagger/dagger/actions/runs/3317001380/jobs/5479401006

Third time lucky, for sure:

image

**Comment by gerhard** [comment]
macOS Intel `brew install dagger/tap/dagger-cue` works as expected:

image

**Comment by gerhard** [comment]
macOS amd64 `curl -L https://dl.dagger.io/dagger-cue/install.sh | sh` works as expected:

image

Same on Linux amd64:

image

cc @vikram-dagger for https://deploy-preview-3485--devel-docs-dagger-io.netlify.app/sdk/cue/526369/install

**Comment by gerhard** [comment]
We might want to check on Windows - I don't have access to one.

**Pull request merged**
