### PR TITLE
docs: Added NodeJS SDK autogen docs

### PR DESCRIPTION
**Pull request by vikram-dagger**
This PR adds plugins to Docusaurus to auto-generate the NodeJS reference docs in Markdown.

### CODE REVIEW

**Comment by vikram-dagger** [comment]
I have found a docusaurus plugin which uses typedoc to generate markdown docs from the code comments. The output is produced in markdown as part of the docusaurus build process and deployed as part of the same website. 

I'm not sure if we want to follow this approach or host these docs on a separate website, as we did for Go and Python. 

I've put this into a separate WIP PR so we can review and discuss separately from the other docs. Note it will need some adjustment as I wasn't sure which files/packages to include/exclude.

**Comment by vikram-dagger** [comment]
Feedback needed:
1. Please have a look at the generated reference docs in the deploy preview. OK to go ahead with this?
2. When working on this PR, we ran into an error with the typedoc error checker (it was failing on various type validations in the SDK). To solve this, we disabled the typedoc type checker. I'm not super comfortable with this solution but practically it may not matter much as typedoc is reading an auto-generated client which presumably has already been checked, linted etc. OK with this workaround or should we follow a different approach? Note: more info on the type validation failures in these messages: 
- https://discord.com/channels/707636530424053791/1038185873289785436/1042480615829819423 
- https://discord.com/channels/707636530424053791/1038185873289785436/1042537046549479424

**Comment by samalba** [comment]
Looks good to me

**Review by shykes — APPROVED** [review]

**Comment by jpadams** [comment]
I see this 
image

**Review by jpadams — APPROVED** [review]
👍

**Pull request merged**
