### PR TITLE
Standalone install docs page

### LINKED ISSUE #2129: Docs: dedicated install / downloads page
Our docs don't have a dedicated page for download / install options. Currently they are hidden in the "getting started" tutorial.

### PR DESCRIPTION
**Pull request by samalba**
Closes #2129

New page will be available at https://docs.dagger.io/install

### CODE REVIEW

**Comment by shykes** [comment]
Nice! Looks like netlify preview links are broken? cc @aluzzardi @gerhard

**Comment by samalba** [comment]
> Nice! Looks like netlify preview links are broken? cc @aluzzardi @gerhard

It works, just the comment is not created anymore (maybe the gh app changed?), go the netlify deploy check below and go to the "details" -> https://deploy-preview-2522--devel-docs-dagger-io.netlify.app/install

**Comment by shykes** [comment]
This paragraph confused me: is there a missing word? 
9C716056-D0B1-4296-AB06-8296BC29E36F

**Comment by samalba** [comment]
This is [from the original doc](https://docs.dagger.io/1200/local-dev), the intent is to show the paths where `dagger` gets installed. _Dagger gets installed in: <path 1> or <path 2>_

Any suggestion to make it less confusing? I did not see a big reason to change it, but fine to do it.

**Review by shykes — APPROVED** [review]
Nice DX improvement 👍

**Comment by shykes** [comment]
> This is [from the original doc](https://docs.dagger.io/1200/local-dev), the intent is to show the paths where `dagger` gets installed. _Dagger gets installed in: <path 1> or <path 2>_
> 
> Any suggestion to make it less confusing? I did not see a big reason to change it, but fine to do it.

I’m not sure, I feel like I’m missing something obvious. Let’s merge this and I can always open a follow up issue / pr if needed.

**Pull request merged**
