### PR TITLE
Cookbook: integrating with a docker engine

### PR DESCRIPTION
**Pull request by shykes**

### CODE REVIEW

**Comment by helderco** [comment]
I ran the formatters, fixed file references and adjusted for consistency.

**Review by helderco — APPROVED** [review]
LGTM

**Comment by shykes** [comment]
> I ran the formatters, fixed file references and adjusted for consistency.

Thanks @helderco! I would have loved to do that myself, but wasn't sure where to start... If only I had access to a standardized environment on my dev machine, with all necessary steps laid out for me to follow... 😇  A great case study for Zenith /cc @sipsma @vito

**Comment by shykes** [comment]
Also @helderco did you check that the snippets actually run? There was no easy way to do that either..

**Comment by helderco** [comment]
> Also @helderco did you check that the snippets actually run? There was no easy way to do that either..

Yeah, it actually pushed me more towards having "ci" tasks to run any snippet. I've thought about it but personally that's mostly for nodejs, because the others are simpler. However it would help others like yourself to test things without having the necessary tools locally. Not to mention with more SDKs being added to the docs in the future. 

Testing Go is simple:
```console
❯ dagger run go run docs/current/cookbook/snippets/docker-engine-host/main.go
```
With Python, you just need to activate a virtual env with `sdk/python` installed (I use conda and it's basically always already activated):
```console
❯ conda activate dagger
❯ dagger run python docs/current/cookbook/snippets/docker-engine-host/main.py
```
Node.js is more difficult so I didn't test it.

There's several extensions and they run differently (`.js`, `.ts`, `.mjs`, `.mts`). In addition to that, node looks for a `node_modules` next to the script you try to run so you get a `Cannot find package '@dagger.io/dagger'` error. At one point I had a `package.json` in the root of dagger that just pointed to `sdk/json`, but I removed it. I tried with `NODE_PATH` but it didn't work:

```console
❯ NODE_PATH=$(pwd)/sdk/nodejs dagger run node docs/current/cookbook/snippets/docker-engine-host/index.mjs
```

I'm sure there's a simple way to do it but haven't looked long enough. Maybe @slumbering can give some pointer.

**Comment by gerhard** [comment]
Was speaking to @mircubed about this one, just confirmed that this is now live: https://docs.dagger.io/7442989/cookbook#connecting-to-docker-engine-on-the-host

image

**Pull request merged**
