### PR TITLE
docs: Converted snippets to embeds for API Concepts doc

### PR DESCRIPTION
**Pull request by vikram-dagger**
This commit replaces the code snippet examples in the API Concepts guide with interactive embeds.

Relates to #4617

### CODE REVIEW

**Review by crjm — APPROVED** [review]
@vikram-dagger if you change the file to a `.mdx` and use [this component](https://github.com/dagger/dagger/blob/main/website/src/components/atoms/embed.js) as it's used [here](https://raw.githubusercontent.com/dagger/dagger/main/docs/current/quickstart/635927-quickstart-caching.mdx), a spinner should appear while waiting for the snippet to load, instead of a white space.
LMK if you'd like me to push a change for it.

**Comment by vikram-dagger** [comment]
> @vikram-dagger if you change the file to a `.mdx` and use [this component](https://github.com/dagger/dagger/blob/main/website/src/components/atoms/embed.js) as it's used [here](https://raw.githubusercontent.com/dagger/dagger/main/docs/current/quickstart/635927-quickstart-caching.mdx), a spinner should appear while waiting for the snippet to load, instead of a white space. LMK if you'd like me to push a change for it.

I reviewed that file but wasn't completely sure how to adapt it for this file, as that file has multiple languages (Go/Python/Node but not GraphQL) and also multiple embed ids for each snippet, and this one has only single GraphQL queries. So probably best if you push the change, and I'll use your code as reference for similar changes in future.

**Comment by vikram-dagger** [comment]
@marcosnils do you know why the engine test is failing?

**Comment by marcosnils** [comment]
@vikram-dagger UI feedback: the embeds seem to be taking way more space than needed:

image


We should be able to make them shorter to make the content more legible. Besides that, LGTM!

**Comment by vikram-dagger** [comment]
> @vikram-dagger UI feedback: the embeds seem to be taking way more space than needed:

@crjm any ideas on this?

**Comment by crjm** [comment]
I'm looking at two alternatives to fix this. 
- Add a feature to set the height of both the response and the result of each embed manually. 
For example, it would be `<Embed id={shared id} editorHeight="400px" responseHeight="300px">`
But I think this would be more tedious to work with. 
- Add a feature to set the height of the embed and let it decide by itself what amount of that height should be distributed between response and result. 
For example `<Embed id={shared id} height="700px">`
This would be easier to work with, but will take a bit more time to implement.
I don't want to block this PR with presentation issues, so I'll get on it ASAP.

**Comment by crjm** [comment]
I spent a few hours trying to implement the automatic height based on the content of each element with no luck. I'm going with the first alternative ASAP as I don't want to block this PR.

I've analyzed another solution for this requirement, which is [**making the embed resizable by the user**](https://github.com/dagger/dagger/issues/4710). GraphiQL has a hook to allow this, but [it breaks our editor layout](https://github.com/graphql/graphiql/blob/5cf77e0513a65459deaa95e8dcf9ea15e582e2d0/packages/graphiql-react/src/utility/resize.ts#L111). It's a shame because besides that, it worked straight away.
However, I think allowing the user to set their preferred height ratio of editor/response is a good UX improvement, so will add it to my backlog and do a custom implementation.

**Pull request merged**
