### PR TITLE
Spike: host-to-container networking

### PR DESCRIPTION
**Pull request by vito**
Adds the following API:

```graphql
extend type Container {
  withExposedPort(
    # ...
    "Make this port reachable via the given port on the host"
    publish: Int
  )
}
```

Whenever a service runs, either via `run` (#4723) or `withServiceBinding`, the Dagger session will listen on any published ports and forward traffic to the container via the shim.

Note that this is a distinct behavior of `run` as opposed to `exitCode`/`stdout`/`stderr`.

### CODE REVIEW

**Review by sipsma — COMMENTED** [review]
Awesome! Left a few minor comments, looks great overall!

My only broad nit-pick is that there *might* be some performance benefits to using the socket session attachable mechanism instead of proxying through stdio pipe of gateway containers. The idea being that when a container is spun up that publishes a port, there will be a unix socket provided that is "intercepted" by the shim when it is updating the bundle and it uses that to proxy the connection instead of stdio pipes.

The main possible benefit is that it avoids the need to spin up a new container every time a connection is made on the host. It also avoids having to go through pipes, which I'm sure work fine but have weird limitations around the maximum size of a single read/write and a relatively low default buffer size (IIRC) as compared with socket defaults.

That being said, I highly doubt that this would be noticeable for most straightforward use cases, probably only makes a difference for relatively high load scenarios (which are probably rare), so this isn't a blocker at all. If this approach is about the same complexity as the existing one and you feel like trying it maybe it's worth a shot, but otherwise not a big deal at all. Super excited to have the feature in place!

**Comment by vito** [comment]
@sipsma Would definitely like to avoid the container-per-request overhead. Just threw something together for tomorrow's demo. An earlier iteration just did `docker exec -i dagger-engine.dev socat - tcp:hostname:port` so the new approach is slightly better. :joy: 

I don't quite grok how to use the SSH socket attachable yet but I can take a deeper look. I considered it briefly but it seemed more suited for proxying in the other direction (container -> host), and it didn't seem like there was much I could re-use, but I might be missing something.

I'm currently running into a weird issue where after a handful of connections it hangs trying to start the proxy process. It's able to create the container, but the Container.Start call hangs. Not sure why yet, but all the more reason to use something more lightweight. Hopefully it doesn't happen in the demo. :sweat_smile:

**Comment by sipsma** [comment]
> I don't quite grok how to use the SSH socket attachable yet but I can take a deeper look. I considered it briefly but it seemed more suited for proxying in the other direction (container -> host), and it didn't seem like there was much I could re-use, but I might be missing something.

Ah yeah I was thinking the shim could call connect on the unix socket and then the client-side of the session attachable blocks until a connection on it's client-side listener is made, at which time it will accept the connection and start copying between the two, but I just realized that because we aren't the ones directly calling accept on the unix socket in the server, buildkitd code is, we can't implement that blocking behavior we'd need... There's probably ways of getting it to work but it would become a mess.

That's sad but not a big deal since it seems like you got the gateway container idea working fully. The only other possibility I can think of is to maybe add our own session attachable implementation and see if we could use that somehow (plausible now that we control both client and server) but that's way way too complicated to be worth it for now, so never mind :-)

**Comment by marcosnils** [comment]
> The distinction between "exposing" and "publishing" a port was... not a highlight of the Docker UX, and I am not eager to perpetuate the problem in Dagger

Interesting to know.. FWIW I never personally found or heard in the wild that the `publish` UX caused that many issues. It's funny to see that even all the other container orchestrators like k8s and nomad also used the same design.

**Comment by shykes** [comment]
> Interesting to know.. FWIW I never personally found or heard in the wild that the `publish` UX caused that many issues. It's funny to see that even all the other container orchestrators like k8s and nomad also used the same design.

That’s the thing, `publish` doesn’t cause issues because nobody uses it anymore for development or prod. It’s often hidden away and basically disabled by wrappers, including of course kubernetes. Even in compose you typically configure port mapping in the yaml.

In the early days it was similar to ‘cmd’ and ‘entrypoint’: which is which? Then later the problem became more fundamental: publish where? We had plans to extend the publish concept beyond “a nat rule on the local host”, add a new extension point so that you could eg. publish your port on a firewall, punch holes through your VPC, register a route on an http proxy. But the ecosystem was already fragmenting, the various wrappers just wanted docker to be a dumb single-host runner while they fought each other with incompatible extension points… So Docker gave up on unifying the ecosystem around the engine API and shipped its own wrapper. ‘publish’ remained a single-host concept, impossible to extend. And gradually became irrelevant, like ONBUILD, links etc.

So, I think the same question is relevant in our case: ‘publish’ where? It’s not intuitive that the answer is always ‘on the client host’. Especially since we have `container { publish }` with a very different answer.

**Comment by vito** [comment]
> Especially since we have `container { publish }` with a very different answer.

Haha, I completely forgot about that. Definitely worth avoiding the term "publish" then.

Shower thought: maybe this is where we bring `Socket` back into the fray?

```graphql
extend type Container {
  "Returns a Socket routing to the specified port, or the first exposed port if unspecified."
  socket(port: Int): Socket!
}

extend type Socket {
  "Binds the socket in the host address space."
  bind(
    address: String!,
    family: NetworkFamily=INET, # or UNIX?
  ): Proxy!
}

type Proxy {
  close: Void!
}
```

Just a sketch. Things I like:

* Parallels between `Container.Endpoint` and `Container.Socket` (selecting the default port)
* Parallels to [`bind(2)`](https://man7.org/linux/man-pages/man2/bind.2.html) (takes an existing socket and binds it to an address space)
* Supports mounting a service's socket into a client container as a Unix socket via `Container.WithMountedSocket`
* Supports mounting a service's socket to the host as a Unix socket (family=UNIX)
* Integrating `Socket` into the rest of the API, which has been kind of on its own since its introduction

Things that are weird:

* Supports binding a Host Unix socket to another address.

Things I don't like:

* Having to add a whole new `Proxy` type just to be able to stop the proxy. I could have made `reverseProxy` just block and return `Void!` and have the client cancel the request to stop it, but I'd rather give client have a guarantee that the address is bound when the API returns to avoid race conditions.

This might be a narrower slice of what you accomplished with the earlier Proxy proposal though.

> As a strawman, I would like to bring back [my original suggestion from the API draft](https://github.com/dagger/dagger/pull/4163/files#diff-4242183254eaee9649c3ed82114bd292d61bd23a0d7b2ff701c3bb16d3fb8fabR22-R90). Basically it makes explicit the concept of proxy services. In the initial proposal, proxy services and [container services](https://github.com/dagger/dagger/pull/4163/files#diff-c1d87d955754323d0c8fe207595b3d6860abbbf4d79083a34c2351a297c5d369R170-R175) had a common type, `Service`, which I found elegant. I'm now realizing that by slicing up the design, and removing the `Service` type in the c2c slice, we may have closed that door...

FWIW, I don't think any door needs to stay closed - we're pre-1.0 after all, and if addressing the rest of networking requires a more fleshed-out API, to me any change is on the table. There just needs to be enough carrot with the stick, and h2c networking seems like as good a carrot as any.

I liked the symmetry that you found between the Proxy and Service, but I also like where we ended up without it, where services are really just inter-networked containers. We didn't end up needing them to fulfill a Service interface, and decided to avoid explicit service lifecycle management as much as we can. One way of looking at it is we chose to align Containers with Services rather than align Services with Proxies.

**Comment by shykes** [comment]
> I liked the symmetry that you found between the Proxy and Service, but I also like where we ended up without it, where services are really just inter-networked containers. We didn't end up needing them to fulfill a Service interface, and decided to avoid explicit service lifecycle management as much as we can. One way of looking at it is we chose to align Containers with Services rather than align Services with Proxies.

I think the main benefit of a common `Service` type, backed by either `container { service }` or `host { proxy }` would be to avoid having both `container { withContainerServiceBinding }` and `container { withProxyServiceBinding }` just because there are two different bindable types.

**Comment by shykes** [comment]
> I think the main benefit of a common `Service` type, backed by either `container { service }` or `host { proxy }` would be to avoid having both `container { withContainerServiceBinding }` and `container { withProxyServiceBinding }` just because there are two different bindable types.

Possible alternative solution: `host { proxy }` returns a `Container`, which can be bound the usual way.

- Upside: no extra type, only one way to bind
- Downside: more complicated implementation under the hood; we’re kind of lying because technically the proxy isn’t a container, and consequently its implementation of most container fields would probably have to return an error. No rootfs, no env variables, etc.

I think I still prefer adding `container { service }: Service!` and `host { proxy }: Service!`

**Comment by verdverm** [comment]
+1 for networking upgrades, I need to be able to talk to host containers from dagger

**Pull request closed without merging**
