### PR TITLE
fix: Improve validation around `#DecodeSecret`

### LINKED ISSUE #2789: 🐞 Panic when validating plan on secret types that unify with a decoded secret value
### What is the issue?

When you pass a decoded secret to a `dagger.#Secret` field, the validator panics.

Essentially this:

```cue
token: dagger.#Secret & decode.output.apiToken.contents
```

When checking for core types, we need to do it only if it's a struct:

```go
	// Core types (FS, Secret, Socket): make sure they are references, otherwise abort.
	case plancontext.IsFSValue(v) || plancontext.IsSecretValue(v) || plancontext.IsSocketValue(v):
```

As a workaround for now there's ways to avoid this situation, but no immediate general recommendation.

### Log output

```console
panic: not properly initialized (state: unprocessed, value: <nil>)

goroutine 1 [running]:
cuelang.org/go/cue.makeValue(0x10197b2d8?, 0x101970948?, 0x14000ed9560?)
        /Users/helder/go/pkg/mod/github.com/dagger/cue@v0.4.1-rc.1.0.20220121023213-66df011a52c2/cue/types.go:668 +0xc8
cuelang.org/go/cue.Value.LookupPath({0x140003c3d50?, 0x14000ed94d0?, 0x0?}, {{0x140003eb830?, 0x14000680000?, 0x140011ee160?}})
        /Users/helder/go/pkg/mod/github.com/dagger/cue@v0.4.1-rc.1.0.20220121023213-66df011a52c2/cue/query.go:77 +0x4a0
go.dagger.io/dagger/compiler.(*Value).LookupPath(0x140011ee140, {{0x140003eb830?, 0x14000ed94d0?, 0x140003c3d50?}})
        /Users/helder/Projects/dagger/compiler/value.go:63 +0xf4
go.dagger.io/dagger/plancontext.IsFSValue(0x140011ee140?)
        /Users/helder/Projects/dagger/plancontext/fs.go:22 +0x3c
go.dagger.io/dagger/plan.isPlanConcrete(0x14000001611?, 0x140011ee140)
        /Users/helder/Projects/dagger/plan/validate.go:76 +0xd4
go.dagger.io/dagger/plan.isPlanConcrete(0x14000000681?, 0x14001201f80)
        /Users/helder/Projects/dagger/plan/validate.go:113 +0x400
go.dagger.io/dagger/plan.isPlanConcrete(0x14000001634?, 0x140010f03a0)
        /Users/helder/Projects/dagger/plan/validate.go:113 +0x400
go.dagger.io/dagger/plan.isPlanConcrete(0x14000001651?, 0x140010f0180)
        /Users/helder/Projects/dagger/plan/validate.go:113 +0x400
go.dagger.io/dagger/plan.isPlanConcrete(0x140000006d1?, 0x1400083ffe0)
        /Users/helder/Projects/dagger/plan/validate.go:113 +0x400
go.dagger.io/dagger/plan.isPlanConcrete(0x14000aff280?, 0x1400083f400)
        /Users/helder/Projects/dagger/plan/validate.go:113 +0x400
go.dagger.io/dagger/plan.(*Plan).validate(0x14001188540, {0x101979228, 0x14000b33a40})
        /Users/helder/Projects/dagger/plan/plan.go:272 +0xc0
go.dagger.io/dagger/plan.Load({0x101979228, 0x14000b339e0}, {{0x14000b75420, 0x1, 0x1}, {0x1023d4e38, 0x0, 0x0}, {0x0, 0x0}, ...})
        /Users/helder/Projects/dagger/plan/plan.go:91 +0x5d4
go.dagger.io/dagger/cmd/dagger/cmd.loadPlan({0x101979228, 0x14000b339e0}, {0x16fa1f73d, 0x16})
        /Users/helder/Projects/dagger/cmd/dagger/cmd/do.go:281 +0x13c
go.dagger.io/dagger/cmd/dagger/cmd.glob..func2(0x10236f3c0, {0x14000aff3c0, 0x3, 0x4})
        /Users/helder/Projects/dagger/cmd/dagger/cmd/do.go:83 +0x2a8
github.com/spf13/cobra.(*Command).execute(0x10236f3c0, {0x14000aff3c0, 0x3, 0x4})
        /Users/helder/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x10236fdc0)
        /Users/helder/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/helder/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /Users/helder/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
go.dagger.io/dagger/cmd/dagger/cmd.Execute()
        /Users/helder/Projects/dagger/cmd/dagger/cmd/root.go:96 +0x398
main.main()
        /Users/helder/Projects/dagger/cmd/dagger/main.go:8 +0x20
exit status 2
```

### Steps to reproduce

```cue
package main

import (
	"encoding/yaml"
	"dagger.io/dagger"
	"dagger.io/dagger/core"
	"universe.dagger.io/bash"
)

dagger.#Plan & {
	actions: {
		write: core.#WriteFile & {
			input:    dagger.#Scratch
			path:     "/secret"
			contents: yaml.Marshal({
				apiToken: "foobar"
			})
		}

		secret: core.#NewSecret & {
			input: write.output
			path:  "/secret"
		}

		decode: core.#DecodeSecret & {
			input:  secret.output
			format: "yaml"
		}

		test: #Run & {
			token: decode.output.apiToken.contents
		}
	}
}

#Run: {
	token: dagger.#Secret

	_run: bash.#RunSimple & {
		env: TOKEN:       token
		script: contents: "echo -n $TOKEN > /out"
		export: files: "/out": _
		always: true
	}

	verify: _run.export.files."/out"
}
```

### Dagger version

dagger devel (31b0522df) darwin/arm64

### OS version

macOS 12.4

/cc @marcosnils @rawkode

### PR DESCRIPTION
**Pull request by helderco**
Fixes #2789

The following issues were fixed in turn:

1. Fix panic while checking core type;
2. Fix undefined field error for `dagger.#Secret & decoded.output.FOO.contents` references;
3. Improve error message when making a typo with exec env.

Signed-off-by: Helder Correia

\cc @rawkode @marcosnils

### CODE REVIEW

**Comment by grouville** [comment]
@helderco, what shall we do about the two validation PRs ? I'm interested in getting it done, at least for the LSP. If it's not your priority anymore, could you please share context with me, I'll try to finish them up 😇

**Comment by gerhard** [comment]
This continues to be on hold. If anyone is able to pick it up this week or next, you are welcome to it. Alternatively, I intend to load context the week beginning August 15.

**Comment by helderco** [comment]
> @helderco, what shall we do about the two validation PRs ? I'm interested in getting it done, at least for the LSP. If it's not your priority anymore, could you please share context with me, I'll try to finish them up 😇

I've commented on the [other PR](https://github.com/dagger/dagger/pull/2777), I'll explain where this one stands.

# Overview

Our `#DecodeSecret` is flexible but hard to get along with the rest of the code. It has a recursive structure, which can only be known at runtime. We validate during load, so keep this in mind.

When a value is validated, it passes the checks for core types in:

https://github.com/dagger/dagger/blob/1ea907b30bbf45468de6a9225948da16b85a3509/plan/validate.go#L75-L76

Those checks are very simple and just call `LookupPath()`:

https://github.com/dagger/dagger/blob/1ea907b30bbf45468de6a9225948da16b85a3509/plancontext/fs.go#L21-L23

There's a situation in #2789 where a `BottomKind` value from a _decoded secret_ is passing through that check and hitting a **not properly initialized** panic:

```go
func makeValue(idx *runtime.Runtime, v *adt.Vertex, p *parent) Value {
	if v.Status() == 0 || v.BaseValue == nil {
		panic(fmt.Sprintf("not properly initialized (state: %v, value: %T)",
			v.Status(), v.BaseValue))
	}
	return Value{idx, v, p}
}
```

https://github.com/cue-lang/cue/blob/b4d1b16ccf8944599eec6870da400d2b56da979b/cue/types.go#L672-L678

# Problem

I have not been able to correctly detect a value that isn't properly initialized when we check for the core types, so I instead added a check for a struct, since all core types are structs:

```diff
-	return v.LookupPath(fsIDPath).Exists()
+ 	return v.IncompleteKind() == cue.StructKind && v.LookupPath(fsIDPath).Exists()
```

This fixed the panic issue in #2803 🎉 with the `env` use case:

https://github.com/dagger/dagger/blob/d273ceacbc87183b7db799211a099b1e653393cd/tests/tasks/decodesecret/type.cue#L33-L38

But broke the `mount` use case 😭:

https://github.com/dagger/dagger/blob/d273ceacbc87183b7db799211a099b1e653393cd/tests/tasks/decodesecret/mount.cue#L35-L44

The reason is that that's a **properly initialized `BottomKind` value** that was **previously going through the core type checks with success**, so now it's going to the "last resort" `BottomKind` catch all instead:

https://github.com/dagger/dagger/blob/1ea907b30bbf45468de6a9225948da16b85a3509/plan/validate.go#L118-L126

Which shows a bunch of `undefined field` errors for your `#DecodeSecret` fields.

# Workaround (not ideal) 😞 

As a workaround I added a new check to weed out values referencing a child of a generated value:

https://github.com/dagger/dagger/blob/d273ceacbc87183b7db799211a099b1e653393cd/plan/validate.go#L140-L146

The idea is that if a value is a reference like so:

```cue
token: dagger.#Secret & decode.output.apiToken.contents
```

Then strip components until you find a generated value, which means it can't be known during load (at least with `#DecodeSecret` you can't know if `apiToken` is valid or not):

1. `decode.output.apiToken.contents` ❌ 
2. `decode.output.apiToken` ❌ 
3. `decode.output` ✅ 

In which case, skip the `undefined field` error.

This fixed all the `#DecodeSecret` tests 🎉, but broke some other tests 😭(e.g., in Netlify).

# Paths to enlightenment 🧘 

- Pick the `dagger.#Secret &` from above and just assume it's a secret (core type), but it doesn't account for more complex expressions (which may include disjunctions and nested conjunct expressions) 👎
- Try to drill down the expression recursively until you untie that knot enough so you can return `true` (which is where I left it at locally) 🤔
- Find some other simple way to match a `#DecodeSecret.output` type to simply a `dagger.#Secret` 🚀
- Just try to detect the uninitialized value early on in a simple way 🥳

**Comment by helderco** [comment]
To be complete, I started manipulating `isCoreOutputReference` to be recursive and drill down the expressions, but didn't finish it.

```diff
diff --git a/plan/validate.go b/plan/validate.go
index e37d5d2e..b7fdb7ee 100644
--- a/plan/validate.go
+++ b/plan/validate.go
@@ -1,6 +1,7 @@
 package plan
 
 import (
+	"fmt"
 	"strings"
 
 	"cuelang.org/go/cue"
@@ -56,23 +57,56 @@ func isDockerImage(v *compiler.Value) bool {
 func isCoreOutputReference(v *compiler.Value) bool {
 	_, expr := v.Expr()
 
-	for _, i := range expr {
+	// fmt.Printf("[[ Root: %s; Sels: %d ]]\n", v.Path(), len(expr))
+
+	// if src, err := v.Source(); err == nil {
+	// 	fmt.Printf("vvvvvv [%s]\n%s\n^^^^^^\n", v.Kind(), src)
+	// }
+
+	for k, i := range expr {
+		fmt.Printf("\n[[ Root: %s; Sels: %d; Index: %d ]]", v.Path(), len(expr), k)
+		// if src, err := i.Source(); err == nil {
+		// 	fmt.Printf(" ==> %s", src)
+		// }
+		fmt.Println()
+
 		rv, rp := i.ReferencePath()
 		sel := rp.Selectors()
 
+		// op, _ := i.Expr()
+		if isCoreOutputReference(rv) {
+			return true
+		}
+
+		// if src, err := rv.Source(); err == nil {
+		fmt.Printf("\n[ Path: %s; Sels: %d ]\n\n", rp, len(sel))
+		// }
+
 		for k := range sel {
 			sp := cue.MakePath(sel[0 : len(sel)-1-k]...)
 
+			fmt.Printf(" %d ~~~ %s\n", k, sp)
+
 			if rv.LookupPath(sp).HasAttr("generated") {
+				fmt.Println(" YUP! ")
 				return true
 			}
 		}
 	}
 
+	// if src, err := v.Source(); err == nil {
+	// 	fmt.Printf("vvvvvv [%s]\n%s\n^^^^^^\n", v.Kind(), src)
+	// }
+
+	fmt.Println(" NOPE! ")
 	return false
 }
```

As I said, I don't like this approach. I'd rather find a smarter way to detect these cases but I lost a lot of time on that! 😮‍💨

**Comment by marcosnils** [comment]
cc @helderco is this still relevant?

**Pull request closed without merging**
