### PR TITLE
docs: Promote version zenith docs to current

### PR DESCRIPTION
**Pull request by vikram-dagger**
This commit deletes the `current` version of the docs and replaces it with `zenith`.

### CODE REVIEW

**Comment by vikram-dagger** [comment]
@crjm this PR deletes version `zenith` and changes the docs to `current`. The guide plugin is erroring out since it is expecting to find a `zenith` version. I have tried to comment out the related changes in the plugin but even after this I continue to see an error. Can you help?

```
TypeError: Cannot read properties of undefined (reading 'forEach')
    at /home/vikram/public/vikram.dagger/docs/plugins/docusaurus-plugin-guides/index.js:96:32
    at Array.forEach (<anonymous>)
    at Object.loadContent (/home/vikram/public/vikram.dagger/docs/plugins/docusaurus-plugin-guides/index.js:95:21)
    at /home/vikram/public/vikram.dagger/docs/node_modules/@docusaurus/core/lib/server/plugins/index.js:35:51
    at Array.map (<anonymous>)
    at loadPlugins (/home/vikram/public/vikram.dagger/docs/node_modules/@docusaurus/core/lib/server/plugins/index.js:34:53)
    at async load (/home/vikram/public/vikram.dagger/docs/node_modules/@docusaurus/core/lib/server/index.js:76:58)
    at async Command.start (/home/vikram/public/vikram.dagger/docs/node_modules/@docusaurus/core/lib/commands/start.js:44:19)

[INFO] Docusaurus version: 3.0.1
Node version: v18.16.0
```

**Comment by vikram-dagger** [comment]
@TomChv can you please see https://github.com/dagger/dagger/actions/runs/8061192344/job/22018503221?pr=6750 and make the necessary change in the TS SDK generation? It would be better to make that a separate PR though.

**Comment by TomChv** [comment]
About the lint error in `Docs/lint`, there error comes from : https://github.com/vikram-dagger/dagger/blob/b800e4b5264698c522e19f39423490cd6de73bb5/core/schema/container.go#L67-L68

But I don't really know how to fix it, because to me, it's more a false positive than an actual error.

**Comment by TomChv** [comment]
I updated the [vikram-dagger/dagger@b800e4b/core/schema/container.go#L67-L68](https://github.com/vikram-dagger/dagger/blob/b800e4b5264698c522e19f39423490cd6de73bb5/core/schema/container.go#L67-L68) to be compliment with the linter. everything should be fine now.

**Comment by TomChv** [comment]
Ok all linters are good except Python!
@vikram-dagger please double I didn't broke or rollback anything in our doc while I was fixing everything and we should be good to go after everything is green.

**Review by jedevc — APPROVED** [review]

**Comment by vikram-dagger** [comment]
Note: After merging and making the new docs live, the Algolia index needs to be emptied and the site recrawled. FYI @gerhard @slumbering

**Review by gerhard — APPROVED** [review]
Getting this live shortly 🚀

**Comment by gerhard** [comment]
New docs are now live. Next: kicking off recrawl.

image

**Comment by gerhard** [comment]
Search index updated:
image

**Pull request merged**
