### PR TITLE
chore: bump next version to v0.15.0

### PR DESCRIPTION
**Pull request by jedevc**
Next release is going to be v0.15.0, with some exciting changes.

### CODE REVIEW

**Comment by jedevc** [comment]
Should also update `future_test.go` and shepherd those tests into the main suite.

**Comment by jedevc** [comment]
Hm, the daggerverse preview has failed @gerhard :thinking:

```
Error: response from query: input: daggerverse.deployPreviewWithDaggerMain resolve: call function "DeployPreviewWithDaggerMain": process "/runtime" did not complete successfully: exit code: 2

Stdout:
invoke: GET https://api.github.com/user: 401 Bad credentials []
```

It definitely shouldn't be triggering on PRs (creds aren't available) - but I'm not quite sure that it *should* trigger on `.changes/.next` even on main - I'm just bumping to the next version here. We want it to trigger on the PR right before the release.

We could trigger it on a new markdown file in `.changes/`? That would be the case we care more about.

**Review by marcosnils — APPROVED** [review]

**Comment by jedevc** [comment]
Will fix https://github.com/dagger/dagger/pull/9073.

**Comment by jedevc** [comment]
Failure is known failure from https://github.com/dagger/dagger/pull/9094, merging now to get release pieces started :tada:

**Pull request merged**
