### PR TITLE
feat: added npm pkg

### PR DESCRIPTION
**Pull request by troncoso**
Signed-off-by: Noah Troncoso <noah.troncoso@gmail.com>

Note this is pretty much an exact copy of the yarn package. There were just a couple tweaks to make it work for npm

### CODE REVIEW

**Comment by jpadams** [comment]
@troncoso I'm re-running tests.

**Comment by grouville** [comment]
@troncoso, are you using it for one of your projects ? 

@gerhard, WDYT ? As it is a copy of the `yarn` package, it has the same design flaws: hard to debug for example

**Review by grouville — DISMISSED** [review]
LGTM. Thanks for this contribution 😇

**Review by grouville — APPROVED** [review]
Tested locally: it works fine. I moved the package to the `alpha` section

**Pull request merged**
