### PR TITLE
Node.js SDK - Improve ref docs readability

### PR DESCRIPTION
**Pull request by slumbering**
Update css only for node.js docs reference page. Use the latest Dagger UI Library 
- Bring back font family Montserrat only for Title
- Enhance title spacing
- Enhance code readability

Before:
docs dagger io_current_sdk_nodejs_reference_modules_api_client_gen

After:
deploy-preview-4275--devel-docs-dagger-io netlify app_current_sdk_nodejs_reference_modules_api_client_gen

Signed-off-by: jffarge <jf@dagger.io>

### CODE REVIEW

**Review by TomChv — APPROVED** [review]
Looks way better this way! LGTM 🚀

**Comment by vikram-dagger** [comment]
LGTM!

**Comment by helderco** [comment]
Looks better! I think the gray background on `monospace` text looks better in the rest of the website as well, instead of the black background.

**Comment by slumbering** [comment]
> Looks better! I think the gray background on `monospace` text looks better in the rest of the website as well, instead of the black background.
> 
> * [Docs: Enhance code readability #4299](https://github.com/dagger/dagger/issues/4299)

Yes you've red in our mind :D ! We've planned to apply those updates to the whole website. Thanks for the issue 🙏

**Pull request merged**
