### PR TITLE
Python: migrate back to hatch

### PR DESCRIPTION
**Pull request by helderco**
When we were getting ready to launch the Python SDK in https://github.com/dagger/dagger/pull/3730 I was having a few issues with Hatch so I migrated to Poetry at the last minute. It gave a bit more control and lock file support, but I preferred a package manager that followed standards more closely.

Moving back to hatch is motivated mostly by wanting to follow standards and to simplify things a bit more. This was revisited while working on #5300.

Lock file support is not as important because we want the latest packages in development to catch any issues that people may have, but just added a `hatch run lock` command to create a `requirements.txt` with pinned versions to use in CI to avoid unrelated PRs to fail on Python actions.

The `requirements.txt` file is named thus to make integration with dependabot easier.

### CODE REVIEW

**Review by gerhard — APPROVED** [review]
I makes me very happy to see a PR that removes more lines than it introduces, without changing the functionality 🙌

Everything looks great, appreciate you keeping the `requirements.txt` functionality. Pinning deps is super important, before `go.sum`, `yarn.lock` & `Gemfile.lock`,  I used to spend too much time dealing with loose dependency versions causing havoc at the worst possible moment (solid CI practices & containerisation were not as popular back in the day).

Anything to follow-up from https://dagger.io/blog/ruff ?

**Comment by helderco** [comment]
> Anything to follow-up from https://dagger.io/blog/ruff ?

Yeah, I've considered switching from ignore rules to select rules to avoid lint failures and the need to update but I still think it's better to let it push for continuous updates. I always have the latest ruff-lsp in the IDE anyway.

**Comment by gerhard** [comment]
Missed one (in two places):
- https://github.com/dagger/dagger/actions/runs/5446415094/jobs/9907397123#step:10:18
- https://github.com/dagger/dagger/actions/runs/5446415094/jobs/9907396539#step:8:21

Want to PR follow-up @helderco?

**Comment by helderco** [comment]
@gerhard Ah, I looked for the provisioning stuff by navigating the file system, and it doesn't show when I search for "poetry" in Live Grep, maybe that doesn't see hidden files, so must have thought that we weren't using that anymore.

I'm on it now. Unfortunately that's the part of CI that requires "fix CI" commits right? No way to test other than merge to main?

**Pull request merged**
