### PR TITLE
docs: add connhelper instructions

### LINKED ISSUE #1959: 🐞 Can't connect to docker daemon when using nerdctl
### What is the issue?

I use nerdctl with buildkit and containerd (Rancher Desktop) to normally build, tag and push my "docker" images (OCI compatible). If I want to use the docker Dagger step as mentioned in the "quick start" [here](https://docs.dagger.io/), I get the error that it couldn't connect to the docker daemon. I was told to create this issue by helderco#4068 in Discord.

### Log output

`11:09AM ERR failed to run docker: exit status 1    output=Client:
 Context:    default
11:09AM ERR failed to run docker: exit status 1    output=Client:
 Context:    default
 Debug Mode: falseuildx (Docker Inc., v0.7.1)
 Plugins:: Docker Compose (Docker Inc., v2.2.3)
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.16.0)
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Server:pretty printing info
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info`

### Steps to reproduce

1. Use Rancher Desktop and get use nerdctl as your building tool.
2. Alias docker to nerdctl.
3. Try to build with dagger `dagger do build` in https://github.com/dagger/dagger/pkg/universe.dagger.io/examples/todoapp

### Dagger version

0.2.4

### OS version

macOS 11.6.4

### PR DESCRIPTION
**Pull request by jcdickinson**
Adds documentation for podman and kube-pod to operator-manual. Resolves #1959

Signed-off-by: Jonathan Dickinson <jdickinson@cmgx.io>

### CODE REVIEW

**Review by aluzzardi — APPROVED** [review]
Thank you for the contribution, @jcdickinson!

LGTM, waiting for CI to pass

**Comment by aluzzardi** [comment]
Markdown linter is failing, can you look into that?

You can repro locally with `dagger do lint markdown`

**Comment by jcdickinson** [comment]
> You can repro locally with `dagger do lint markdown`

Doesn't inspire much confidence if I don't lint before pushing :/

**Review by gerhard — APPROVED** [review]
Thank you for this @jcdickinson!

We are currently working on making it clearer that these are the 0.1 docs which are now deprecated. cc @slumbering

Even if this contribution is for deprecated docs, we will merge it - thank you! If you want to add this to the new docs, you can follow https://github.com/dagger/dagger/tree/main/docs#how-can-i-add-a-new-doc-page to create a new doc page. I think that adding under **Guides** makes most sense. cc @shykes 

🚀

**Pull request merged**
