### PR TITLE
[wip] support remote client sessions

### PR DESCRIPTION
**Pull request by vito**
This is nowhere near ready but I wanted to put a PR up early.

* Adds an endpoint for initializing a client session.
* `dagger.Connect` now initializes a session and keeps it open for the duration of the client.
* The client session endpoint hijacks the connection and uses it to serve gRPC services from the client.
* Subsequent queries are associated to the session via `/query?session=<id>`.
* Schema endpoints look up the session's gateway by ID (lazily instantiated for now; implementation detail).
* Gateways are initialized with a `session.Attachable` that proxies back to the client's session.
* Removes the global gateway session; everything uses the client session instead.

The end result is that it's possible to run the Engine in a Docker container and sync files from the client's host. No API changes necessary. :tada: 

To try it out:

```sh
docker buildx build . -t cloak
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -p 8080:8080 cloak dev
go run ./cmd/remotesync
```

TODO:

* [ ] Figure out how to integrate https://github.com/mwitkow/grpc-proxy/pull/62 to support the auth service
* [ ] Decouple SDK from `github.com/moby/buildkit` dependency
    * this probably means vendoring + cutting down `github.com/moby/session/*` implementations, which we've already almost done for `filesync`
    * alternatively we can just put this all in a binary and have the Go SDK use the binary in the same way the other SDKs would
* [ ] Figure out what to do with the secret attachable
* [ ] Support forwarding Docker auth
* [x] Support forwarding export calls
* [ ] Try more things
* [ ] Remove `cmd/remotesync` (it's just a testing crutch)
* [ ] Preserve attribution for code yoinked from Buildkit
* [ ] Make sure `--disable-host-rw` is still respected
* [ ] Fix Yarn example (JS SDK needs to implement session)

### CODE REVIEW

**Comment by aluzzardi** [comment]
🎉 🎉 🎉

wow, this is incredibly amazing. I thought we were *months* away from having this.

I only skimmed through the code, need to spend more time on this, but ... so many questions :)

> alternatively we can just put this all in a binary and have the Go SDK use the binary in the same way the other SDKs would

Yep, good point. I'm wondering what the binary size would be. @sipsma this might re-open up the topic of how we distribute the binaries long term?

- We might not have docker locally (since the engine can now be wherever)
- The binary MIGHT be small enough to have an acceptable size to be packaged in the SDK directly

**Comment by vito** [comment]
> I only skimmed through the code, need to spend more time on this, but ... so many questions :)

A lot of it is yoinked from Buildkit and stripped for parts. The hard part was figuring out how exactly to glue it together. :sweat_smile: Lots of confusion around whether something is client-side or server-side, and lots of things that looked promising but were dead ends.

Some key parts:

* https://github.com/moby/buildkit/blob/ac4f39aaad34da48855d0beb2785a0666c68b895/session/manager.go
* https://github.com/moby/buildkit/blob/ac4f39aaad34da48855d0beb2785a0666c68b895/session/session.go#L101
* https://github.com/moby/buildkit/blob/ac4f39aaad34da48855d0beb2785a0666c68b895/session/grpc.go#L29

Need to preserve proper attribution for all this.

**Comment by vito** [comment]
So, we're not totally out of the woods yet. This lets us get files _in_ to Dagger but it doesn't help us get them _out_.

As @sipsma pointed out in https://github.com/dagger/dagger/pull/3421#issuecomment-1288327419, exporting currently requires establishing a new gateway session. There's an upstream issue to add exporting to the gateway interface: https://github.com/moby/buildkit/issues/1914.

Unless I'm missing something, this seems like a decent chunk of work to implement. Currently exporting works by registering a _single_ `FileSend` (vs `FileSync`) gRPC service which is pre-configured with the destination for the data it receives. To support exporting via the gateway API we'd probably need a way to dynamically configure destinations per-export instead, and it'd need to support mixed export types (OCI vs Tar vs Local).

The sad thing is even with that implemented we wouldn't really get remote exporting "for free" because we currently have to deal both OCI and Local export types in engine, and I don't think we'd want to bubble that complexity up to each SDK. I think we might just want to come up with our own gRPC service interface for exporting to paths. The engine can then internally do whichever export type is appropriate and then translate it to a direct gRPC client call using the session's underlying `*grpc.ClientConn`.

The silver lining is that we could do this without actually being blocked on upstream changes by re-using the underlying `*grpc.ClientConn` across multiple gateway sessions. That way SDK implementations stays simple (just one client session). The disadvantage is that it won't fix underlying reproducibility issues, but it's nice to decouple these things, since we're already tracking that in #3613.

**Comment by vito** [comment]
Updates:

* Exporting files to the host has been implemented. The engine no longer uses `ExporterLocal`, instead it uses `ExporterTar` and sends a tar stream to the SDK which unpacks it as it streams.
* Exporting a container sends a tar stream with `unpack: false` so it gets written to a single `.tar` file client-side as before.
* The global `*core.Host` instance has been removed. Instead host APIs use a dynamic `*core.Host` from the client session. This paves the way for supporting `host { envVariable }` & etc.
* The engine is no longer configured with `Workdir`/`ConfigPath`/`NoExtensions`. Instead the SDK client installs extensions as part of setup when they are configured. This eliminates the sanity checks from the Unix/TCP connectors that had to be disabled in #3674.
* Go SDK tests now are passing with Dagger-in-Dagger, including the Workdir test which was problematic before.
* All core integration tests are passing.
* All but one extension test is passing. The remaining failure is `TestExtensionYarn` which needs the NodeJS SDK to be able to establish sessions. Fixing this will either mean a native NodeJS implementation of the required gRPC services (hard) or shelling out to a helper binary (easier).

**Comment by dolanor** [comment]
> Go SDK tests now are passing with Dagger-in-Dagger, including the Workdir test which was problematic before.
This is amazing!

**Comment by vito** [comment]
Closing now that we know that we can, but have decided that we shouldn't (for now). Most of the time was spent figuring out how to do this; now that we know how it'll be easier to just redo it on `main` when we want to rather than try to rebase or maintain a branch.

**Pull request closed without merging**
