### PR TITLE
Pull+push all image config.

### LINKED ISSUE #3170: 🐞 ENTRYPOINT/CMD data lost during Dagger image build
### What is the issue?

The default entrypoint/cmd of a base image is lost when that image is used in a Dagger image build process.

### Log output

_No response_

### Steps to reproduce

Running standard PHP image:
```
$ docker run  php:8.1-apache
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
[Sat Sep 17 06:11:06.065706 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) PHP/8.1.9 configured -- resuming normal operations
[Sat Sep 17 06:11:06.065751 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

Building new image based on above image, making no changes, pushing it to registry and running it:

```
query {
  core {
    image(ref: "php:8.1-apache") {
      pushImage(ref:"xxx/testrepo:latest")
    }
  }
}

$ docker run  xxx/testrepo
docker: Error response from daemon: No command specified.
See 'docker run --help'.
```

### Dagger version

cloak devel (97205d987) linux/amd64

### OS version

Linux  5.15.0-47-generic #51-Ubuntu SMP

### PR DESCRIPTION
**Pull request by sipsma**
Not a particularly beautiful solution, but gets the bug fixed for the moment and the better solution is coming soon with the new api work.

Signed-off-by: Erik Sipsma <erik@sipsma.dev>

Fixes #3170 

cc @vito just want to squash that bug to unblock @vikram-dagger. Hopefully at least the test case code will be useful when we have the real solution, but I'm guessing the rest will be mostly throwaway.

The reason the solution looks so weird is that `Cmd` and `Entrypoint` don't propagate automatically along with `llb.State`, so I just do a dumb thing where I store the whole image config in the llb state metadata and pass that along.

### CODE REVIEW

**Review by vito — APPROVED** [review]
Nice, using the full image config is definitely the right direction imo especially for the new API.

One thing I'm wondering is if we want to also support preserving the raw image config bytes, since unmarshaling and re-marshaling could potentially change the digest. I remember gotchas here because sometimes the JSON is pretty-printed, sometimes it's not, maybe the key order changes, etc. But there's no reason for this to be a blocker yet, especially since we know we'll want to modify it with the new API.

~~One thing to note is I think @vikram-dagger also needed to support actually running the `CMD`, but I think we can/should just wait on the new API for that. (#3184)~~ Nevermind, that use case would have been equally satisfied with `ENTRYPOINT`.

**Comment by sipsma** [comment]
> One thing I'm wondering is if we want to also support preserving the raw image config bytes, since unmarshaling and re-marshaling could potentially change the digest. I remember gotchas here because sometimes the JSON is pretty-printed, sometimes it's not, maybe the key order changes, etc. But there's no reason for this to be a blocker yet, especially since we know we'll want to modify it with the new API.

I looked into this a while ago when wondering about something similar and found that while it's not fully documented, go's stdlib does apparently create stable marshals/unmarshals. This is based on in depth research I performed on stack-overflow (https://stackoverflow.com/a/18668885) so take with a grain of salt of course. So if that's true I think we should be covered? But it's an important thing to keep in mind going forward either way, it's easy to create subtle caching bugs with stuff like this.

**Comment by vito** [comment]
Go marshaling is stable, but image configs written to a container registry could be pushed by another language. I've also run into one occasion where digests differed because one party marshaled it with pretty-printing and one party didn't.

This is absolutely an edge case though. I'm not worried about it until someone complains. :laughing:

**Comment by sipsma** [comment]
@vito Ahhh okay I see what you're saying now, sorry I misunderstood before. Yeah that's a delightful corner case...

**Pull request merged**
