### PR TITLE
fix: fix terminal broken on Windows

### LINKED ISSUE #7282: 🐞 On Windows 11 - Cannot start an interactive terminal
### What is the issue?

The command

```
 dagger -m github.com/shykes/daggerverse/wolfi@v0.1.2 call container --packages=python3 terminal
```

fails with `Error: sending initial size: get terminal size: The handle is invalid.`

### Dagger version

dagger v0.11.2 ([registry.dagger.io/engine](http://registry.dagger.io/engine)) windows/amd64

### Steps to reproduce

I have create an azure windows 11 vm with docker desktop installed.
I follow the install docs, I install powershell 7.4.2 and I execute

```pwsh
Invoke-WebRequest -UseBasicParsing -Uri https://dl.dagger.io/dagger/install.ps1 | Invoke-Expression
```

I add the location of dagger to the path and then I try to follow t[he instructions to build a container](https://docs.dagger.io/quickstart/883939/containers)

Eventually I want to start an interactive terminal session with the container

```pwsh
dagger -m github.com/shykes/daggerverse/wolfi@v0.1.2 call container --packages=python3 terminal
```

### Log output

```pwsh
PS C:\Users\giulio365cloud> dagger -m github.com/shykes/daggerverse/wolfi@v0.1.2 call container --packages=python3 terminal
←[31m✘←[0m start sh ←[2m1.4s←[0m
←[33m! new container: client closed
←[0m
Error: sending initial size: get terminal size: The handle is invalid.
PS C:\Users\giulio365cloud>
```

### PR DESCRIPTION
**Pull request by wingyplus**
Uses `ts.stdout` instead of `ts.stdin` to get terminal size.

Fixes #7282

### CODE REVIEW

**Comment by wingyplus** [comment]
Screenshot 2024-05-07 223259

Demo on Windows. :)

**Review by jedevc — APPROVED** [review]

**Comment by jedevc** [comment]
Nice, thanks @wingyplus! I suspect this is the same kind of issue as in https://github.com/dagger/dagger/pull/7095. While on Unix, stdin/stdout/stderr generally all point to the same underlying device, on windows, these are fundamentally different data structures (one is an input buffer, one is an output buffer).

Thanks again! :tada:

**Comment by jedevc** [comment]
Any chance you could add a release note using `changie new`?

**Comment by wingyplus** [comment]
@jedevc added. 🙇

**Review by jedevc — APPROVED** [review]

**Pull request merged**
