### PR TITLE
docs: bump CLI version during installation

### PR DESCRIPTION
**Pull request by migmartri**
While reviewing the upcoming version documentation, I noticed that the CLI installed through other installation methods, except homebrew, was outdated.

This prevented me (I use Linux and the curl method) from progressing through the following sections in the quickstart, such as [this one](https://docs.dagger.io/zenith/user/quickstart/239293/functions) failing due to the missing `functions` command.

I bumped the docs to point to 0.9.7, which seems to be the latest release, also referenced in [homebrew tap](https://github.com/dagger/homebrew-tap/blob/bf22aa9d1e44de7e1d67196b117028d501431ea8/dagger.rb#L8).

Note for reviewers

- I noticed that after running docusaurus locally, a `guides.json` file was updated. I am not sure if this is expected or not. In fact, I can see the `guides.json` file in the `.gitignore` file. Let me know if you want me to drop the changes in this file. 
- I manually tested the installation method with curl in Linux. I didn't do it for the Windows version. So I'd appreciate it if you could double-check that, indeed, there is a Windows package with that version, and/or I can update my patch accordingly.

Thanks!

### CODE REVIEW

**Review by helderco — COMMENTED** [review]
Oh yes, this is really outdated! Thanks for the change! Comes from https://docs.dagger.io/cli/465058/install which needs an update as well.

Btw, @vikram-dagger already updated this (albeit to 0.9.5) in:
- https://github.com/dagger/dagger/pull/6262

Just needs to pass review but yours is a simpler change to approve and get out sooner. I'll defer to @vikram-dagger on that.

Regarding your problem, the first instruction should get you the latest version:
```shell
cd /usr/local
curl -L https://dl.dagger.io/dagger/install.sh | sh
```

It's only when you need an older version, or want to make sure you're getting a specific version, that you use `DAGGER_VERSION=`.

So I'm curious, did you skip to the end when following the instructions, expecting that to be the latest version? @vikram-dagger, maybe break that part into a section, with a clear heading like **For past versions**? Or automate during our release process to update that to be new version to remove ambiguity?

I remember at one point we had a shell script that replaced one version for another. We can at least add it to the RELEASING.md checklist. And rather than point to a previous version, in the context of installing a "specific" version, just replace with the new one during release.

As for `guides.json` it seems like it's expected, yes. But we should add it to [`docs/_README.md`](https://github.com/dagger/dagger/blob/e1a3764f9fcd676374a504e37eb7334e31e2c639/docs/_README.md) and mark it with `linguist-generated` in a `.gitattributes`.

**Comment by migmartri** [comment]
Hi,

> Just needs to pass review but yours is a simpler change to approve and get out sooner. I'll defer to @vikram-dagger on that.

Happy either way, I'll be happy to close the issue without merging if needed.

> So I'm curious, did you skip to the end when following the instructions, expecting that to be the latest version? @vikram-dagger, maybe break that part into a section, with a clear heading like For past versions? Or automate during our release process to update that to be new version to remove ambiguity?

Actually what happened is that I missed the `linux` tab and instead I was following the `MacOS` one (default). Which as you can see in the following picture, in the curl section, the first command includes a version.

image

If, this version would have included the `curl` command without the env variable (like the linux instructions), that's probably the one I've have picked :)

> As for guides.json it seems like it's expected, yes. But we should add it to [docs/_README.md](https://github.com/dagger/dagger/blob/e1a3764f9fcd676374a504e37eb7334e31e2c639/docs/_README.md) and mark it with linguist-generated in a .gitattributes

Thanks for clarifying. What confused me was the fact that the file is marked as ignored, although I assume that this ignore rule happened before the file was checked-in for the first time. So you might also want to remove that rule from there to prevent confusion, unless I am missing something.

https://github.com/dagger/dagger/blob/72de8a296a855fdeda9a616e2c6914eca4bcfea3/docs/.gitignore#L12

**Comment by vikram-dagger** [comment]
@migmartri thank you for this contribution! I reviewed it and have the following suggestions:

1. Your change affects the `zenith` version of the docs but not the `current` docs. Could you update docs/current_docs/partials/_install-cli.mdx with similar changes?
2. Yes, git rm-ing the generated file makes sense to me. It should be ignored, I'm not sure why it showed up here. Maybe @crjm has thoughts?

Just for reference, we now have a slightly different command for installing on linux: `curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh`. You can see this change in https://github.com/dagger/dagger/pull/6262

**Comment by migmartri** [comment]
@vikram-dagger I've just updated the patch to

- update the version in the current version of the docs
- `git rm guides.json`

> Just for reference, we now have a slightly different command for installing on linux: curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh. 

Nice. I am not sure if you are suggesting I make the change, too. I'd prefer to keep it separated though. It's my first patch and my context of how the install script works is very limited :)

Thanks!

**Comment by vikram-dagger** [comment]
> @vikram-dagger I've just updated the patch to
> 
> * update the version in the current version of the docs
> * `git rm guides.json`

Thank you!

> Nice. I am not sure if you are suggesting I make the change, too. I'd prefer to keep it separated though. It's my first patch and my context of how the install script works is very limited :)

No, that was just FYI. That change is already present in a different PR.

**Review by vikram-dagger — APPROVED** [review]

**Comment by vikram-dagger** [comment]
Congratulations on your first contribution @migmartri !

**Comment by migmartri** [comment]
@vikram-dagger, out of curiosity, when should I expect the change to be live on the site?  

I am asking in case I introduced any regression in the docusaurus bundle (which it has happened in the past to me :)

Thanks

**Comment by vikram-dagger** [comment]
> @vikram-dagger, out of curiosity, when should I expect the change to be live on the site?

The changes were made live earlier today.

**Pull request merged**
