### PR TITLE
Restrict dagger listen localdir access by default.

### PR DESCRIPTION
**Pull request by sipsma**
Signed-off-by: Erik Sipsma <erik@sipsma.dev>

Running with this command: `./hack/dev go run $(pwd)/cmd/dagger listen --local-dirs /tmp`

And then trying to make this query that requests a not allowed dir:
```
curl \
  -H "content-type:application/json" \
  -d '{"query":"{host{directory(path:\"/home/sipsma\"){entries}}}"}' \
  http://127.0.0.1:8080/query
```

Now results in this error: `{"data":{},"errors":[{"message":"NotFound: no access allowed to dir \"/home/sipsma\"","path":["host","directory","entries"],"locations":[{"line":1,"column":38}]}]}`

TODO:
- [x] Add automated tests

### CODE REVIEW

**Comment by sipsma** [comment]
Added a test now. Also had to add support for specifying `localhost:0` where a random port is chosen; I needed it to minimize conflicts between different tests but seems nice to have anyways.

Also, this change currently results in the CLI being incompatible with the last released engine. Locally I can just do `./hack/dev go run $(pwd)/cmd/dagger` and it works, but want to double check that the playground has all its source pinned to a git commit @marcosnils and only gets upgraded when we do a release (at which time the last released engine will work).

**Comment by sipsma** [comment]
I realized that once we have the CLI use `engine.Start` directly all the changes to the Go SDK in this PR will not be needed, so I'm going to put this in draft for now, will rebase it once the CLI is updated.

**Comment by gerhard** [comment]
Does the CLI use `engine.Start` today? cc @marcosnils

**Comment by sipsma** [comment]
@gerhard this PR changes the CLI to use `engine.Start` directly: https://github.com/dagger/dagger/pull/4119

Once it's merged I'll rebase this one. It'll be essentially the same as now except without any of the changes to the Go SDK.

**Comment by sipsma** [comment]
Reminder to self: add happy path e2e test case alongside the e2e test case in here too ocne rebased

**Comment by marcosnils** [comment]
> double check that the playground has all its source pinned to a git commit @marcosnils and only gets upgraded when we do a release (at which time the last released engine will work).

not currently. The playground is pulling from `main` every 5 minutes and bumping the engine to the latest version. I guess it'd make sense to make it only update when there's a new release. I'll make that change today.

**Pull request closed without merging**
