### PR TITLE
Docs website - Replace Amplitude with Posthog

### PR DESCRIPTION
**Pull request by slumbering**
Amplitude has been replaced by Posthog and should be completely removed from the docs website.

Signed-off-by: jffarge <jf@dagger.io>

### CODE REVIEW

**Comment by slumbering** [comment]
Next step will be to remove `REACT_APP_AMPLITUDE_ID` env variable from netlify.

**Review by gerhard — COMMENTED** [review]
I **think** that we can safely remove Amplitude, as well as the `/t` redirect.

WDYT @shykes @aluzzardi @samalba?

**Comment by jamesefhawkins** [comment]
👋 welcome to posthog!

just popping in to say hi / i'm one of the founders and if you need any help, posthog.com/slack is a good place to ask :)

**Comment by slumbering** [comment]
> 👋 welcome to posthog!
> 
> just popping in to say hi / i'm one of the founders and if you need any help, posthog.com/slack is a good place to ask :)

Hey @jamesefhawkins 😃  ! Thanks for your message.

**Comment by slumbering** [comment]
> I **think** that we can safely remove Amplitude, as well as the `/t` redirect.
> 
> WDYT @shykes @aluzzardi @samalba?

After asking @aluzzardi we're not using Amplitude anymore and it can be safely removed.

**Comment by slumbering** [comment]
One test is failing. It shoud be fixed with the following PR 
- https://github.com/dagger/dagger/pull/4478

**Review by grouville — APPROVED** [review]
LGTM

**Pull request merged**
