### PR TITLE
NodeJS SDK: Update codegen templates for docs references

### PR DESCRIPTION
**Pull request by slumbering**
- Add @hidden (equivalent to @ignore in JSDoc) tag to remove symbol that should never appear in the documentation.

- Export every classes otherwise they will not appear in documentation. 
I've tried to use `typedoc-plugin-missing-exports` in docusaurus but gets some conflicts during the build.

Signed-off-by: jffarge <jf@dagger.io>

### CODE REVIEW

**Review by gerhard — APPROVED** [review]
Looks good! When all checks are ✅ green, go for merge @slumbering 🏎

**Comment by gerhard** [comment]
I like that last commit!

Skipped tests are a terrible thing. Every one of them lowers the confidence in the test suite. Skip enough tests and the usefulness of the entire test suite will start getting questioned. Nice improvement!

**Comment by gerhard** [comment]
I will trust the test suite more when these new errors will be addressed. Nice digging @slumbering 🚜

**Comment by dolanor** [comment]
You need to update the expected results of the templating tests

**Comment by dolanor** [comment]
Read the diff. Do you always want to hide the documentation of all the classes?

**Comment by sipsma** [comment]
The reasoning behind skipping that test (and the issue for following up) is here: https://github.com/dagger/dagger/pull/3851#discussion_r1023164201

If we don't want to skip it we can just remove it as the codepaths are covered by the other test cases for now.

**Pull request merged**
