### PR TITLE
website: use docusaurus versioning system

### PR DESCRIPTION
**Pull request by slumbering**
To avoid broken url, we're using docusaurus [plugin client redirects](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects)

```
 redirects: [
  // /docs/oldDoc -> /docs/newDoc
  {
    to: '/0.1/1002/vs',
    from: '/1002/vs',
  },
],
```

cc @gerhard @dolanor 

Signed-off-by: jffarge <jf@dagger.io>

### CODE REVIEW

**Comment by dolanor** [comment]
Isn't there a possibility to preview the website? I thought we had that in the CI

**Comment by slumbering** [comment]
> Isn't there a possibility to preview the website? I thought we had that in the CI

https://deploy-preview-2066--devel-docs-dagger-io.netlify.app/

**Review by marcosnils — COMMENTED** [review]
Preview looks good here. Only thing that feels a bit stange IMO is the version number in the header

image

For some reason I have the feeling that the selector doesn't feel natural with the website. Maybe adding the word "version" inside the component or something. 

Besides that, LGTM!

**Comment by slumbering** [comment]
> Preview looks good here. Only thing that feels a bit stange IMO is the version number in the header
> 
> image
> 
> For some reason I have the feeling that the selector doesn't feel natural with the website. Maybe adding the word "version" inside the component or something.
> 
> Besides that, LGTM!

It's exactly what I did at first (adding version in front of 0.2, 0.1..). Except that this add version also in front of this :
Capture d’écran 2022-04-07 à 19 43 31

I could probably cheat and use css content property though ...

**Review by gerhard — COMMENTED** [review]
While we should definitely tell users that `0.1` docs are outdated and should not be used with the latest version of dagger, the whole idea of unique doc IDs is rooted in the principle of not breaking docs between versions, which makes versioning docs redundant.

Europa was a one-off AFAIK - **before launch** - and everything that happens **after launch** will not require users to tie the docs version to the dagger version. Or at least that was my understanding from talking to @shykes about this.

When in doubt, this is a good docs example to look at: https://tailscale.com/kb/
(notice that there are no versions there either)

**Comment by slumbering** [comment]
> While we should definitely tell users that `0.1` docs are outdated and should not be used with the latest version of dagger, the whole idea of unique doc IDs is rooted in the principle of not breaking docs between versions, which makes versioning docs redundant.
> 
> Europa was a one-off AFAIK - **before launch** - and everything that happens **after launch** will not require users to tie the docs version to the dagger version. Or at least that was my understanding from talking to @shykes about this.
> 
> When in doubt, this is a good docs example to look at: https://tailscale.com/kb/ (notice that there are no versions there either)

Ok. I could totally hide version dropdown in the Navbar. What do you think @gerhard ?

**Comment by gerhard** [comment]
I think that we should not use the Docusaurus versioning system as it is not compatible with the approach that we have been taking to versioning doc pages, with unique IDs.

I also think that we should make it clear for every `0.1` doc page that it is now outdated and should not be used unless the user is definitely using dagger `0.1`.

Keeping this 0.1 & 0.2 split seems to be creating a lot of confusion, so I'm wondering if we should hide the link in the sidebar all together. WDYT @shykes?

**Comment by slumbering** [comment]
Tweaking Docusaurus by introducing a mechanism to display a banner can be tricky. The project is still in beta and updated very frequently. When bump up, Docusaurus core is overwritten and our customization needs some fixes to be fully functional again. So, less tweaking means less pain ;)

After discussion with @aluzzardi, we'll move docs 0.1 to a parallel url (ex: v1.docs.dagger.io ?) using GitHub tag 0.1.0.
It'll be a snapshot of docs 0.1.
Then we'll remove all 0.1 docs from our current repo to avoid confusion between the two versions.

cc @gerhard @shykes

**Comment by aluzzardi** [comment]
For context: 0.1 is relevant for less than 10 users (conversation estimate, probably way less than that by now), which we should be helping migrating to 0.2 anyway.

To me that doesn't warrant investing effort to maintain 0.1 within the main website docs (we should spend that time helping users migrate instead, IMO)

**Comment by shykes** [comment]
> Tweaking Docusaurus by introducing a mechanism to display a banner can be tricky. The project is still in beta and updated very frequently. When bump up, Docusaurus core is overwritten and our customization needs some fixes to be fully functional again. So, less tweaking means less pain ;)
> 
> After discussion with @aluzzardi, we'll move docs 0.1 to a parallel url (ex: v1.docs.dagger.io ?) using GitHub tag 0.1.0. It'll be a snapshot of docs 0.1. Then we'll remove all 0.1 docs from our current repo to avoid confusion between the two versions.
> 
> cc @gerhard @shykes

Sounds good, a few important notes:

* For the URL, let's keep it under the same hostname, eg. `docs.dagger.io/0.1`. Otherwise we would break URLs from the older articles, which we don't want to do.
* Will it be possible to update the 0.1 docs by updating the 0.1.0 tag?

**Comment by slumbering** [comment]
To avoid broken url, let's leave docs as it is and tweak docusaurus to display a banner for docs 0.1

**Pull request closed without merging**
