### PR TITLE
Enhance docs typo readability

### PR DESCRIPTION
**Pull request by slumbering**
- Use the new typo size relative to the Dagger style guide.
- Change `code` tags background colors.

Signed-off-by: jffarge <jf@dagger.io>

### CODE REVIEW

**Comment by vikram-dagger** [comment]
I noticed that the hover effect is a bit weird on links which are also formatted as code. The underline which should appear on hover appears as a dashed/broken underline. See for example the links formatted as code in Step 4 of https://deploy-preview-4351--devel-docs-dagger-io.netlify.app/sdk/go/959738/get-started.

This is minor and need not block the merge, so I'll approve it anyway.

**Review by vikram-dagger — APPROVED** [review]

**Comment by slumbering** [comment]
> I noticed that the hover effect is a bit weird on links which are also formatted as code. The underline which should appear on hover appears as a dashed/broken underline. See for example the links formatted as code in Step 4 of https://deploy-preview-4351--devel-docs-dagger-io.netlify.app/sdk/go/959738/get-started.
> 
> This is minor and need not block the merge, so I'll approve it anyway.

Good catch @vikram-dagger thanks. I'll fix that tomorrow. 
Note for myself: line-height are also not big enough

**Review by crjm — CHANGES_REQUESTED** [review]
Nice, changing the background improves readability a lot.
I'll add a tiny observation.
The `<p>` line-height is different from the `<li>` line-height. In the first case, code tags collide, while in the second case they don't.
image
vs
image

**Comment by crjm** [comment]
> I noticed that the hover effect is a bit weird on links which are also formatted as code. The underline which should appear on hover appears as a dashed/broken underline. See for example the links formatted as code in Step 4 of https://deploy-preview-4351--devel-docs-dagger-io.netlify.app/sdk/go/959738/get-started.
> 
> This is minor and need not block the merge, so I'll approve it anyway.

@slumbering  I stumbled across this bug in the past, so I made the underline disappear or the same color as the background, don't remember which one. If you are stuck on making the underline render properly (I never managed to), I suggest we stick to one of those quick fixes.

**Review by crjm — APPROVED** [review]

**Comment by crjm** [comment]
LGTM! :ship:

**Pull request merged**
