### PR TITLE
feat(dev/ps-analyzer): add PSScriptAnalyzer to lint install.ps1 script

### PR DESCRIPTION
**Pull request by wingyplus**
I'm playing around PowerShell script and found that they have a tool called [PSScriptAnalyzer](https://learn.microsoft.com/en-us/powershell/module/psscriptanalyzer/invoke-scriptanalyzer) to lint and format the PowerShell script. So I do some a quick hack to daggerize it and share it to you all to asking for opinion.

## Demo

Checking the `install.ps1`

```
$ dagger call -m ./dev/ps-analyzer check --file=./install.ps1 issues
- _type: PsAnalyzerIssue
  code: 0
  column: 13
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 30
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 17
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 73
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 9
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 83
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 9
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 136
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 5
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 148
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 13
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 189
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 13
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 193
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 13
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 206
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 13
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 241
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 9
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 262
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 9
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 278
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 9
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 289
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 13
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 312
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 13
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 328
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 13
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 343
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 13
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 359
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 5
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 370
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 9
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 378
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 9
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 388
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 17
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 399
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 17
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 402
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 17
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 407
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 9
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 410
  lineEnd: 0
  message: File 'install.ps1' uses Write-Host. Avoid using Write-Host because it might not work in 
all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, capture
d, or redirected. Instead, use Write-Output, Write-Verbose, or Write-Information.
- _type: PsAnalyzerIssue
  code: 0
  column: 1
  columnEnd: 0
  filename: install.ps1
  level: Information
  line: 226
  lineEnd: 0
  message: Line has trailing whitespace
- _type: PsAnalyzerIssue
  code: 0
  column: 1
  columnEnd: 0
  filename: install.ps1
  level: Information
  line: 229
  lineEnd: 0
  message: Line has trailing whitespace
- _type: PsAnalyzerIssue
  code: 0
  column: 82
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 4
  lineEnd: 0
  message: 'The parameter ''DaggerVersion'' has been declared but not used. '
- _type: PsAnalyzerIssue
  code: 0
  column: 87
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 5
  lineEnd: 0
  message: 'The parameter ''DaggerCommit'' has been declared but not used. '
- _type: PsAnalyzerIssue
  code: 0
  column: 44
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 6
  lineEnd: 0
  message: 'The parameter ''DownloadPath'' has been declared but not used. '
- _type: PsAnalyzerIssue
  code: 0
  column: 44
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 7
  lineEnd: 0
  message: 'The parameter ''InstallPath'' has been declared but not used. '
- _type: PsAnalyzerIssue
  code: 0
  column: 44
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 8
  lineEnd: 0
  message: 'The parameter ''AddToPath'' has been declared but not used. '
- _type: PsAnalyzerIssue
  code: 0
  column: 44
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 9
  lineEnd: 0
  message: 'The parameter ''Interactive'' has been declared but not used. '
- _type: PsAnalyzerIssue
  code: 0
  column: 90
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 422
  lineEnd: 0
  message: 'The parameter ''DaggerVersion'' has been declared but not used. '
- _type: PsAnalyzerIssue
  code: 0
  column: 95
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 423
  lineEnd: 0
  message: 'The parameter ''DaggerCommit'' has been declared but not used. '
- _type: PsAnalyzerIssue
  code: 0
  column: 52
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 424
  lineEnd: 0
  message: 'The parameter ''DownloadPath'' has been declared but not used. '
- _type: PsAnalyzerIssue
  code: 0
  column: 52
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 425
  lineEnd: 0
  message: 'The parameter ''InstallPath'' has been declared but not used. '
- _type: PsAnalyzerIssue
  code: 0
  column: 52
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 426
  lineEnd: 0
  message: 'The parameter ''AddToPath'' has been declared but not used. '
- _type: PsAnalyzerIssue
  code: 0
  column: 52
  columnEnd: 0
  filename: install.ps1
  level: Warning
  line: 427
  lineEnd: 0
  message: 'The parameter ''Interactive'' has been declared but not used. '
```

the `issues` field come from `Report` that I do copy from `shellcheck` module and map into it from what it has in analyzer output.    So the code is a bit duplicate with the shellcheck module and looks inconsistent, but it can be discuss further.

If you're all ok about this. I can work on fixing the script to make it pass and integrate into dev module.

### CODE REVIEW

**Comment by jedevc** [comment]
Woo, this looks awesome :tada: Yeah, I definitely want this, it'll be great to have this next to `shellcheck`.

Very much agreed on getting `install.ps1` to pass this! Thanks for offering to pick it up!

cc @pjmagee who did a lot of work on the `install.ps1` script

**Comment by pjmagee** [comment]
This is awesome, the Write-Host warnings make sense instantly to me, the last few around the parameters not being used is a bit confusing though. I wonder what's going on there. We do have a kind of special usage in that the file can either be invoked as an entire script, in which case, the function declared at the bottom is used and executes the installation, where as the params defined in the top of the file, are used for when the script is executed from a file. 

We should certainly include this, and then maybe figure out why its thinking some variables arent used. 

Aaaaaaaaaaaaand, semi-related, I still strongly believe Daggers official installation should be via winget, which is still a pending PR to do with goreleaser. I feel like the powershell install is more for powershell/power/advanced users.  goreleaser with winget means a very simple upgrade process would be supported  (winget upgrade dagger.cli) 

None the less, we do have powershell, it's a great way to install and thus, this analyzer is looking great to add!

**Comment by wingyplus** [comment]
I found the tricky point now, the `latest` image doesn't `arm64`. They provides support for `arm64` but that image are not cross platform. 😂

**Comment by wingyplus** [comment]
Hmm, I see a weird output on macOS

```
PS /Users/thanabodee/src/github.com/dagger/dagger> ./install.ps1
---------------------------------------------------------------------------
Note: This script will install the Windows binary of Dagger.
---------------------------------------------------------------------------
Downloading Dagger from https://dl.dagger.io/dagger/releases/Latest version of Dagger is v0.12.1
 0.12.1/dagger_vLatest version of Dagger is v0.12.1
 0.12.1_windows_arm64.zip
```

The `Downloading...` and the `Latest version of...` should be a separate line. Let me investigating on Windows.

**Comment by jedevc** [comment]
@wingyplus once the above is resolved, this LGTM :tada:

**Comment by wingyplus** [comment]
@jedevc @pjmagee It's all done. Here is summary:

1. I struggle with the official powershell image. They're not provides cross-platform image. So I fix it by using Wolfi + [Powershell](https://github.com/wolfi-dev/os/blob/main/powershell.yaml) package with `PSScriptAnalyzer` bundled. The container size should be smaller than official image due to limit of Powershell module. 
2. I replace `Write-Host` to `Write-Error` for any output that is error.
3. I replace `Write-Host` to `Write-Output` for any output in `Main`
4. I cannot find the way to fix the unused parameters in `Install-Dagger`, it'll error when using `Invoke-Expression; Install-Dagger` if we deleting it. So I temporary add the exclude rules to the `ps-analyzer` to bypass unused parameters for now. Feel free to suggest if you have any suggestions.

**Review by jedevc — APPROVED** [review]

**Comment by jedevc** [comment]
Thanks @wingyplus - this is super useful! :heart:

**Pull request merged**
