### PR TITLE
Separated SDK docs into independent sites

### PR DESCRIPTION
**Pull request by vikram-dagger**
THIS IS STILL WIP - DO NOT MERGE

- Created 3 separate Docusaurus sites in new websites/ directory
  - websites/docs-main: parent site, base URL will be docs.dagger.io/
  - websites/docs-sdk-go: dedicated Go SDK child site, base URL will be /sdk/go
  - websites/docs-sdk-cue: dedicated CUE SDK child site, base URL will be /sdk/cue
 - Created a shared area in websites/docs-common for static assets, styles and themes so all docs sites can share these
 - Adjusted each site's configuration file to use shared area for static assets
 - Added sample content and sidebar for each site
 - Cross-linked parent and child sites via sidebar

Signed-off-by: Vikram Vaswani <vikram@dagger.io>

### CODE REVIEW

**Comment by vikram-dagger** [comment]
Open issues:
- Search testing - requires additional indexes in Docsearch + deployment to public URL so crawler can operate
- Deployment - complicated if we are using sub-URLs for the child sites as each site is built independently, so somehow needs to be merged into the main site tree (simplification might be to use a separate sub-domain for each child site) 
- - At build-time of parent site, Docusaurus throws warnings about broken links as its sidebar contains links to child sites but the parent site build doesn't include them (related to previous issue)
- Some legacy filenames/URLs use numbers and others don't, needs review
- There is probably a lot of duplication between the three sites, needs review and cleanup of unwanted/duplicate files

**Comment by vikram-dagger** [comment]
Note: I investigated using Docusaurus multi-instance to make this structure lighter. This approach uses a single Docusaurus instance and single configuration file. However, this allows only a single DocSearch index. If we want each site to have independent search results, I believe we will need a separate DocSearch index for each site (or a single index with facets). Therefore, multi-instance would not fit with this requirement.

**Comment by gerhard** [comment]
Converting to draft so that it will not be merged by mistake.

**Comment by gerhard** [comment]
https://www.algolia.com/apps/XEIYPBWGOI/indices

<a href="https://www.algolia.com/apps/XEIYPBWGOI/indices">image</a>

**Comment by gerhard** [comment]
Once we have the URLs for the other websites, we can [configure the new crawlers](https://crawler.algolia.com/admin/crawlers?sort=status&order=ASC&limit=20&appId=XEIYPBWGOI):

<a href="https://crawler.algolia.com/admin/crawlers?sort=status&order=ASC&limit=20&appId=XEIYPBWGOI">image</a>

**Comment by gerhard** [comment]
The biggest question for me right now is whether we want to configure the new docs to be deployed on a sub-domain (e.g. `go-sdk-docs.dagger.io`) or path (e.g. `docs.dagger.io/go-sdk`). Based on this, I will know how to configure Route 53, Netlify & Algolia.

cc @vikram-dagger @aluzzardi @samalba @shykes @slumbering

**Comment by shykes** [comment]
> The biggest question for me right now @vikram-dagger is whether we want to configure the new docs to be deployed on a sub-domain (e.g. `go-sdk-docs.dagger.io`) or path (e.g. `docs.dagger.io/go-sdk`). Based on this, I will know how to configure Route 53, Netlify & Algolia.

Definitely path `docs.dagger.io/sdk/go` . Copying @vikram-dagger who has the most context for docs structure.

**Comment by shykes** [comment]
@vikram-dagger high level, do you feel the navigation experience will be pleasant, and match what we imagined when planning it?

**Comment by vikram-dagger** [comment]
> Definitely path `docs.dagger.io/sdk/go` . Copying @vikram-dagger who has the most context for docs structure.

@shykes what about pages below that path? Do you prefer:
- `docs.dagger.io/sdk/go/8g34z/get-started`
- `docs.dagger.io/sdk/go/get-started`
- `docs.dagger.io/8g34z/get-started`

Note: the last one will allow maximum reuse of existing URLs but has the downside of not being very descriptive or matching the `/sdk/go` approach.

I'm checking this because I know you wanted to reuse the existing URLs from docs.dagger.io where possible. But if most of those pages will now move to `docs.dagger.io/sdk/cue/*` anyway (depending on decision above), I'm wondering if it makes sense to drop the UUID prefixes altogether and just go with completely a human-readable URL structure for the new docs. WDYT?

**Comment by shykes** [comment]
> @shykes what about pages below that path? Do you prefer:
> 
> * `docs.dagger.io/sdk/go/8g34z/get-started`
> * `docs.dagger.io/sdk/go/get-started`
> * `docs.dagger.io/8g34z/get-started`
> 
> Note: the last one will allow maximum reuse of existing URLs but has the downside of not being very descriptive or matching the `/sdk/go` approach.
> 
> I'm checking this because I know you wanted to reuse the existing URLs from docs.dagger.io where possible. But if most of those pages will now move to `docs.dagger.io/sdk/cue/*` anyway (depending on decision above), I'm wondering if it makes sense to drop the UUID prefixes altogether and just go with a completely human-readable URL structure for the new docs. WDYT?

Good question...

My preference (but open to changing my mind) is the first option: `docs.dagger.io/sdk/go/8g34z/get-started`. I find it has the best balance of 1) flexibility to easily change structure in the future without breaking URLs, 2) matches high-level organization of sites (`/sdk/go` approach), 3) still readable, and 4) easiest to change our minds later.

**Comment by vikram-dagger** [comment]
> Once we have the URLs for the other websites, we can [configure the new crawlers](https://crawler.algolia.com/admin/crawlers?sort=status&order=ASC&limit=20&appId=XEIYPBWGOI):

@gerhard, the URLs will be:
- docs.dagger.io
- docs.dagger.io/sdk/go
- docs.dagger.io/sdk/cue

I have configured the base URLs of the 3 Docusaurus sites accordingly.

**Comment by shykes** [comment]
@vikram-dagger if it makes the readability hit less painful, we could reserve a range of IDs for each SDK, and just use those. That would allow using less characters.

For example we could reserve `4xxx` for Go SDK, and `5xxx` for CUE SDK. Then articles could even be linear: `docs.dagger.io/go/sdk/4001/get-started` etc.

The important thing is that we coordinate all IDs across all sites to be globally unique. This keep all our options for later (including merging it all back under a single hierarchy, or even getting rid of the entire ID system in the future while still getting a clean slate - that only works once though :)

**Comment by gerhard** [comment]
I am now caught up with this PR too. Thank you @vikram-dagger & @shykes for clarifying domain vs path. The path approach makes a bunch of things easier.

The trickiest part right now is the Docsearch configuration. I am confident that we will figure it out today with @vikram-dagger.

I am going to check the failing Netlify preview next.

**Comment by gerhard** [comment]
OK, this looks like an easy fix - doing it next.

image

**Pull request closed without merging**
