### PR TITLE
docs: Migrated examples from dagger/examples repository to dagger/dagger repository

### PR DESCRIPTION
**Pull request by vikram-dagger**
This commit transfers the code examples from the https://github.com/dagger/examples repository to the current repository. 
- SDK examples are now in `sdk/[go|nodejs|python]/examples/*`
- CLI examples are now in `cmd/examples/*`
This commit also adds a README to each `examples` directory with an index of the available examples.
The intent is for new examples to be added to the current repository instead of the https://github.com/dagger/examples, which will shortly be deprecated.
See also: https://github.com/dagger/examples/pull/34

### CODE REVIEW

**Comment by vikram-dagger** [comment]
I have taken the approach of placing SDK-specific examples inside a new `sdk/[language]/examples*` directory. Another approach would be to create an `examples` directory in the repo root and place all examples there instead, with separate sub-dirs for each language. Reviewers, please lmk if this second approach is preferable.

**Review by TomChv — COMMENTED** [review]
The architecture makes sense to me as a developer but as a user, it might be better to group everything into an `examples` directory with them `examples/cmd` and `examples/sdk/[languages]`.

So you can have a root `README` that summary what's in this directory and then you can have specific readme for each sub directory (exactly like you did).

This way, the user has only 1 directory to search in and does not need to look for 4 different locations to see examples.

I wonder what other think, do not apply my suggestion for now. I'll approve the PR once we all agreed on a structure

**Comment by d3rp3tt3** [comment]
> The architecture makes sense to me as a developer but as a user, it might be better to group everything into an `examples` directory with them `examples/cmd` and `examples/sdk/[languages]`.
> 
> So you can have a root `README` that summary what's in this directory and then you can have specific readme for each sub directory (exactly like you did).
> 
> This way, the user has only 1 directory to search in and does not need to look for 4 different locations to see examples.
> 
> I wonder what other think, do not apply my suggestion for now. I'll approve the PR once we all agreed on a structure

I agree with a root Examples directory. It will make it easier to find and use the examples.

**Comment by shykes** [comment]
Small nit on commit messages: generally try to use the present tense ("migrate examples...") instead of past tense ("migrated examples...")

**Comment by vikram-dagger** [comment]
> Small nit on commit messages: generally try to use the present tense ("migrate examples...") instead of past tense ("migrated examples...")

Noted, thanks for the feedback. Will do on future messages.

**Comment by vikram-dagger** [comment]
Closing this as it does not include the Git history of the dagger/examples repository.

**Pull request closed without merging**
