### PR TITLE
docs: Provide more examples on `client: commands` and `platform`

### LINKED ISSUE #1890: client doc: reference on how to use stdin/stdout
in https://docs.dagger.io/1203/client/#running-commands, we talk about we can use stdin + stderr, but we don't link to any other docs. And it seems we have none.

### PR DESCRIPTION
**Pull request by helderco**
Resolves #1890

👀 [Preview](https://deploy-preview-2668--devel-docs-dagger-io.netlify.app/1203/client#running-commands)

Signed-off-by: Helder Correia

### CODE REVIEW

**Review by TomChv — APPROVED** [review]

**Comment by jpadams** [comment]
@helderco Love these improvements.
The only thing I'd add regarding output fields is that they have to be *generated fields* (or whatever best term is) instead of concrete fields, right?

Some users might be confused that they didn't get output for `out1` below:

```
dagger.#Plan & {
    actions: {
        build: {
            out1: "hello"
            _nop: core.#Nop & {input: "helloNop"}
            out2: _nop.output
        }
    }
}
```
```
$ dagger do build
[✔] actions.build                                                           0.0s
Field  Value
out2   "helloNop"
```

**Comment by helderco** [comment]
Yes, but non-output fields are private in these examples, so I don't see the confusion.

**Review by samalba — APPROVED** [review]
Agreed with Helder, LGTM.

**Comment by jpadams** [comment]
> Yes, but non-output fields are private in these examples, so I don't see the confusion.

I have no issues with your examples :) If folks follow them, they will do well.

I mean that I don't think there is anywhere in the docs where it is stated that the output fields must be *generated* fields. We should say that somewhere. Why not here? :)

I can follow with a PR.

**Comment by helderco** [comment]
I think the proper place for that is in https://docs.dagger.io/1228/handling-outputs

**Pull request merged**
