### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by mkozakov**

### CODE REVIEW

**Review by gerhard — COMMENTED** [review]
Thank you Michael for your first contribution to Dagger!

We can merge this as soon as you get the [DCO check green](https://github.com/dagger/dagger/pull/1953/checks?check_run_id=5764656771).

**Review by TomChv — APPROVED** [review]

**Comment by TomChv** [comment]
Since you have only one commit, you can also just do `git commit --amend --no-edit --signoff` and then `git push -f <fork name>`

**Comment by gerhard** [comment]
In the interest of preventing a PR pile-up, I am adding a `stale` label.

We will either merge this PR in the next 7 days, or it will be automatically closed.

**Comment by mkozakov** [comment]
Thanks @TomChv and @gerhard, I think it should be good to go!

**Pull request merged**
