### PR TITLE
implement aks auth

### PR DESCRIPTION
**Pull request by bluebrown**
Signed-off-by: Nico Braun <rainbowstack@gmail.com>

resolve: #2860 

### Add

- generic action to get an azure token for a specific resource or scope
- action to get AKS credentials for user or admin

### CODE REVIEW

**Comment by jpadams** [comment]
Thanks @bluebrown !

Look forward to walking through this with you. I might need to confirm that I'm filling in the Azure and AKS environment variables correctly since I'm getting an empty `/.kube/config`.

**Comment by bluebrown** [comment]
Hi @jpadams, did you create a service principal with the correct permissions? 

```yaml
// the tenant ID of your subscription
// az account show --query tenantId -o tsv
AZURE_TENANT_ID:                     string

// service principal id and secret with permission
// to get user or admin credentials for the cluster
// confirm if the sp has permissions with 
// az login --service-principal --username <sp_client_id> --password <password> --tenant <tenant>
// az aks get-credentials --resource-group <rg> --name <cluster> --subscription <sub>  --admin
AAD_SERVICE_PRINCIPAL_CLIENT_ID:     string
AAD_SERVICE_PRINCIPAL_CLIENT_SECRET: dagger.#Secret

// the subscription id of the cluster
// az account show --query id -o tsv
AKS_SUSCRIPTION_ID:                  string
// name and rg
az aks list --query '[].{n:name,g:resourceGroup}' -o tsv
AKS_CLUSTER:                         string
AKS_RESOURCEGROUP:                   string
```

If you follow the test, the SP must be allowed to fetch admin credentials. Perhaps you can try with admin: false. Then you probably also want to set format to `azure`, since you don't have kubelogin installed.

Anyhow, it's probably a good idea to get some kind of error handling going. I think it's not good if it *fails* silently.

**Comment by bluebrown** [comment]
@jpadams, I have modified the scripts so that they fail with error code if the rest API requests against azure fail. 

The issue was the usage of piping and the lack of the pipefail option in sh scripts.  It's not using piping any more so the action will fail if it could not get the config. This should be a better UX since it doesn't let you run into this issue with the empty kubeconfig that you had.

**Review by jpadams — APPROVED** [review]
LGTM. I've tried this out. Thanks, @bluebrown !

**Pull request merged**
