### PR TITLE
fix: NodeSDK correctly solves subqueries

### PR DESCRIPTION
**Pull request by TomChv**
Details in https://github.com/dagger/dagger/issues/4257#issuecomment-1367121945

Resolves: #4257
Signed-off-by: Tom Chauveau <tom.chauveau@epitech.eu>

### CODE REVIEW

**Comment by grouville** [comment]
Thanks @TomChv 🙏.

One side question: do you think adding the corresponding test in our test suite would be worth it ?

**Comment by TomChv** [comment]
I think we can add some complex queries as test but not too much to avoid ultra long test suits, I'll work on it

**Review by slumbering — APPROVED** [review]
LGTM! Thanks 🚀

**Comment by slumbering** [comment]
Could you rebase @TomChv please ? Thx

**Comment by dolanor** [comment]
Thanks @TomChv :)

**Pull request merged**
