### PR TITLE
Add DaggerFunction `format` to PhpSdkDev

### LINKED ISSUE #8124: PHP: Add `format()` to PhpSdkDev
A "format" function will make it easier for other maintainers that get PHP linting errors, to run the formatter in order to solve them.

You can return a Directory with the diff of the changes, like this:

https://github.com/dagger/dagger/blob/b0d27e15843341643954a4e9ef0841cd785b78b3/sdk/python/dev/src/main/__init__.py#L186-L187

_Originally posted by @helderco in https://github.com/dagger/dagger/pull/8112#discussion_r1709402971_

### PR DESCRIPTION
**Pull request by charjr**
Closes #8124

### CODE REVIEW

**Comment by charjr** [comment]
@helderco What should `format` achieve?

Should it:

A - Return a list of diffs showing what would have happened if it was formatted?
B - Actually format the directory?

**Comment by helderco** [comment]
Format should actually format, and return a diff of the changed directory. This way the returned directory can be exported to the host, overwriting only those changed files.

**Comment by charjr** [comment]
> Format should actually format, and return a diff of the changed directory. This way the returned directory can be exported to the host, overwriting only those changed files.

How does the Python accomplish this? I see how I can return the `diff` but how are those changes then exported to the host?

**Comment by helderco** [comment]
It's the cli that does the exporting, just add `export --path=.` to any function that returns a directory: `dagger call -m dev --source=. format export --path=.`

**Comment by charjr** [comment]
This issue is currently blocked by #8141.

**Comment by charjr** [comment]
cc @dagger/sdk-php @carnage

I think this is now ready to go. Would it be possible to have this re-reviewed please?

**Review by TomChv — APPROVED** [review]

**Pull request merged**
