### PR TITLE
💥feat(sdk/elixir): return only `:ok` for any functions that returns Void type

### PR DESCRIPTION
**Pull request by wingyplus**
This is #6868 but for Elixir, when found any function that return `Void`, instead of return `{:ok, Void}`, return just only `:ok` atom. 

This requires #7667 to be complete first because this PR may break the runtime due to `return_value` return type change.

### CODE REVIEW

**Review by helderco — APPROVED** [review]

**Comment by wingyplus** [comment]
The runtime works as expected. :)

**Comment by helderco** [comment]
Waiting for https://github.com/dagger/dagger/pull/7667 as described.

**Comment by helderco** [comment]
> Waiting for #7667 as described.

@wingyplus, that's been merged, let me know when this one is rebased and good to go.

**Comment by wingyplus** [comment]
@helderco It's all done. Waiting for CI to pass.

**Comment by wingyplus** [comment]
All checks green. :)

**Review by helderco — APPROVED** [review]

**Pull request merged**
