### PR TITLE
Added support for gosec

### PR DESCRIPTION
**Pull request by ab-passos**
Signed-off-by: Andre Passos <andre.debritopassos@asml.com>

### CODE REVIEW

**Review by TomChv — COMMENTED** [review]
Thanks for your contribution!

Can you update your commit with `ci:` or `chore:` so it will be ignored by the changelog?

I have no special comment, I pinged @marcosnils and @aluzzardi to have their expertise on that subject.
Otherwise, LGTM

**Comment by TomChv** [comment]
> I think it would be better to instead enable gosec linter in golangci-lint so we don't need another workflow and reduce footprint: https://golangci-lint.run/usage/linters/

I didn't know it was possible, but I agree with him! It would be much simpler and that should work in dagger ci directly

**Comment by ab-passos** [comment]
> gosec

**Comment by ab-passos** [comment]
> I think it would be better to instead enable `gosec` linter in golangci-lint so we don't need another workflow and reduce footprint: https://golangci-lint.run/usage/linters/

Hi @crazy-max, 

I see that gosec is enabled on the .golangci.yml however I get different results if I run it using gosec. 
Any idea on how to proceed?

**Comment by samalba** [comment]
I agree with what was said earlier (moving to golangci-lint), also we're moving most things away from the Makefile, Github workflows, into the dagger plan: https://github.com/dagger/dagger/blob/main/ci/golangci/lint.cue

@ab-passos I would compare the version of gosec in the github action and in golangci-lint, I am pretty sure the different output is due to a version mismatch.

**Comment by dolanor** [comment]
I must say that I see a good amount of ignored error in this, which is a good thing, it will give me some base to work on some error chain that might be broken.
The only one that seems ok to ignored is the one about vt100, because there is a good comment on it about why to ignore

**Comment by marcosnils** [comment]
> I must say that I see a good amount of ignored error in this, which is a good thing, it will give me some base to work on some error chain that might be broken.

we have to be careful with this change since there are some error skipping that's intentional. i.e: https://github.com/dagger/dagger/pull/2105/files#diff-febd17473d63b822be438e40e60ac098fb3a22edefd03f979a63e99ce7e4fcf8R41. 

I also vote for making this work through `golang-ci-lint`

**Comment by shykes** [comment]
This PR looks stuck. Is there consensus on what we want to do here? @samalba @aluzzardi ?

**Comment by samalba** [comment]
Closing this since there is a consensus to use gosec through `golangci-lint`. I checked and it uses the latest version of gosec `v2.11.0`. @dolanor would you mind checking why some rules are skipped? I am sure there is a good reason, I see golangci-lint embeds default config for linters.

**Pull request closed without merging**
