### PR TITLE
Add build args to Dockerfile build

### LINKED ISSUE #3574: ✨ Build Args for Dockerfiles
### What are you trying to do?

Just trying to do a docker build within my dagger pipeline, can't see a way to pass in build args with `container.Build()`. 

I would think I could just pass in a struct of args to build. something like 

```
container.build( dagger.buildArgs{
  {"foo": "bar"},{"biz":"bang"}
} )
```

### Why is this important to you?

We have lots of multi-stage docker builds. Long term I can see a migration path to more efficient builds directly via dagger commands, but the immediate migration path would need to leverage existing builds.

### How are you currently working around this?

I'm not 😅

### PR DESCRIPTION
**Pull request by jlongtine**
Resolves #3574 

Signed-off-by: Joel Longtine <joel@longtine.io>

### CODE REVIEW

**Review by sipsma — APPROVED** [review]
LGTM other than the already discussed need for nodejs support for input types, shipit once that test case is passing :-)

**Comment by jlongtine** [comment]
> LGTM other than the already discussed need for nodejs support for input types, shipit once that test case is passing :-)

Thanks @sipsma! 🙏🏻 

Gonna work with @dolanor on that!

**Comment by gerhard** [comment]
The engine tests were failing due to [this](https://discord.com/channels/707636530424053791/783828171153866782/1054451195156119715) (private discussion). We addressed the root cause and re-ran the failing tests. If they pass, go for merge @jlongtine 💪

**Comment by dolanor** [comment]
https://github.com/dagger/dagger/pull/4247 has been merged (thanks @TomChv )
I tried locally by rebasing this one on top of the #4247, and it worked.
So you can just rebase and merge when you want @jlongtine

**Pull request merged**
