### PR TITLE
Make create_embed_qs.sh support Elixir

### PR DESCRIPTION
**Pull request by wingyplus**

### CODE REVIEW

**Review by TomChv — COMMENTED** [review]
Setup LGTM, do you have something to try it?

**Comment by TomChv** [comment]
I have the same problem when I try on my side, I can think of two reasons:

1 - The setup fails
2 - Something's wrong on Dagger playground when using Elixir

@crjm Do you know if Dagger Playground can struggle with a new setup? Is there any changes we may need to do on our side?

**Comment by vikram-dagger** [comment]
@wingyplus it looks like you want to create an embeddable Elixir snippet which is not related to the quickstart? If so, then the changes should be applied to `create_embed.sh` instead of `create_embed_qs.sh`, as the latter is intended only for use with the Dagger quickstart at https://docs.dagger.io/quickstart/ .

This is also mentioned in [the style guide](https://github.com/dagger/dagger/blob/main/docs/STYLE_GUIDE.md):

```
Note that the command differs depending on whether the embed is for use in the Quickstart or elsewhere, as the Quickstart has special requirements.

cd docs
# for embeds apart from quickstart embeds
TOKEN=$TOKEN ./create_embed.sh YOUR-SNIPPET-FILE
# for quickstart embeds
TOKEN=$TOKEN ./create_embed_qs.sh YOUR-SNIPPET-FILE
```

I suggest transferring the changes you have made in the PR to `create_embed.sh` and then trying to create the embeddable snippet again.

**Comment by TomChv** [comment]
> I suggest transferring the changes you have made in the PR to create_embed.sh and then trying to create the embeddable snippet again.

I updated `create_embed.sh` and I hit the same issue :/ 

```shell
TOKEN=$TOKEN ./create_embed.sh ./test.exs
...

https://play.dagger.cloud/embed/INOiQrplCK1
```

The link is still broken: https://play.dagger.cloud/embed/INOiQrplCK1

**Comment by gerhard** [comment]
I am pretty sure that Elixir is not available on the Playground. cc @marcosnils 

Also, https://play.dagger.cloud/playground/9m4N7SgFN-J doesn't work since the container image does not have `git` installed:

image

**Comment by wingyplus** [comment]
@gerhard Thank you for the guidance! I forgot that elixir image didn't bundle git in the image. 

This is a new version upload by the latest query https://play.dagger.cloud/embed/27uUMLP7l8t. It can open but cannot execute. I'm not sure why. :/

cc @TomChv @vikram-dagger

**Comment by TomChv** [comment]
I think it's because as @gerhard  said, Elixir isn't supported by the Playground for now :/

**Comment by wingyplus** [comment]
> I think it's because as @gerhard said, Elixir isn't supported by the Playground for now.

So I will retest once it support.

**Pull request closed without merging**
