### PR TITLE
docs: Added Tailscale access recipe to cookbook

### PR DESCRIPTION
**Pull request by vikram-dagger**
This commit adds a cookbook recipe explaining how to use a container in a Dagger pipeline to access a Tailscale network.

### CODE REVIEW

**Comment by vikram-dagger** [comment]
@helderco  can you suggest the change needed to fix the lint error at https://github.com/dagger/dagger/actions/runs/5718235177/job/15493626865?pr=5532#step:4:514? Thanks.

**Comment by helderco** [comment]
```console
❯ cd sdk/python
❯ hatch run fmt
```

**Comment by vikram-dagger** [comment]
Ping @kpenfound @jpadams @marcosnils for review

**Review by gerhard — APPROVED** [review]
I have made a few changes to the Go example. See my commit message for more details.

Fails as expected when the env vars are not set:
image

Works as expected when they are:
image

This will be a nice addition to the cookbook @vikram-dagger 💪

**Comment by gerhard** [comment]
Do you want to rebase on top of `main`? The Rust SDK issue has been fixed via:
- https://github.com/dagger/dagger/pull/5626

**Comment by vikram-dagger** [comment]
> Do you want to rebase on top of `main`? The Rust SDK issue has been fixed via:
> 
> * [Fix sdk:rust:test running against nightly Rust #5626](https://github.com/dagger/dagger/pull/5626)

Rebased. Ready for re-review @gerhard

**Pull request merged**
