### PR TITLE
WIP: docs: docker core

### LINKED ISSUE #2866: docs: Move the Docker guide to Core Concepts
`dagger.#Docker` is core to the use of Dagger.

### PR DESCRIPTION
**Pull request by grouville**
Fixes #2866.

cc @jpadams. Please merge #2880 first

### CODE REVIEW

**Comment by grouville** [comment]
rebased

**Review by crjm — APPROVED** [review]
LGTM :ship:

**Comment by gerhard** [comment]
Now that:
- https://github.com/dagger/dagger/pull/2880 is merged
- addressed one warning https://github.com/dagger/dagger/pull/2884
- fixed a bunch of related content https://github.com/dagger/dagger/pull/2885

I can finish reviewing this.

**Review by gerhard — COMMENTED** [review]
Having taken a step back and looking at it from further away, I don't think that this `universe.dagger.io/docker` page belongs under the **Core Concepts** section. This section was meant to cover the high-level, e.g. client, secrets, actions, plan, etc. This specific page seems to be a reference for the Docker package. As great & essential as this doc page is, I would put it under **References**,  in a place that people can see it easily (I assume that most users will find it via Search).

WDYT @jpadams? Happy to defer the merge to you.

**Comment by jpadams** [comment]
> Having taken a step back and looking at it from further away, I don't think that this `universe.dagger.io/docker` page belongs under the **Core Concepts** section. This section was meant to cover the high-level, e.g. client, secrets, actions, plan, etc. This specific page seems to be a reference for the Docker package. As great & essential as this doc page is, I would put it under **References**, in a place that people can see it easily (I assume that most users will find it via Search).
> 
> WDYT @jpadams? Happy to defer the merge to you.

@gerhard I see what you mean. Perhaps detailed foundational docs like the FS doc and the Docker doc should be in References.

I think there is a conceptual doc that we're missing that explains how to think about using Dagger at a high level with some basic illustrations. Something like this (needs a lot of work): 

> An automation (plan) is typically implemented by pulling in source, strings, secrets, or artifacts from the client, git, or a container registry in the form of strings (can be a whole file), filesystem trees (FS, think directory structure), or container images, then building, testing, deploying by processing them in actions steps.
> 
> These actions themselves run in containers. Many actions employ simple `alpine` images (with more packages added if needed like `bash`, `curl`, `jq`) for the execution environment, but you can use any image that contains tools/commands/content that you need. The actions act on filesystems and their contents (e.g. strings in files): reading (copying or mounting), writing (modifying, exporting), executing (e.g. commands, scripts, API calls).
> 
> The actions create new filesystems or container images as output (optionally writing out to the client or pushing images/artifacts to a registry/artifact repo) and pass those to other actions. This continues until your build, test, or deploy has been accomplished.

**Comment by grouville** [comment]
@gerhard @jpadams. What is the next actionable step that I shall do ?

**Comment by gerhard** [comment]
> @jpadams Perhaps detailed foundational docs like the FS doc and the Docker doc should be in References.

Yes,  I think so too.

> @jpadams: I think there is a conceptual doc that we're missing that explains how to think about using Dagger at a high level with some basic illustrations. Something like this (needs a lot of work):

Yes! That sounds like a great follow-up PR to this one.

> @grouville: What is the next actionable step that I shall do?

My interpretation of @jpadams' last comment is to move this page under **References** & follow-up with another PR which adds a new page that expands on the quote from his comment. I am ready to review & merge that change as soon as you're ready @grouville.

**Comment by crjm** [comment]
If you go to the current redesign preview in #2853, you'll see that the "How it Works" section is a great spot for placing some sort of high-level explanation like the one @jpadams mentioned.

**Comment by grouville** [comment]
> explanation

@jpadams, where should I move it ? `How-it-works` ?

**Comment by crjm** [comment]
Any updates on this?
Reading something like [this](https://documentation.divio.com/explanation/) may point us in the right direction.
I can see two possible paths: 
1. making a "Background" category inside Core Concepts, that explains Dagger's inner workings (explanatory content is not a guide). We can add several explanatory guides here, and give them more visibility on the [how it works page](https://docs.dagger.io/f44rm/how-it-works) or even create a new card in the [Overview](https://docs.dagger.io/) page if it's necessary.
2. We can also make a Recommended section inside Guides, containing what we consider must-read content.

**Comment by dolanor** [comment]
> > Having taken a step back and looking at it from further away, I don't think that this `universe.dagger.io/docker` page belongs under the **Core Concepts** section. This section was meant to cover the high-level, e.g. client, secrets, actions, plan, etc. This specific page seems to be a reference for the Docker package. As great & essential as this doc page is, I would put it under **References**, in a place that people can see it easily (I assume that most users will find it via Search).
> > WDYT @jpadams? Happy to defer the merge to you.
> 
> @gerhard I see what you mean. Perhaps detailed foundational docs like the FS doc and the Docker doc should be in References.

I think that base reference should inform the user on how to use the API: inputs, outputs, what does it do.
Which is what we're doing right now: https://docs.dagger.io/1234/dagger-types-reference

I think that a technical deep dive should have its own category. It could be under reference, (what tailscale does with its [technical overview](https://tailscale.com/kb/tech-overviews/) which is listed in reference: https://tailscale.com/kb/reference/)

So I think the current `dagger.#FS` documentation could be in `Reference > Tech Deep Dive`.
But we should have a simple documentation as well explaining the `dagger.#FS` API succintly. (with link to the deep dive)

For this current documentation (docker), it looks more like a deep dive as well, so I would put it there as well.

**Comment by crjm** [comment]
> I think that base reference should inform the user on how to use the API: inputs, outputs, what does it do. Which is what we're doing right now: https://docs.dagger.io/1234/dagger-types-reference
> 
> I think that a technical deep dive should have its own category. It could be under reference, (what tailscale does with its [technical overview](https://tailscale.com/kb/tech-overviews/) which is listed in reference: https://tailscale.com/kb/reference/)
> 
> So I think the current `dagger.#FS` documentation could be in `Reference > Tech Deep Dive`. But we should have a simple documentation as well explaining the `dagger.#FS` API succintly. (with link to the deep dive)
> 
> For this current documentation (docker), it looks more like a deep dive as well, so I would put it there as well.

+1
I really like the idea of a "Tech Deep Dive" inside References.

If we want to highlight this section so it does not loose visibility (References category is the last in the sidebar) we can do any of the following things:
* Add a CTA for the Deep Dive in the Overview
* Add a CTA for the Deep Dive in "How it Works"
* Add a CTA in related documentation that links to the Deep Dive section (for example at the end of [Building container images](https://docs.dagger.io/1205/container-images/))

**Comment by crjm** [comment]
@jpadams WDYT?

**Comment by grouville** [comment]
We didn't manage to find an arrangement. Closing it for now

**Pull request closed without merging**
