### PR TITLE
feat(project info): output available plans

### PR DESCRIPTION
**Pull request by u-yas**
I found the following documentation with [TODO commented out](https://github.com/dagger/dagger/blob/main/cmd/dagger/cmd/project/info.go#L33). Therefore, I added a function to output Plans in the following format.

example: For a dagger.cue file

### success
input
```cue
package todoapp

import (
	"dagger.io/dagger"

	"dagger.io/dagger/core"
	"universe.dagger.io/netlify"
	"universe.dagger.io/yarn"
)

dagger.#Plan & {
	actions: {
		// Load the todoapp source code 
		source: core.#Source & {
			path: "."
			exclude: [
				"node_modules",
				"build",
				"*.cue",
				"*.md",
				".git",
			]
		}

		// Build todoapp
		build: yarn.#Script & {
			name:   "build"
			source: actions.source.output
		}

		// Test todoapp
		test: yarn.#Script & {
			name:   "test"
			source: actions.source.output

			// This environment variable disables watch mode
			// in "react-scripts test".
			// We don't set it for all commands, because it causes warnings
			// to be treated as fatal errors.
			// See https://create-react-app.dev/docs/advanced-configuration
			container: env: CI: "true"
		}

		// Deploy todoapp
		deploy: netlify.#Deploy & {
			contents: actions.build.output
			site:     string | *"dagger-todoapp"
		}
	}
}

```
output
```
❯ ./dagger-debug project info

Current dagger project in: /Users/uyas/go/src/go.dagger.io/dagger/todoapp
+--------+------------------------------+
| ACTION |           COMMENT            |
+--------+------------------------------+
| source | Load the todoapp source code |
| build  | Build todoapp                |
| test   | Test todoapp                 |
| deploy | Deploy todoapp               |
+--------+------------------------------+

```

### failed
input
```
package todoapp

import (
	"dagger.io/dagger"

	"dagger.io/dagger/core"
	"universe.dagger.io/netlify"
	"universe.dagger.io/yarn"
)

dagger.#Plan & {
	actions: {
	// 	// Load the todoapp source code 
	// 	source: core.#Source & {
	// 		path: "."
	// 		exclude: [
	// 			"node_modules",
	// 			"build",
	// 			"*.cue",
	// 			"*.md",
	// 			".git",
	// 		]
	// 	}

	// 	// Build todoapp
	// 	build: yarn.#Script & {
	// 		name:   "build"
	// 		source: actions.source.output
	// 	}

	// 	// Test todoapp
	// 	test: yarn.#Script & {
	// 		name:   "test"
	// 		source: actions.source.output

	// 		// This environment variable disables watch mode
	// 		// in "react-scripts test".
	// 		// We don't set it for all commands, because it causes warnings
	// 		// to be treated as fatal errors.
	// 		// See https://create-react-app.dev/docs/advanced-configuration
	// 		container: env: CI: "true"
	// 	}

	// 	// Deploy todoapp
	// 	deploy: netlify.#Deploy & {
	// 		contents: actions.build.output
	// 		site:     string | *"dagger-todoapp"
	// 	}
	// }
}
```

output
```
❯ ./dagger-debug project info

Current dagger project in: /Users/uyas/go/src/go.dagger.io/dagger/todoapp
Failed to load dagger plan

imported and not used: "dagger.io/dagger/core":
    ./dagger.cue:6:2
imported and not used: "universe.dagger.io/netlify":
    ./dagger.cue:7:2
imported and not used: "universe.dagger.io/yarn":
    ./dagger.cue:8:2
```

### CODE REVIEW

**Comment by gerhard** [comment]
**Congrats @u-yas for your first contribution!** I started looking into this & I want to add an integration test before merging.

The other thing that needs fixing is to not display hidden actions. In this case, `_alpine` should not be displayed:

image

Want to help out with that?

**Comment by u-yas** [comment]
@gerhard

**Comment by u-yas** [comment]
@gerhard 

Thank you for watching my PR!


> The other thing that needs fixing is to not display hidden actions. In this case, _alpine should not be displayed:
>

I have a question. The condition to determine whether an action is hidden or not is whether the first character is "_". Is that enough?

Also, if you have any, it would be great if you could tell me if there is a document about hidden actions. I looked all over but couldn't find it.

**Comment by gerhard** [comment]
> Thank you for watching my PR!

💪🏻

> I have a question. The condition to determine whether an action is hidden or not is whether the first character is "_". Is that enough?

Yes, that's right.

> Also, if you have any, it would be great if you could tell me if there is a document about hidden actions. I looked all over but couldn't find it.

- https://cuelang.org/docs/tutorials/tour/references/hidden/
- https://docs.dagger.io/1226/coding-style#private-names
- https://github.com/dagger/dagger/blob/954664e6db0f548e10645848d3def287b99d53f6/docs/tests/core-concepts/fs/client/build_image.cue#L12-L15
- https://github.com/dagger/dagger/blob/7aa1b8ad5f9fd9a7dcd6523dac2c08333a66c35a/cmd/dagger/logger/tty2.go#L56-L60

**Comment by u-yas** [comment]
@gerhard 
Thank you for the many documents!

https://github.com/dagger/dagger/pull/3139/commits/a54e3dff9ae8fb529a9283fc3ccc2fc33fb6ca4d

Is there any problem with this change?

**Comment by gerhard** [comment]
> @gerhard Thank you for the many documents!

🙌

> Is there any problem with this change? [a54e3df](https://github.com/dagger/dagger/commit/a54e3dff9ae8fb529a9283fc3ccc2fc33fb6ca4d)

No, it looks good to me.

Everything works as expected on my end @u-yas:

image

Are you OK with my last commit? https://github.com/dagger/dagger/pull/3139/commits/e948e8bd8c3a06d2635ee77a8e0e7875bc1cde84

**Comment by u-yas** [comment]
@gerhard ok！

**Review by gerhard — APPROVED** [review]
👍 🚀

**Pull request merged**
