### PR TITLE
feat(sdk/php): support TRACEPARENT

### PR DESCRIPTION
**Pull request by wingyplus**
Inject `Traceparent` headers into client when `TRACEPARENT` env variable is presents.

Before:

```
✔ Potato.containerEcho(stringArg: "hello"): Container! 1.2s
  ✔ exec /src/sdk/php/potato/entrypoint.php 1.1s | CPU Pressure (some): 163µs | CPU Pressure (full): 148µs
✔ Void.stdout: String! 0.0s
  ✔ cache request: pull docker.io/library/alpine:latest@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d 0.0s
  ✔ load cache: exec echo hello 0.0s
```

After:

```
✔ Potato.containerEcho(stringArg: "hello"): Container! 2.3s
  ✔ exec /src/sdk/php/potato/entrypoint.php 2.2s | CPU Pressure (some): 210µs | CPU Pressure (full): 209µs
  ✔ Container.from(address: "alpine:latest"): Container! 2.0s
    ✔ resolving docker.io/library/alpine:latest 2.0s
      ✘ remotes.docker.resolver.HTTPRequest 0.8s
        ✘ HTTP HEAD 0.8s
      ✔ HTTP GET 0.9s
      ✔ remotes.docker.resolver.HTTPRequest 0.3s
        ✔ HTTP HEAD 0.3s
    ✔ Container.from(address: "docker.io/library/alpine:latest@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d"): Container! 0.0s
      ✔ resolving docker.io/library/alpine:latest@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d 0.0s
  ✔ Container.withExec(args: ["echo", "hello"], expand: false, experimentalPrivilegedNesting: false, insecureRootCapabilities: false, noInit: false, redirectStderr: "", redirectStdout: "", stdin: "", useEntrypoint: false): Container! 0.0s
    ✔ cache request: pull docker.io/library/alpine:latest@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d 0.0s
    ✔ load cache: exec echo hello 0.0s
✔ Container.stdout: String! 0.0s
```

### CODE REVIEW

**Review by carnage — COMMENTED** [review]
Approved from my end

**Review by helderco — APPROVED** [review]
lgtm!

**Comment by helderco** [comment]
@wingyplus, want to add a change log?

**Comment by wingyplus** [comment]
@helderco changelog added. 🙏

**Review by helderco — APPROVED** [review]

**Pull request merged**
