### PR TITLE
sdk: python: Migrate to httpx

### LINKED ISSUE #3693: Migrate to httpx
## Reasons

- Supports [AnyIO](https://anyio.readthedocs.io/en/stable/), which supports both [asyncio](https://docs.python.org/3/library/asyncio.html) (built-in) and [Trio](https://github.com/python-trio/trio) (easier to use);
- Supports both async and sync (currently we're using [aiohttp](https://docs.aiohttp.org) for one and [requests](https://requests.readthedocs.io/en/latest/) for the other);
- Simpler support for unix socket connections (https://github.com/dagger/dagger/issues/3694);

## Todo

- [x] Create _async_ transport for GraphQL client
- [x] Create _sync_ transport for GraphQL client
- [x] Hook them in dagger's `HTTPConnector`
- [x] Sunset _aiohttp_

### PR DESCRIPTION
**Pull request by helderco**
Fixes #3693

Signed-off-by: Helder Correia

### CODE REVIEW

**Comment by helderco** [comment]
This migration and the latest changes to provisioning made it clear that the current architecture isn't the best one.

- The point of the current architecture was to allow for multiple ways to connect to the engine that I was seeing at the time: _http_, _unix socket_, _dial stdio_, _bin_;
- Current dispatch based on `DAGGER_HOST` scheme is essentially only used for provisioning, so rename the `connectors` package to `provision`;
- Move `HTTPConnector` specific code to `Connector` and move `connectors.base` to `connection`.
- With only _httpx_ for sync/async, we can [mount _httpx_ transports](https://www.python-httpx.org/advanced/#mounting-transports) for unix sockets for example, and not do the dispatch ourselves.

**Review by gerhard — APPROVED** [review]
Looks good to me!

---

I can see `alpha.0` & `beta.0` already available: https://github.com/graphql-python/gql/releases

Based on the last `3.4.0` release, there will be at least another `rc` before we can expect `3.5.0` GA. Do you have a rough timeline in mind @leszekhanusz? e.g. 4 weeks for the beta stage, then 4 more weeks for the rc stage before GA can be released.

**Comment by leszekhanusz** [comment]
> Based on the last `3.4.0` release, there will be at least another `rc` before we can expect `3.5.0` GA. Do you have a rough timeline in mind @leszekhanusz? e.g. 4 weeks for the beta stage, then 4 more weeks for the rc stage before GA can be released.

The reason gql is currently in a pre-release is because the latest version uses [graphql-core v3.3.0a2](https://github.com/graphql-python/graphql-core/releases/tag/v3.3.0a2) which is also in a pre-release.
graphql-core itself is dependent on the upstream javascript reference [graphql-js v17.0.0a2](https://github.com/graphql/graphql-js/releases/tag/v17.0.0-alpha.2)

So there is no timeline for a stable version since we are dependent on upstream packages.

httpx support in gql was added very recently in the v3.5.0b0 version and even tough it's a pre-release I believe it should work if you request `gql>=3.5.0b0`

**Comment by helderco** [comment]
Dependency resolution would fail for `strawberry-graphql`, I'll vendor for now.

**Pull request merged**
