### PR TITLE
fix: dagger do help should indicate where to insert action name #2582

### LINKED ISSUE #2582: 🐞 `dagger do` help should indicate where to insert action name
### What is the issue? & Log output

Today if you run `dagger do` or `dagger do --help` you are returned something like

image

It looks like the proper command syntax is `dagger do [flags]`, but it should be something like:

```
dagger do [action] [flags]
```

Note: `[action]` here could be something like `hello` or something like `hello foo bar` to reference a sub-action.
We should probably note that in the CLI help as well.
```
// Hello world
hello: foo: bar: bash.#Run & {
...
```
        
image

Note: A lot of folks [use conventions for which CLI args are required or optional](https://stackoverflow.com/questions/21503865/how-to-denote-that-a-command-line-argument-is-optional-when-printing-usage). If `[]` means optional, then it's true that it's valid to run `dagger do` _without_ an action name or any flags (i.e. action is optional), but we should show where you'd put those in a valid command by making them both optional, but including them both like suggested above.

### Steps to reproduce

`dagger do`
or
`dagger do -h`
or
`dagger do --help`

### Dagger version

0.2.16

### OS version

macOS 12.3.1[](url)

### PR DESCRIPTION
**Pull request by tuongaz**
Fixes #2582 

`dagger do` will print:

```
Usage: 
  dagger do <action> [subaction...] [flags]
```

Signed-off-by: Tuong Le <tuongaz@gmail.com>

### CODE REVIEW

**Review by gerhard — APPROVED** [review]
Thanks for this contribution @tuongaz!

I have made one minor change - `[action]` -> `<action>` - and a few other ["boy scout"](https://www.informit.com/articles/article.aspx?p=1235624&seqNum=6https://www.informit.com/articles/article.aspx?p=1235624&seqNum=6) changes. Works on my machine:

image

As soon as all checks pass, this will get merged.

**Comment by gerhard** [comment]
I just remembered about sub-actions. This is the current output after all the changes:

image

This PR adds the missing `<action> [subaction...]`. [CLI reference]( https://en.wikipedia.org/wiki/Command-line_interface#Command_description_syntax).

**Comment by gerhard** [comment]
The duration of the [**Lint** job in GitHub Actions](https://github.com/dagger/dagger/actions/runs/2861713809/attempts/1) is concerning: **12m 45s**. The same job takes **38s** locally, with an empty cache:

image

The [`ERROR: maximum timeout reached` error](https://github.com/dagger/dagger/runs/7841026783?check_suite_focus=true#step:5:1372) makes me believe that this is cache-related. I would be curious to read what @sipsma thinks. For now, I am just re-triggering. [The second attempt](https://github.com/dagger/dagger/actions/runs/2861713809) took **2m 2s** to succeed. This reminds me what we were talking with @grouville last week: we should try running tests against a dedicated Docker Engine and see if things improve. Putting a pin in this for now, just capturing a thought snapshot for now.

**Comment by gerhard** [comment]
Pretty sure that we have a cache-related issue. [**Experimental Universe** failed in **19m 4s**](https://github.com/dagger/dagger/actions/runs/2861713817) due to another error during cache export: [`FATAL system | failed to execute plan: maximum timeout reached`](https://github.com/dagger/dagger/runs/7844543520?check_suite_focus=true#step:8:1246).

The same test suite passed locally in **1m 42s**:
image

I'm seeing similar failures in other PRs, e.g. https://github.com/dagger/dagger/runs/7844454284?check_suite_focus=true#step:8:2234

Pushing a commit that does not use the cache to see if it fixes the issue.

**Comment by gerhard** [comment]
@tuongaz if all checks pass, I intend to get this merged. Are there any changes that you would like to see before that happens?

**Comment by gerhard** [comment]
♾ 

image

**Comment by tuong-at-wes** [comment]
LGTM, thank you @gerhard

**Pull request merged**
