### PR TITLE
Add release notes fragment instructions

### PR DESCRIPTION
**Pull request by gerhard**
This is a follow-up to:
- https://github.com/dagger/dagger/pull/5408

WDYT?

---
There is a related discussion in https://github.com/dagger/dagger/issues/5475 that you may be interested in.

### CODE REVIEW

**Comment by gerhard** [comment]
Before merging, double-check that https://docs.dagger.io/204441/contributing will get updated as expected.

**Comment by gerhard** [comment]
LGTM:

image

**Comment by gerhard** [comment]
@grouville if you are on the correct branch - `add-release-notes-to-contributing` - then `yarn start` should just work. Maybe try `yarn clear` first, ensure that you don't have another instance running, and try again. Happy to sync on this for a few mins if it helps!

**Comment by grouville** [comment]
> @grouville if you are on the correct branch - `add-release-notes-to-contributing` - then `yarn start` should just work.
> 
> Maybe try `yarn clear` first, ensure that you don't have another instance running, and try running `yarn start` again.
> 
> Happy to sync on this for a few mins if it helps!

`yarn clear` was the solution, as I just did it on main right before 🙏 
image

**Pull request merged**
