### PR TITLE
Python: Support async resolvers and client

### LINKED ISSUE #3300: Python: Add async support
Resolvers should be able to use async code if needed (e.g., calling async libraries or running tasks concurrently).

We can also provide a client with an async transport so you can make async queries on an async resolver, or if you use a script in an async environment. To avoid having different `AsyncClient` and `SyncClient` sort of classes, I'm thinking about using a context manager in a proxy to instantiate the correct client so you'd use them like this:

```python
# async
async with dagger.Client() as session:
    result = await session.execute(...)

# sync
with dagger.Client() as session:
    result = session.execute(...)
```

### PR DESCRIPTION
**Pull request by helderco**
Fixes #3300

Notice: `Engine` needs a bit more work. Specifically running an async subprocess.

### CODE REVIEW

**Comment by samalba** [comment]
It's very nice to support async resolvers from day one. I see that you also replaced the resolver introspection with a proper JSON->Schema converter. I am keen to try this one. If it works as it should, it's gonna take care of all the edge cases that I struggle with before. Very nice!

**Comment by helderco** [comment]
Reverted to draft because I want to improve a couple things.

Python’s async model doesn’t share code with sync so I’m just trying to abstract that away as a convenience. I’m particularly trying to avoid having different `Client` and `AsyncClient` classes. The underlying one is agnostic, what changes is the `Transport` argument for it which is what I’m trying to create under the hood.

Got delayed because I’m unsure of the client factory pattern, but will move on for now. We’ll iterate on the factory if we come up with something better.

**Comment by helderco** [comment]
Rebased.

**Comment by helderco** [comment]
Newly rebased.

**Review by samalba — APPROVED** [review]

**Pull request merged**
