### PR TITLE
website: add environment var to avoid crash issue

### PR DESCRIPTION
**Pull request by slumbering**
signed-off-by: jffarge <jf@dagger.io>

### CODE REVIEW

**Comment by gerhard** [comment]
Still crashing for me:

Screenshot 2022-03-30 at 14 38 46

**Comment by gerhard** [comment]
This works for me:

```diff
❯ g diff
diff --git a/Makefile b/Makefile
index 4cf048ec..84edcb17 100644
--- a/Makefile
+++ b/Makefile
@@ -89,7 +89,7 @@ mdlint: # Markdown lint for web
 .PHONY: web
 web: # Run the website locally
        yarn --cwd "./website" install
-       yarn --cwd "./website" start
+       REACT_APP_AMPLITUDE_ID="" yarn --cwd "./website" start

 .PHONY: todo
 todo: # Find all TODO items
```

**Comment by slumbering** [comment]
Ok. I've created a new script on my package.json + modify the makefile let me know if it's good for you

**Comment by gerhard** [comment]
Yes, it works!

We cannot merge this until the checks are green.

This is the 3rd PR sitting in the queue now:

image

**Comment by slumbering** [comment]
Done

**Review by helderco — APPROVED** [review]

**Pull request merged**
