### PR TITLE
chore(python): place codegen in workspace

### PR DESCRIPTION
**Pull request by helderco**
Makes it easier to manage, and brings back codegen's tests into CI.

> [!warning]
> Stacked on top of https://github.com/dagger/dagger/pull/8072

### CODE REVIEW

**Comment by helderco** [comment]
@jedevc, I added this to the milestone because of the included updates.

**Comment by jedevc** [comment]
Is this one ready to review?

**Comment by helderco** [comment]
> Is this one ready to review?

Just need to fix one problem. Looking into it now.

**Comment by helderco** [comment]
I've split the update and put that PR in the milestone instead.

**Comment by helderco** [comment]
Resolved in https://github.com/dagger/dagger/pull/8311

**Pull request closed without merging**
