### PR TITLE
website: display caution Docusaurus "Admonition"

### PR DESCRIPTION
**Pull request by slumbering**
replace component overwritting by using Admonition to warn users about deprecated documentation

Signed-off-by: user.email <jf@dagger.io>

### CODE REVIEW

**Comment by slumbering** [comment]
@jpadams, following our conversation about users confusion with documentation. I've added caution banners in every markdown file instead of tweaking Docusaurus behavior.

**Review by jpadams — APPROVED** [review]
@slumbering This looks really good for the web user.
One thing we discussed was the experience of a user who is browsing the docs in GitHub or a text editor. Could we make the message more clear for that user by using a piece of markup like this?

```
<CautionBanner alt="Old docs. Not maintained." old="0.1" new="0.2" />
```

**Comment by slumbering** [comment]
> @slumbering This looks really good for the web user. One thing we discussed was the experience of a user who is browsing the docs in GitHub or a text editor. Could we make the message more clear for that user by using a piece of markup like this?
> 
> ```
> <CautionBanner alt="Old docs. Not maintained." old="0.1" new="0.2" />
> ```

Good point! Adding a not used props on CautionBanner component could be confusing though. How about having a comment on each file ?

**Comment by jpadams** [comment]
LGTM! 🚀

**Comment by slumbering** [comment]
> LGTM! 🚀

Done

**Pull request merged**
