### PR TITLE
feat: allow filtering module input directories

### PR DESCRIPTION
**Pull request by jedevc**
Potential fix for #6155.

This is an implementation of @helderco's suggestion in https://github.com/dagger/dagger/issues/6155#issuecomment-1953199174.

I'll add some tests, and such, but thought I'd throw this together so people can try it.

### CODE REVIEW

**Comment by sipsma** [comment]
> This isn't a dealbreaker, but it does make for a rather awkward calling experience - I'm okay with something like this for a first-pass though.

Agreed, you need to deal with this all the time with `grep` or any CLI that accepts globs/regex/etc. It's not awesome but also par for the course.

Overall this approach LGTM

**Comment by sipsma** [comment]
Also, provisionally added this to v0.10.0 milestone since the linked issue is on that milestone. I personally would be okay with it being in v0.10.x instead if time runs low though.

**Comment by sipsma** [comment]
There's still ongoing discussion about how to approach this in https://github.com/dagger/dagger/issues/6155 so I'm going to move this to the `v0.10.x` milestone for now. All the approaches are backwards compatible so I think it's safe to push it to a subsequent minor release.  cc @jedevc

**Comment by jedevc** [comment]
Closing this in preference of #6857.

**Pull request closed without merging**
