### PR TITLE
docs: Tabs for JavaScript & TypeScript

### PR DESCRIPTION
**Pull request by jpadams**
Signed-off-by: Jeremy Adams <jeremy@dagger.io>

### CODE REVIEW

**Comment by jpadams** [comment]
Netlify preview is stale for some reason.

**Review by gerhard — APPROVED** [review]
👍 🚀 https://6375d85498762800083d7519--devel-docs-dagger-io.netlify.app/sdk/nodejs/783645/get-started

image

**Comment by gerhard** [comment]
Leaving merge for you @jpadams in case you want to add more changes.

**Comment by jpadams** [comment]
> Leaving merge for you @jpadams in case you want to add more changes.

I'll leave it for @vikram-dagger to decide to merge 🙌

**Comment by gerhard** [comment]
@vikram-dagger 💪 go for **Squash and merge** when ready:

image

**Pull request merged**
