### PR TITLE
remove llb.SessionID from Host.Directory for now

### PR DESCRIPTION
**Pull request by vito**
This is causing container hostnames to change on every run, causing caches to bust.

We tried changing Container.WithExec to only set a hostname if the container exposes ports, but that breaks two use cases:

1. Calling WithExec before WithExposedPort.
1. Using a container as a service without explicitly exposed ports.

We could stomach temporarily breaking the latter case, but the former case is probably pretty common, since that's what our docs show.

The impact of this change on the other hand should be pretty minor, only breaking the unannounced `dagger do` command, which is already being completely rearchitected such that we can probably approach the intended fix here in a different manner. (#5415)

### CODE REVIEW

**Review by marcosnils — APPROVED** [review]

**Comment by sipsma** [comment]
I really feel like it's worth a quick shot at removing the need to set the hostname directly in `WithExec` while retaining backwards compatibility in the current service API.

If we leave in setting the hostname for all execs based on the unresolved LLB digest then we're leaving in all the other pre-existing problems it caused in terms of extra cache invalidations and just kicking the can very slightly down the road since the need to set session ID in local LLB is not going away.

Options for getting rid of setting the hostname in `WithExec` and instead setting it only on service execs (that don't involve huge radical changes):
1. A `pb.Definition` can be turned back into an `llb.Definition` and then unpacked into the individual pb ops for each op type. We can then update the hostname setting there and remarshal back to pb. This is not exactly" fun", but it's explicitly supported and done in a few places in buildkit's own code. We'd be able to do this anytime after `WithExec` is called
2. We already have the [`cacheMap` ](https://github.com/sipsma/dagger/blob/2b1dbb30461468a7662cf505e485e0999909afee/core/cachemap.go#L18-L18) util which allows us to map ids->anything, so we could use that to store the mapping of `ContainerID` -> `llb.ExecState` for the container and then retain the ability to only set the hostname in LLB in the methods that spin up the service container.

I realize time is limited, so I'm not opposed to this PR as is if we need to get a release out and/or none of the above works out.

**Comment by marcosnils** [comment]
@vito I'll defer the decision to you since you since you know this part of the codebase better :pray:

**Comment by vito** [comment]
> If we leave in setting the hostname for all execs based on the unresolved LLB digest then we're leaving in all the other pre-existing problems it caused in terms of extra cache invalidations and just kicking the can very slightly down the road since the need to set session ID in local LLB is not going away.

The hostnames are removed entirely in #5322 so this seemed like the most expedient way to fix the regression without rocking the boat too much. At that point I figured we can bring the session ID back, if we need to. I wasn't sure if it would still be necessary with the new architecture, but it sounds like it would be.

If we can't trust LLB digests to be stable across sessions anymore we're going to need a new way to generate content-addressed hostnames, or a new way for containers to address each other. If I run a service based on a `Host.directory` with stable content (e.g. server config), client call sites shouldn't have their caches busted every time because of the hostname changing.

Maybe we'll just need to compute a hash some other way, ignoring certain metadata fields like the session ID?

Either way, I can take a look at both of those alternative approaches on Monday; sounds kinda fun!

**Comment by vito** [comment]
Closing in favor of #5474

**Pull request closed without merging**
