### PR TITLE
chore: update dagger-modules-test to new latest commit

### PR DESCRIPTION
**Pull request by grouville**
Tom updated the dagger-modules-test repo to include context-directory tests. I updated the repo state to all mirror repos.

This PR updates the test suite to new latest commit

### CODE REVIEW

**Review by jedevc — DISMISSED** [review]

**Comment by jedevc** [comment]
Tests are legitimately failing:https://dagger.cloud/dagger/traces/e49e618fdf256241eae7d38e40b5eee8?span=12992cad856623fa#1ef0c0c4e9ef00a7

```
cache request: git://github.com/dagger/dagger-test-modules.git
295ms

error fetching default branch for repository git@github.com:dagger/dagger-test-modules.git: git error: exit status 128 stderr: ERROR: Permission to dagger/dagger-test-modules.git denied to deploy key fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. 
```

:eyes: not sure what's going on here?

**Comment by grouville** [comment]
> Tests are legitimately failing:https://dagger.cloud/dagger/traces/e49e618fdf256241eae7d38e40b5eee8?span=12992cad856623fa#1ef0c0c4e9ef00a7
> 
> ```
> cache request: git://github.com/dagger/dagger-test-modules.git
> 295ms
> 
> error fetching default branch for repository git@github.com:dagger/dagger-test-modules.git: git error: exit status 128 stderr: ERROR: Permission to dagger/dagger-test-modules.git denied to deploy key fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. 
> ```
> 
> 👀 not sure what's going on here?

Yeah, I remember now why I used my fork: 
image


Need to add the public key on the official repo cc @gerhard

**Comment by grouville** [comment]
Double SSH key seems to work 😄 👼 I'll dig a bit more on https://github.com/dagger/dagger/issues/8288 after PAT support is finished

**Comment by grouville** [comment]
cc @marcosnils

**Review by marcosnils — APPROVED** [review]

**Pull request merged**
